### ISSUE TITLE
zsh doesn't work

### ISSUE THREAD

**Issue by KafuChinoDesu** [tbodt/ish#103]
zsh and bash don't work with Bad system call

**Comment by tbodt** [comment]
bash is fixed, zsh is a separate issue.

**Comment by tbodt** [comment]
zsh now starts up, but the prompt is `\h:\w \$`

**Comment by tbodt** [comment]
Prompt is actually not a zsh bug, it's just the setting in /etc/profile, which isn't in the syntax zsh supports. However it crashes with "bad system call" when you try to run a command. It's sigsuspend.

**Comment by tbodt** [comment]
It works for you on the latest build? Maybe there was a zsh update since I tried it.

**Comment by SConaway** [comment]
`nano`, `apk`, and `git` work.

**Comment by tbodt** [comment]
The program will run, but then zsh will crash and leave you at the regular ash prompt.

**Comment by SConaway** [comment]
Which one?

**Comment by tbodt** [comment]
Any program will do this, that I know of.

**Comment by SConaway** [comment]
But does the `ash` prompt run it?

**Comment by tbodt** [comment]
No, it's started by zsh. The bug is that after starting the program, zsh crashes.

**Comment by SConaway** [comment]
I'm confused

**Comment by tbodt** [comment]
Fixed now.
