### ISSUE TITLE
Elixir/iex doesn't work

### ISSUE THREAD

**Issue by gpmcadam** [tbodt/ish#104]
Installing Elixir with `apk add elixir` then trying to run the `iex` repl results in:

```
erts_poll_init(): Failed to get max number of files: unknown                                                                                                      
Aborted
```

**Comment by shadowfacts** [comment]
IEx still fails, though now with a different set of errors:

```
# iex
Segmentation fault
# dmesg
20 missing syscall 66
25 page fault on 0xf7ed21c8 at 0x566a1cb9
24 page fault on 0x0 at 0x0
22 missing syscall 309
```

**Comment by tbodt** [comment]
The error is now `TODO select on multiple fds`

**Comment by jbosse** [comment]
The error I get in 1.0 (45) is that iSH crashes. 😬

**Comment by shadowfacts** [comment]
As of 1.0 (49), running `iex` and `elixir -e "IO.puts(\"test\")"` still both crash (though, one attempt I got a segfault, and some dmesg errors that I lost, not sure if that was a fluke).

[Crash dump](https://gist.github.com/shadowfacts/45ccf6ffd882ce93aa4064b9530178df)

**Comment by jbosse** [comment]
Still crashes or segmentation faults in 57. 😢

**Comment by tbodt** [comment]
The crashes were because it was randomly overestimating the number of available CPU cores and starting 400 threads, which is apparently enough to cause random crashes. That's fixed, now it's trying to use timerfd.

**Comment by jbosse** [comment]
Thats a lot of threads, even for Elixir. :-) This stuff is too low level for me to be helpful, but if you need any frontend or documentation help, let me know.

**Comment by tbodt** [comment]
So now the erlang repl starts *sometimes*. Other times it crashes spectacularly, or infinitely prints logs such as

    (no logger present) unexpected logger message: {log,error,"Error in process ~p with exit value:~n~p~n",[<0.41.0>,{badarg,[{ets,lookup,[ac_tab,{env,kernel,error_logger_format_depth}],[]},{application_controller,get_env,2,[{file,"application_controller.erl"},{line,333}]},{error_logger,get_format_depth,0,[{file,"error_logger.erl"},{line,574}]},{proc_lib,get_process_messages,1,[{file,"proc_lib.erl"},{line,559}]},{proc_lib,get_messages,1,[{file,"proc_lib.erl"},{line,555}]},{proc_lib,my_info_1,3,[{file,"proc_lib.erl"},{line,528}]},{proc_lib,my_info,4,[{file,"proc_lib.erl"},{line,520}]},{proc_lib,crash_report,4,[{file,"proc_lib.erl"},{line,509}]}]}],#{error_logger=>#{emulator=>true,tag=>error},gl=><0.0.0>,pid=><0.41.0>,time=>1569907584378715}}
