### ISSUE TITLE
Rtdsc crashes app on iPad Air

### ISSUE THREAD

**Issue by zhuowei** [tbodt/ish#106]
The `rtdsc` instruction causes a crash on iPad Air (iOS 12.1, ish compiled from source).

![rtdsc_cropped](https://user-images.githubusercontent.com/704768/48667201-fcf0f580-ea85-11e8-8ee9-1d96801c5e96.png)

It seems the iPad Air's performance counter is disabled by iOS: I checked; [its processor has it](https://github.com/llvm-mirror/llvm/blob/0ea548887e95f988fd3a13f4f3c703166563559b/lib/Target/AArch64/AArch64.td#L388) but accessing it in any app immediately crashes the application.

I can reproduce it even in a regular iOS app:

```
@implementation ViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    NSLog(@"%llu", __builtin_readcyclecounter());
}
```

Also crashes on the `mrs PMCCNTR_EL0` instruction, with or without the debugger attached.

Maybe, for older iPads, this instruction needs to call one of the Mach counter methods instead?

**Comment by tbodt** [comment]
Interesting, I just tried on an iPod touch and it did the same thing. I guess this code never actually worked, and nobody noticed because nothing on alpine tries to do rdtsc. I suppose this should be replaced with a call to mach_absolute_time() or something.

**Comment by saagarjha** [comment]
@zhuowei I'm guessing that iOS, by default, doesn't enable access to the `PMCCNTR_EL0` register to userspace, even if the processor supports it (very few OSes actually do); I doubt this would be selectively disabled on iPad Air and somehow enabled on newer processors. If anyone has a newer device I'm sure they could try this, but I'm not optimistic this would work on any of them.

**Comment by tbodt** [comment]
PMCCNTR_EL0 also doesn't work on raspberry pi. Guess I need a replacement.

**Comment by saagarjha** [comment]
Would `clock_gettime(CLOCK_MONOTONIC, …)` be good enough? On my system, that's basically the same as `mach_continuous_time()`.

**Comment by tbodt** [comment]
Probably, I'm about to push some code that uses that.

**Comment by saagarjha** [comment]
Can confirm that this seems to work correctly on my iPad.

**Comment by tbodt** [comment]
This is fixed now.
