### ISSUE TITLE
How often does TestFlight update?

### ISSUE THREAD

**Issue by NorthIsUp** [tbodt/ish#110]
I’m seeing all the bugs close and was wondering when do testers get to test them?

**Comment by tbodt** [comment]
I'm planning to push an update in a day or two after I fix a couple more bugs.

**Comment by yjqiang** [comment]
> I'm planning to push an update in a day or two after I fix a couple more bugs.

Time to push an update now? I don't have a Mac. 😢

**Comment by Mnpn03** [comment]
An update be released soon.

**Comment by yjqiang** [comment]
> An update be released soon.

I didn't see the news on Twitter. Can't wait to try the new features.

**Comment by yjqiang** [comment]
> > An update be released soon.
> 
> I didn't see any news on Twitter. Can't wait to try the new features.

**Comment by tbodt** [comment]
New estimate: a day or two after i fix one more bug. Though Hofstadter’s law states: “It always takes longer than you expect, even if you take Hofstadter’s law into account.”

**Comment by tbodt** [comment]
After this update I’m going to update more often, after fixing a significant bug or program.

**Comment by NorthIsUp** [comment]
Is it possible to set up a build server that does a new build on each commit?

**Comment by tbodt** [comment]
It's possible, but TestFlight deployment is really tricky to automate. Also you probably don't want a new build on every commit, there's often a lot of broken stuff. Though I suppose there could be a different public link for the continuous builds.

**Comment by yjqiang** [comment]
> New estimate: a day or two after i fix one more bug. Though Hofstadter’s law states: “It always takes longer than you expect, even if you take Hofstadter’s law into account.”

My fault. Sorry.

**Comment by tbodt** [comment]
New build was pushed today.
