### ISSUE TITLE
Working Copy Support

### ISSUE THREAD

**Issue by jcampbell05** [tbodt/ish#120]
Going to be really cool if we have this https://twitter.com/twolivesleft/status/1065247954938716161

**Comment by ELChris414** [comment]
It would actually be quite cool I agree. I guess we are getting there with the Files App support, so you could say that this is a feature that Working Copy should handle, not sure tho

**Comment by yjqiang** [comment]
Ish doesn't have to change anything. Any applications which are using "file" can do that with Working Copy.

**Comment by ELChris414** [comment]
That’s great! That just means that the Files app integration has to become more robust and it should work

**Comment by yjqiang** [comment]
@jcampbell05 I hope I didn't misunderstand your words.

**Comment by tbodt** [comment]
Closing in favor of #231
