### ISSUE TITLE
Apk not working

### ISSUE THREAD

**Issue by CaptnFuret** [tbodt/ish#123]
Not-an-iPhone-6S-Plus:~# apk update                   
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x
86/APKINDEX.tar.gz                                    
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.8/main:
 temporary error (try again later)                    
WARNING: Ignoring APKINDEX.adfa7ceb.tar.gz: No such fi
le or directory                                       
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/commun
ity/x86/APKINDEX.tar.gz                               
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.8/commu
nity: temporary error (try again later)               
WARNING: Ignoring APKINDEX.efaa1f73.tar.gz: No such fi
le or directory                                       
2 errors; 13 distinct packages available              
Not-an-iPhone-6S-Plus:~#  

I can’t get any apk command to work...

**Comment by Mnpn03** [comment]
What does `cat /etc/resolv.conf` say?

**Comment by CaptnFuret** [comment]
Not-an-iPhone-6S-Plus:~# cat /etc/resolv.conf         
Not-an-iPhone-6S-Plus:~#

**Comment by Mnpn03** [comment]
Weird. Run `echo "nameserver 8.8.8.8" > /etc/resolv.conf` and try apk again

**Comment by CaptnFuret** [comment]
Same error

**Comment by bizimburak** [comment]
Help me

**Comment by bizimburak** [comment]
Burak--iPhone:~# apk add python3
WARNING: Ignoring file:///ish/apk/main/x86/APKINDEX.tar.gz: IO ERROR
WARNING: Ignoring file:///ish/apk/community/x86/APKINDEX.tar.gz: Interrupted system call
ERROR: unsatisfiable constraints:
  python3 (missing):
    required by: world[python3]
Burak--iPhone:~#

**Comment by 62f** [comment]
@bizimburak run an analysis and send the report to @tbodt
