### ISSUE TITLE
pip cannot install any packages.

### ISSUE THREAD

**Issue by stevewangv** [tbodt/ish#125]
![afaae104-9cf7-4feb-be28-d65ccad91778](https://user-images.githubusercontent.com/12782946/48986941-55468800-f155-11e8-845d-57b3fdc27cb0.png)

**Comment by tbodt** [comment]
I've gotten a report that it can install some packages (though most packages will have issues). Did you by any chance rotate your phone or tap the terminal while installing?

**Comment by stevewangv** [comment]
I tried to rotate phone but it was same.

**Comment by stevewangv** [comment]
I try to use apk install some packages, but python cannot find them.
![2d7af6e3-a6d1-48d0-a794-f50f73adf652](https://user-images.githubusercontent.com/12782946/48987753-81b1d280-f15c-11e8-90c3-16720b0677a6.png)

**Comment by kweitzner** [comment]
I can't find anything that I can actually do - even just "pip" results in "Illegal Instruction".  Pretty exciting development though - would love to be able to run Python libraries that aren't in Pythonista like Pandas.

**Comment by tbodt** [comment]
@kweitzner Just `pip` shouldn't give illegal instruction, are you on the latest version?

**Comment by kweitzner** [comment]
@tbodt Apologies, thought I was on the latest version.. but yes it works now.  Getting segmentation faults/bad system calls on lot of packages but pip itself works fine.

**Comment by tbodt** [comment]
The segfault was fixed in e95a2acbdd876a11fefb531637777f539445e86c.

**Comment by jiaaro** [comment]
for anyone finding this in the future, if pip doesn’t work, try easy_install as well (if possible for your use case)
