### ISSUE TITLE
File system no longer showing up in Files app

### ISSUE THREAD

**Issue by goerz** [tbodt/ish#128]
Since updating to today's Testflight release, in the Files app, `iSH` still shows up in Locations, but it does not show any files or folders, nor does it allow creating folders, or dragging in any files.

This is relevant to #120

**Comment by kkk669** [comment]
Same here. Nothing has been shown since I updated iSH via TestFlight today. The last version had shown the root filesystem.

![GitHawk Upload by kkk669](https://i.imgur.com/xmS3bCo.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Mnpn03** [comment]
I can replicate this on build 32 on iOS 12.

**Comment by tbodt** [comment]
Bisected to cce46316366b0de522e80c507feeb566e59e6ab8.

**Comment by tbodt** [comment]
Fixed in https://github.com/tbodt/ish/commit/9ae3d8e0e97a69abe17477869e1226ef4fbc80a5.
