### ISSUE TITLE
Network unavailable on iPhone 8/ios12

### ISSUE THREAD

**Issue by rieonke** [tbodt/ish#130]
Reon-iPhone:~# apk update                        
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/m
ain/x86/APKINDEX.tar.gz                          
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.8/
main: temporary error (try again later)          
WARNING: Ignoring APKINDEX.adfa7ceb.tar.gz: No su
ch file or directory                             
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/c
ommunity/x86/APKINDEX.tar.gz                     
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.8/
community: temporary error (try again later)     
WARNING: Ignoring APKINDEX.efaa1f73.tar.gz: No su
ch file or directory                             
2 errors; 13 distinct packages available         
Reon-iPhone:~# cat /etc/resolv.conf              
nameserver 240.0.0.2                             
Reon-iPhone:~# echo "nameserver 8.8.8.8" > /etc/r
esolv.conf                                       
Reon-iPhone:~# apk update                        
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/m
ain/x86/APKINDEX.tar.gz                          
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.8/
main: temporary error (try again later)          
WARNING: Ignoring APKINDEX.adfa7ceb.tar.gz: No su
ch file or directory                             
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/c
ommunity/x86/APKINDEX.tar.gz                     
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.8/
community: temporary error (try again later)     
WARNING: Ignoring APKINDEX.efaa1f73.tar.gz: No su
ch file or directory                             
2 errors; 13 distinct packages available         
Reon-iPhone:~# ifconfig                          
ifconfig: /proc/net/dev: No such file or director
y                                                
ifconfig: ioctl 0x8912 failed: Invalid argument  
Reon-iPhone:~# ls -al /proc                      
total 0                                          
dr-xr-xr-x    2 root     root            64 Jan  
1  1970 .                                        
drwx------   18 root     root           576 Jan  
1  1970 ..                                       
Reon-iPhone:~#

**Comment by halfdev** [comment]
It doesn’t do this automatically, just do ``echo “nameserver 8.8.8.8 > /etc/resolv.conf``

**Comment by tbodt** [comment]
It is supposed to do that automatically.

**Comment by shikil** [comment]
I have same error on iPhone X/iOS 12 after switching Wi-fi network, just kill the app and restart than fix.

**Comment by tbodt** [comment]
Closing as norepro
