### ISSUE TITLE
Prevent device sleep while a command is running

### ISSUE THREAD

**Issue by fcy** [tbodt/ish#131]
I'm using `youtube-dl` to download videos and it takes its time as expected. The problem I'm having is if the device goes to sleep the download stops (also expected), my suggestion is to prevent device from sleep when a command is running or give an option to enable it manually.

**Comment by tbodt** [comment]
There could be a setting for this, but it's easier to always keep the screen on.

**Comment by fcy** [comment]
Not sure if I understand, I did mean to have a way to keep the screen on. Right now I have to keep touching it to keep it awake. The suggestion is to have iSH do it for me.

**Comment by tbodt** [comment]
I mean it's easier to always have iSH keep the screen automatically, rather than adding a setting.

**Comment by fcy** [comment]
Nevermind, I just saw the commit! That was fast, thank you.
