### ISSUE TITLE
Doesn’t support Solid Keyboard

### ISSUE THREAD

**Issue by FlintyLemming** [tbodt/ish#132]
Bluetooth keyboard doesn’t work.

**Comment by tbodt** [comment]
I've tested with apple's smart keyboard and that works; as far as I know the api is the same for bluetooth keyboards.

**Comment by FlintyLemming** [comment]
But my magic keyboard doesn’t work, you can check this video.
https://youtu.be/S0mRjaIiUso

**Comment by tbodt** [comment]
@lamphobic recorded this video to demonstrate https://www.youtube.com/watch?v=ccb5SQDDXHk
