### ISSUE TITLE
Doesn't support Pinyin Keyboard.

### ISSUE THREAD

**Issue by yjqiang** [tbodt/ish#133]
I can't input anything with Pinyin Keyboard. I'm not sure about others. But English Keyboard works well.

**Comment by tbodt** [comment]
I haven't put any thought into IME support, so I'm not surprised it doesn't work.

**Comment by KafuChinoDesu** [comment]
@tbodt Surprisingly, recent update made iSH support Korean input/output fluently!

**Comment by crazywhalecc** [comment]
So can iSH support IME and external keyboard IME?

**Comment by tbodt** [comment]
Probably
