### ISSUE TITLE
tmux crashes the terminal.

### ISSUE THREAD

**Issue by Ladizii** [tbodt/ish#134]
Termux crashes the app when you run it, but you're able to install it properly and everything like normally.

**Comment by tbodt** [comment]
tmux is going to be hard to get working because it requires pseudoterminals. But it should give a "bad system call", not crash the app. Termux is unrelated to tmux, title updated.

**Comment by Ladizii** [comment]
I confused it for a second, anyways it does crash the app.

**Comment by tbodt** [comment]
Gonna close this as duplicate of #46
