### ISSUE TITLE
Ruby gem install doesn't work

### ISSUE THREAD

**Issue by MattKevan** [tbodt/ish#135]
Installing a Ruby Gem fails:

``` 
apk add ruby
gem install bundler

ERROR: While executing gem... (Errno::EBADF)
Bad file descriptor - not a socket file descriptor
```

**Comment by sausheong** [comment]
This error doesn’t show in release 35. Instead I get this now
![img_0054](https://user-images.githubusercontent.com/5962/49708255-d596de00-fc69-11e8-885d-156263590237.png)

**Comment by MattKevan** [comment]
Yes, I get that message now as well.

Running dmesg returns:

```5 missing sys call 309```

**Comment by tbodt** [comment]
Turns out implementing ppoll fixed it. It now says
```
Fetching: bundler-1.17.2.gem (100%)
Successfully installed bundler-1.17.2
ERROR:  While executing gem ... (Gem::DocumentError)
    RDoc is not installed: cannot load such file -- rdoc/rdoc
```
which is what it says on a real alpine install.

**Comment by tbodt** [comment]
Errors like that are a natural consequence of chopping up things that were intended as one package into multiple packages. Installing ruby-rdoc and ruby-irb helps.

**Comment by tbodt** [comment]
```
Successfully installed bundler-1.17.2
Parsing documentation for bundler-1.17.2
Installing ri documentation for bundler-1.17.2
Done installing documentation for bundler after 522 seconds
1 gem installed
```
You may want to use `gem install -N` to skip documentation generation.
