### ISSUE TITLE
R doesn't work

### ISSUE THREAD

**Issue by ajaypillarisetti** [tbodt/ish#136]
R (a statistical environment) doesn't work; exits with bad system call.

apk add R
apk add R-dev

Many thanks. This is amazing!

**Comment by ajaypillarisetti** [comment]
Sure, thanks! It’s 274.

**Comment by tbodt** [comment]
That's the same one numpy needs, interestingly.

**Comment by tbodt** [comment]
R now reports a large number of file not found errors for files that exist.

**Comment by tbodt** [comment]
This seems to be due to missing /proc/self/fd #148

**Comment by tbodt** [comment]
its working now !
