### ISSUE TITLE
Memory Error when pip3 install packages 

### ISSUE THREAD

**Issue by stevewangv** [tbodt/ish#138]
When pip unpack file, there will be a memory error.
![c7e17db9-f725-4705-ad72-afb8317112cf](https://user-images.githubusercontent.com/12782946/49323650-a5f52100-f559-11e8-848d-5c8670ad2104.png)

**Comment by tbodt** [comment]
Which package did you try to install?

**Comment by stevewangv** [comment]
I was installing numpy.

**Comment by stevewangv** [comment]
I can use “apk add py3-numpy” to install numpy now, but when I import it, it will bad system call.
![1a457524-eaa0-4d84-9d68-9d255e0909dc](https://user-images.githubusercontent.com/12782946/49323682-12702000-f55a-11e8-91b9-e75976baa393.jpeg)

**Comment by tbodt** [comment]
What bad system call? `dmesg` will tell you.

**Comment by stevewangv** [comment]
missing syscall 274

**Comment by tbodt** [comment]
Freakin numa

**Comment by tbodt** [comment]
Report of same thing happening with `pip3 install -U pip`: https://twitter.com/stephenloo1/status/1068741254471573506

**Comment by tbodt** [comment]
Numpy seems to work now.

**Comment by sausheong** [comment]
Still doesn’t work for me. Also problem installing Pandas as well (missing syscall)
![img_0033](https://user-images.githubusercontent.com/5962/49335735-6fd5a100-f62e-11e8-80ec-5c32111d867b.png)

**Comment by sausheong** [comment]
No I didn't. I'm using the TestFlight version.

**Comment by adrianrocamora** [comment]
Hi all, is the fix in TestFlight yet or should I go ahead and build from source?

**Comment by tbodt** [comment]
This should be fixed in TestFlight.

**Comment by adrianrocamora** [comment]
Ah, well I tried it a few hours ago and thenew error is related to OpenBLAS and the cache:
```
OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
Illegal instruction
```

**Comment by tbodt** [comment]
That's a different problem, can you open a new issue?

**Comment by adrianrocamora** [comment]
Sure thing, thanks!

**Comment by adrianrocamora** [comment]
Here's the new issue, thank you for your prompt responses https://github.com/tbodt/ish/issues/377python3>>> import numpy
