### ISSUE TITLE
Strange behavior when editing iSH files via Files app

### ISSUE THREAD

**Issue by shadowfacts** [tbodt/ish#139]
I've run into some strange behavior when editing files from iSH in external apps via the Files.app provider.

This happens when using the [Kodex](https://itunes.apple.com/app/kodex/id1038574481?ls=1&mt=8) quick edit feature.

I created a file in iSH, then edited it in Kodex from the Files app, and saved the file.

When returning to iSH, I can `cat` the file and the modified output is printed, but running `ls` produces an unexpected "no such file or directory" message. The file can't be deleted using `rm`, it produces the same error message. `unlink` must be used to remove it.

Screenshot of the issue:

![image](https://user-images.githubusercontent.com/7091588/49323739-f59e0300-f4ed-11e8-83d4-9413943c9b7f.png)

**Comment by tbodt** [comment]
Closing in favor of #231
