### ISSUE TITLE
Feature Request: Dark Mode(s)

### ISSUE THREAD

**Issue by sirredbeard** [tbodt/ish#14]
This is a feature request for dark mode(s). Preferably, a choice between current black-on white, plus a white-on-black, green-on-black, and solarized-on-black theme.

**Comment by tbodt** [comment]
Done in #72

**Comment by apas** [comment]
Hi @tbodt, I just want to ask -- would it be possible (or is in the roadmap) to also ship Solarized Light / Dark themes along with Light, Dark, l337? Thanks.
