### ISSUE TITLE
Stuck at screen while running pip3 install

### ISSUE THREAD

**Issue by sausheong** [tbodt/ish#143]
Pip3 installation stuck after downloading. It’s not because of tapping the screen, tried that.

![img_0005](https://user-images.githubusercontent.com/5962/49324673-94b60f80-f56d-11e8-9904-125d59e15cd4.png)

**Comment by tbodt** [comment]
It's compiling numpy from source, which is not something that really is likely to work at the moment. You can get numpy binaries from apk.

**Comment by sausheong** [comment]
Tried that and it works. Thanks!
