### ISSUE TITLE
youtube-dl failing to merge formats via ffmpeg

### ISSUE THREAD

**Issue by viticci** [tbodt/ish#147]
After downloading separate video and audio tracks for a video via `youtube-dl` with the following command:

`youtube-dl -f 313+251 https://www.youtube.com/watch?v=JiwIuWFLv-U`

iSH fails to merge formats at the end, returning the following encoder error via ffmpeg:

```                                                                                                         
[youtube] JiwIuWFLv-U: Downloading webpage                                                                                                                                                
[youtube] JiwIuWFLv-U: Downloading video info webpage                                                                                                                                     
[download] Destination: What's on my iPad Pro!-JiwIuWFLv-U.f313.webm                                                                                                                      
[download] 100% of 677.26MiB in 07:48                                                                                                                                                     
[download] Destination: What's on my iPad Pro!-JiwIuWFLv-U.f251.webm                                                                                                                      
[download] 100% of 8.06MiB in 00:05                                                                                                                                                       
[ffmpeg] Merging formats into "What's on my iPad Pro!-JiwIuWFLv-U.webm"                                                                                                                   
ERROR: Unknown encoder 'copy'
```

For context, here is the successful output for the same command from macOS:

```
[youtube] JiwIuWFLv-U: Downloading webpage
[youtube] JiwIuWFLv-U: Downloading video info webpage
[download] Resuming download at byte 85454848
[download] Destination: What's on my iPad Pro!-JiwIuWFLv-U.f313.webm
[download] 100% of 677.26MiB in 01:23
[download] Destination: What's on my iPad Pro!-JiwIuWFLv-U.f251.webm
[download] 100% of 8.06MiB in 00:01
[ffmpeg] Merging formats into "What's on my iPad Pro!-JiwIuWFLv-U.webm"
Deleting original file What's on my iPad Pro!-JiwIuWFLv-U.f313.webm (pass -k to keep)
Deleting original file What's on my iPad Pro!-JiwIuWFLv-U.f251.webm (pass -k to keep)
```

**Comment by Drvolks** [comment]
You’re right it’s a ffmpeg issue. 

ffmpeg -i video.mp4 -i audio.m4a -c:v copy -c:a copy output.mp4

Will result in the same « Unknown encoder 'copy' » error.

-loglevel debug doesn’t reveal any hint on the underlying issue:

Successfully opened the file.                                                                                                                          
Parsing a group of options: output url output.mp4.                                                                                                     
Applying option c:v (codec name) with argument copy.                                                                                                   
Applying option c:a (codec name) with argument copy.                                                                                                   
Successfully parsed a group of options.                                                                                                                
Opening an output file: output.mp4.                                                                                                                    
Unknown encoder 'copy'

**Comment by tbodt** [comment]
This smells like some kind of subtle CPU bug that takes a day to debug and is fixed by changing 1 character.

**Comment by tbodt** [comment]
I just tried ffmpeg on the "you've been gnomed" video and it seems to be working now. Maybe there was an ffmpeg update? Maybe it's only broken on aarch64? (likely)

**Comment by cliss** [comment]
Just `apk del`’d everything and then re-added it, and still can’t use the `copy` encoder.

So weird.

**Comment by tbodt** [comment]
It's definitely an arm64-specific CPU bug, it doesn't work on iOS but it does work on my computer

**Comment by tbodt** [comment]
Fixed now, it was a screwup in 8-bit string compares.

**Comment by cliss** [comment]
@tbodt 
1) Thanks!! Stoked to try it!!
2) Purely out of curiosity, was 5b4807c the commit that fixed it?
3) `# setting flags: a horror story` 🤣 you write comments like I do

**Comment by tbodt** [comment]
Yup, https://github.com/tbodt/ish/commit/5b4807c8a5f56d683e2c6191010d5993373a9606 was the fix. Checking overflow on 8-bit subtraction on arm64 is the third hard problem in computer science.

**Comment by cliss** [comment]
Hahahahahahahaha 🤣🤣🤣

**Comment by cliss** [comment]
Excuse me for being a bit over enthusiastic, but...

OMFG IT WORKS AND IT’S SO DAMN FAST LOOK AT THIS
