### ISSUE TITLE
procfs is not implemented

### ISSUE THREAD

**Issue by chubchubsancho** [tbodt/ish#148]
```
# top
top: no process info in /proc
# ls -la /proc

```

**Comment by joefitzgerald** [comment]
`top` now crashes the app in build 40.

**Comment by Mnpn03** [comment]
I can replicate the top crash in build 39 (and 40).
[iSH-2018-12-28-153155.ips.zip](https://github.com/tbodt/ish/files/2715026/iSH-2018-12-28-153155.ips.zip)
(GitHub doesn’t allow that file format so here’s a .zip)

**Comment by tbodt** [comment]
procfs now exists

**Comment by feng5** [comment]
I met the error in 1.0(52)
```
# cat /proc/cpuinfo
cat: can't open '/proc/cpuinfo': No such file or directory
```

**Comment by tbodt** [comment]
@feng5 Please open a new issue
