### ISSUE TITLE
git authentication doesn’t work

### ISSUE THREAD

**Issue by negebauer** [tbodt/ish#150]
When cloning a private github repo it fails with the message

```js
fatal: could not read Username for 'https://github.com': No such file or directory
```

Running `dmesg` outputs

```sh
dmesg                          
FIXME no support for shared futexes              
FIXME no support for shared futexes              
FIXME no support for shared futexe
```

Related to https://github.com/tbodt/ish/blob/fc157975f7564ebd5e0d643330148133e3f154b1/kernel/futex.c#L99

**Comment by tbodt** [comment]
I'm almost certain this is the same as the issue with ssh reading passwords: missing /dev/tty.

**Comment by MattKevan** [comment]
I've had the same error trying to install Django via Pip – I guess it's also cloning a git repo. I get an almost endless stream of ```FIXME:``` errors, with one lone ```34 missing sys call 329``` thrown in for good luck.

**Comment by tbodt** [comment]
Syscall 329 is #142

**Comment by tbodt** [comment]
The password reading is now fixed.

**Comment by tbodt** [comment]
@negebauer Run `mknod /dev/tty c 5 0`, that should fix it.
