### ISSUE TITLE
Cursor runs off screen when using a hardware keyboard

### ISSUE THREAD

**Issue by yaakov-h** [tbodt/ish#154]
When using the Apple Smart Keyboard Folio, the cursor initially starts on-screen, but after enough new lines are rendered, it slips below the options/autocorrect keyboard bar.

Opening and dismissing the settings dialog works around the bug and resets the cursor position.

![img_0070](https://user-images.githubusercontent.com/426009/49346856-5e52ce80-f6ec-11e8-9f95-3315ab8c5605.png)

To reproduce:

1. Attach a hardware keyboard
2. Open iSH
3. Press enter until the cursor runs below the bar

**Comment by tbodt** [comment]
This also affects virtual keyboards. Fixed in 55adf8103f81cd9cc8a781f0bdc183defe7bcd12.
