### ISSUE TITLE
pip install failed with error code -31 and IPython meets disk I/O error

### ISSUE THREAD

**Issue by stevewangv** [tbodt/ish#158]
When pip install some packages, I met this error. 
For example, when installing IPython which will install a lot of required packages, it will put error code -31. But if you install each required packages respectively, it works.
![99deb2c3-8eef-4978-b5c1-271ab6c20003](https://user-images.githubusercontent.com/12782946/49365768-92e17d00-f722-11e8-8f03-fa1e11060f7f.png)

However, IPython doesn’t work after installing, it cannot open SQLite files:
![2de9175b-0d6a-4da1-9118-04653a6e0512](https://user-images.githubusercontent.com/12782946/49365983-1e5b0e00-f723-11e8-949f-0a7b78a4bb27.png)

**Comment by pen9un** [comment]
我遇到了同样的问题，请问解决了没有，或者其他人有好的解决方案

**Comment by pen9un** [comment]
I met the same problem, have you solved it, or someone else has a good solution

**Comment by tbodt** [comment]
The error -31 has been solved by stubbing out all the xattr system calls. IPython I/O errors are a separate issue.
