### ISSUE TITLE
GNU screen

### ISSUE THREAD

**Issue by newbold** [tbodt/ish#159]
Running GNU screen results in the output `Must be conneted to a terminal` so it seems that iSH isn’t aware of a terminal. Any plans to add emulation or whatever would be needed to allow screen to run? (I know I can still use screen to send commands to detached sessions but I like to use it for visual window splitting.)

**Comment by JaquesBoum** [comment]
With the limitations of running multiple instances of the same App on IOS I was hoping this was a bit more of a priority. Are you by chance planning to introduce tabs for multiple shells?
Using “&” to send a program to background works, “jobs” works and “fg” works as well. Freezing with “Ctrl+Z” so you can “bg” a running program unfortunately doesn’t. The input of “Ctrl+Z” seems to not register.

**Comment by tbodt** [comment]
@JaquesBoum Interesting, fg used to be broken and I didn't do anything to fix it. I guess then all that's left for #127 is ctrl-z.

**Comment by tbodt** [comment]
@JaquesBoum background jobs are all fixed in the next build

**Comment by JaquesBoum** [comment]
@tbodt works like a charm! I add it to the “what works” list.

**Comment by tbodt** [comment]
screen works until you try to detach.

**Comment by tbodt** [comment]
Reattaching is working now.
