### ISSUE TITLE
nc unable to bind port

### ISSUE THREAD

**Issue by compilingEntropy** [tbodt/ish#165]
Attempting to set up nc to listen for an incoming connection results in ish crashing to springboard. Reproduce with `nc -l 80` (port number doesn't matter here).

[iSH-2018-12-04-095415.ips.beta](https://github.com/tbodt/ish/files/2647302/iSH-2018-12-04-095415.ips.beta.txt)

**Comment by tbodt** [comment]
Are you on build 33? In the latest build it just says `nc: listen: Function not implemented` instead of crashing.

**Comment by compilingEntropy** [comment]
Ah, you’re correct, I was on build 33. Looks like this was indeed fixed.

**Comment by tbodt** [comment]
`nc -l -p 1234` now works. `nc -l 1234` doesn't, but that's because busybox netcat is really weird.
