### ISSUE TITLE
Terminal new line handling is bad

### ISSUE THREAD

**Issue by ELChris414** [tbodt/ish#168]
Was going to test weechat, it crashed and when it gave the Bad system call output it started the new command place slightly off. Pressing enter a couple of times lead to this: 
![image0 png](https://user-images.githubusercontent.com/8685248/49657574-a48b9300-fa48-11e8-8f20-8f44e9136c9f.jpg)

**Comment by Mnpn03** [comment]
Does `clear` fix it

**Comment by ELChris414** [comment]
No https://media.discordapp.net/attachments/330825662678171648/520626600371552277/image0.png?width=599&height=473

**Comment by Mnpn03** [comment]
What about `reset`

**Comment by ELChris414** [comment]
Fixes it but starts the first line with an awkward `(B`

**Comment by Mnpn03** [comment]
![](https://user-images.githubusercontent.com/17569187/49657536-35aa3c00-fa40-11e8-904f-67de6c604f5d.png)

**Comment by tbodt** [comment]
Nothing I can do about this, it's what would happen on a real system if weechat crashed before resetting the terminal mode.
