### ISSUE TITLE
Error upgrading busybox to 1.26.2-r9

### ISSUE THREAD

**Issue by sirredbeard** [tbodt/ish#17]
`apk upgrade`

attempts to upgrade busybox from 1.26.2-r5 to 1.26.2-r9 and results in the following error 
![a6916100-cf06-431e-967f-6dc732eeb623](https://user-images.githubusercontent.com/33820650/38283378-b44a809a-3783-11e8-977d-404f7d5374ce.jpeg)

it also results in errors when installing other apps:
![69b2d3bd-76da-41bb-be7e-8d6aabf60c04](https://user-images.githubusercontent.com/33820650/38283407-e0df9a0a-3783-11e8-91f7-38976bdc3169.jpeg)

**Comment by sirredbeard** [comment]
It is odd.

**Comment by tbodt** [comment]
Cannot reproduce.
