### ISSUE TITLE
Weechat fails to run

### ISSUE THREAD

**Issue by ELChris414** [tbodt/ish#170]
dmesg outputs `3 missing syscall 14` although I have seen it output other syscall numbers too.

**Comment by tbodt** [comment]
It now starts up, but when you try to connect to IRC it doesn't work very well because sendmsg/recvmsg isn't implemented.

**Comment by tbodt** [comment]
oh god it's trying to send a file descriptor

**Comment by leeramsay** [comment]
Should be good to close this one, I could install weechat, connect to freenode, join #weechat, and disconnect all of that.

**Comment by tbodt** [comment]
Yeah I tested this, it seems to work.
