### ISSUE TITLE
Missing nameservers in /etc/resolv.conf

### ISSUE THREAD

**Issue by grgarside** [tbodt/ish#173]
I don't seem to be able to get internet access with iSH without manually editing /etc/resolv.conf to add nameservers. A fresh install of iSH shows the following, where example is my university.

    # cat /etc/resolv.conf
    search example.ac.uk

This doesn't seem to work when the network is an 802.1X? I don't have access to another network to test, but I suspect this might be the awkward factor about the network I'm using that makes this less reproducible?

https://github.com/tbodt/ish/blob/7e44df935a6a7366be666a37331a024c8abfeaee/app/AppDelegate.m#L67-L75

If I do `echo nameserver 8.8.8.8 >> /etc/resolv.conf` then internet works fine and I can `apk update`.

**Comment by tbodt** [comment]
The code I wrote to query DNS settings is indeed questionable, but to fix it I'd need to have access to a network where it doesn't work. Leaving this open for now.

**Comment by Patronics** [comment]
I encountered the problem a while back where /etc/resolv.conf was empty, and DNS was nonfunctional until I manually added some DNS servers into resolv.conf (in my case I used 1.1.1.1 and 8.8.8.8

**Comment by joubin** [comment]
On it!

**Comment by joubin** [comment]
**Self**
self	AppDelegate *	0x28052aa00	0x000000028052aa00
Res_9_state
```
Printing description of res:
(__res_9_state) res = {
  retrans = 30
  retry = 2
  options = 1729
  nscount = 2
  nsaddr_list = {
    [0] = {
      sin_len = '\0'
      sin_family = '\0'
      sin_port = 0
      sin_addr = (s_addr = 0)
      sin_zero = ""
    }
    [1] = {
      sin_len = '\0'
      sin_family = '\0'
      sin_port = 0
      sin_addr = (s_addr = 0)
      sin_zero = ""
    }
    [2] = {
      sin_len = '\0'
      sin_family = '\0'
      sin_port = 0
      sin_addr = (s_addr = 0)
      sin_zero = ""
    }
  }
  id = 58031
  dnsrch = ([0] = 0x0000000000000000, [1] = 0x0000000000000000, [2] = 0x0000000000000000, [3] = 0x0000000000000000, [4] = 0x0000000000000000, [5] = 0x0000000000000000, [6] = 0x0000000000000000)
  defdname = ""
  pfcode = 0
  ndots = 1
  nsort = 0
  unused = ""
  sort_list = {
    [0] = {
      addr = (s_addr = 0)
      mask = 0
    }
    [1] = {
      addr = (s_addr = 0)
      mask = 0
    }
    [2] = {
      addr = (s_addr = 0)
      mask = 0
    }
    [3] = {
      addr = (s_addr = 0)
      mask = 0
    }
    [4] = {
      addr = (s_addr = 0)
      mask = 0
    }
    [5] = {
      addr = (s_addr = 0)
      mask = 0
    }
    [6] = {
      addr = (s_addr = 0)
      mask = 0
    }
    [7] = {
      addr = (s_addr = 0)
      mask = 0
    }
    [8] = {
      addr = (s_addr = 0)
      mask = 0
    }
    [9] = {
      addr = (s_addr = 0)
      mask = 0
    }
  }
  qhook = 0x0000000000000000
  rhook = 0x0000000000000000
  res_h_errno = 0
  _vcsock = -1
  _flags = 0
  _pad = 9
  _u = {
    pad = ""
    _ext = {
      nscount = 0
      nstimes = ([0] = 0, [1] = 0, [2] = 0)
      nssocks = ([0] = 0, [1] = 0, [2] = 0)
      ext = 0x0000000125e03060
    }
  }
}
```

**Comment by tbodt** [comment]
There are no nameservers being returned. what

**Comment by tbodt** [comment]
If you look in the device settings, does it show you a nonempty list of dns servers?

**Comment by DavidSouthgate** [comment]
@tbodt you cannot update or see DNS Servers for cellular connections in iOS (only WiFi).  Could this be the root cause of the issue?

**Comment by tbodt** [comment]
I’ve heard reports from people on cellular that it works fine.

**Comment by DavidSouthgate** [comment]
Fair enough, I assume iOS does get name servers from somewhere for cellular but it just hides them from the user and doesn't allow you to change them.

**Comment by tbodt** [comment]
Are they in fact hidden from the user? That would sure be annoying...

**Comment by DavidSouthgate** [comment]
So iOS itself doesn't allow you but there is a free app called "Network Analyzer" that allows you to. Having checked my cellular DNS settings using this app I believe that this could be an issue with networks that have any IPv6 DNS server setup but no IPv4 address setup. 
![photo 16-01-2019 15 53 58](https://user-images.githubusercontent.com/6199657/51261023-6bc7cd80-19a7-11e9-9e93-589f11affde0.png)

**Comment by joubin** [comment]
Alright. I found a workaround. 

I have MDM, which provides DNS overrides when on (this is part of my on-demand VPN config)

[reference](https://developer.apple.com/business/documentation/Configuration-Profile-Reference.pdf)

![Image](https://i.imgur.com/KjGsKLA.jpg)

**Comment by tbodt** [comment]
Maybe you have to call res_getservers to include the ipv6 ones? https://stackoverflow.com/a/43344910/1455016

**Comment by joubin** [comment]
Note that MDM was disabled on the Xcode dump session!

**Comment by DavidSouthgate** [comment]
@tbodt yeah that's it! I have rewritten that part to allow IPv6 addresses! Will open a PR now

**Comment by DavidSouthgate** [comment]
Working
<img src="https://user-images.githubusercontent.com/6199657/51264108-974db680-19ad-11e9-99da-d15bd69b5890.png" height=500></img>

**Comment by tbodt** [comment]
Thanks @joubin and @DavidSouthgate for helping to debug!

**Comment by joubin** [comment]
Woot!  Thank you guys. That was quicker than I thought.
