### ISSUE TITLE
/dev/urandom is not implemented / working

### ISSUE THREAD

**Issue by galli-leo** [tbodt/ish#175]
I haven‘t found any issue / project mentioning /dev/urandom, so I thought I would open one :)

Seems like /dev/urandom is not implemented / there. This prevents e.g. numpy from installing and mono from running.

Is this something that is planned? I would love to be able to run mono for quickly testing stuff on my iPad.

**Comment by tbodt** [comment]
This wouldn’t be too hard, I already have code to generate random data.

**Comment by lunixbochs** [comment]
done in https://github.com/tbodt/ish/pull/181
