### ISSUE TITLE
terraform doesn’t work

### ISSUE THREAD

**Issue by samsonjs** [tbodt/ish#176]
Attempting to run [terraform][] results in the error message `This program can only be run on processors with MMX support.`. It’s written in Go so maybe this is something specific to Go? Pure speculation.

[terraform]: https://www.terraform.io/

Happy to try to help if you can point me at something to get started. Not my area of expertise but I like this sort of stuff.

**Comment by tbodt** [comment]
go programs require the MMX instruction set, and MMX is not implemented.

**Comment by tbodt** [comment]
Closing as duplicate of #57
