### ISSUE TITLE
Can’t install python pandas package with pip3

### ISSUE THREAD

**Issue by sausheong** [tbodt/ish#177]
Can’t install python pandas package using pip3. 

![img_0056](https://user-images.githubusercontent.com/5962/49713975-0127c180-fc86-11e8-83e3-59e5390e3610.png)

**Comment by tbodt** [comment]
Duplicate of #126

**Comment by tbodt** [comment]
You can install working numpy binaries using apk.

**Comment by ifuchs** [comment]
Has anyone gotten any further with installing pandas?
