### ISSUE TITLE
ssh-keygen quietly dies if keyboard focus is given while waiting for input

### ISSUE THREAD

**Issue by jckarter** [tbodt/ish#180]
If you:

1. Launch ssh-keygen without an output filename and a large bit size, `ssh-keygen -b 2048` for instance
2. Switch to a split-screen app while you wait, dismissing the keyboard
3. Bring focus back to iSH when ssh-keygen asks for an output filename

then ssh-keygen will immediately quit back to the shell prompt, without any error message, before you get a chance to give any input.

**Comment by saagarjha** [comment]
@tbodt It might be dying on a `SIGWINCH`?

**Comment by tbodt** [comment]
It does seem sigwinch related, rotating your phone also triggers it.

**Comment by tbodt** [comment]
The sigwinch is causing the read to return EINTR, even though there's no handler established.

**Comment by tbodt** [comment]
723ebc44fc19f7b62193131c12836527f197ca17
