### ISSUE TITLE
Feature-Request: allow non-user accounts

### ISSUE THREAD

**Issue by abbanatic** [tbodt/ish#184]
Hi,

please be so kind to implement the creation of non-root accounts.

Sometimes, there're some packages that won't allow to be built (and executed) as root.

After installing the alpine shadow package, I'm able to create additional accounts, but I'm not allowed to login into those accounts. Furthermore, after the creation of non-root accounts, ish cannot be started anymore, always saying "attempted to kill init".

The only way to get out of this loop is to completely delete the app from the device and start all over again.

It would be great, if you could take a look at this.

Thanks and kind regards,
Thomas

**Comment by tbodt** [comment]
As it happens I already fixed the problems with installing shadow, and it should be working in the next build.
