### ISSUE TITLE
Vim commands don’t work

### ISSUE THREAD

**Issue by jroberts0** [tbodt/ish#187]
Vim commands seem to be all over the place, sometimes they work, other times they don’t. 

How to reproduce (sometimes):

- `apk add vim`
- `vim Test`

On Ubuntu 18.04 Vim command mode:

```
:w      Written 5 lines
jack@jbuntu:~# 
```

On iSH Vim command mode:

```
:w 
```
As shown above, nothing happens but when you write to a new file instead of the original one, Vim executes the command. 

```
:w /Test2
Jacks-iPad:~# 
```
Sometimes running `apk fix vim` makes things work again but most of the time writing to files doesn’t work.

**Comment by tbodt** [comment]
:wq works consistently for me.

**Comment by jroberts0** [comment]
I forgot to put

**Comment by jroberts0** [comment]
I meant to put that :w doesn’t work consistently for me.

**Comment by f0cus10** [comment]
Can confirm that `:w` and `:wq` consistently work for me. 

I’m on iPhone Xs: 12.1.1

**Comment by kkk669** [comment]
@jroberts0 Do you have  a `.vimrc` on your home directory?

**Comment by jroberts0** [comment]
No I don’t

**Comment by ViralTaco** [comment]
:wq never works for me… If only I could at least ssh into it. I also tried :w then :q I'm not sure why this doesn't seem to work half of the time. I'll try to look into it… Again. Man that screen is small tho :/

**Comment by bao3** [comment]
I could comfirm `:w` and `:wq` work for me , iOS 12.1.1

**Comment by f0cus10** [comment]
@ViralTaco this maybe a stupid suggestion, but did you make sure to exit out of *INSERT* mode when doing the operation?

**Comment by tbodt** [comment]
Closing since there's still no repro
