### ISSUE TITLE
curl needs poll

### ISSUE THREAD

**Issue by Mnpn03** [tbodt/ish#19]
As the title says, curl (and possibly other programs) crash iSH when running, with the following notice:

```
Apr 20 19:03:32 iPhone iSH[3896] <Notice>: TODO: actual working poll
```
In `/kernel/poll.c`:
```
    if (nfds != 1)
        TODO("actual working poll");
```

--
I have already sent you a crash dump and log.

**Comment by tbodt** [comment]
Curl works now.
