### ISSUE TITLE
Feature request: pbcopy/pbpaste style clipboard integration

### ISSUE THREAD

**Issue by fernandotcl** [tbodt/ish#192]
On the Mac, you can use the `pbcopy`/`pbpaste` commands to copy from and paste to the clipboard. It would be awesome if you could do something similar in iSH.

The way I see this working is through virtual devices, but maybe there's a more clever way to do it. On iOS, `UIPasteboard` stores clipboard entries as pairs of UTI (Universal Type Identifier) and content. So the ideal API is probably more complicated than simply reading and writing to a single virtual device.

Right now iSH supports copy and paste on the terminal, but that isn't as powerful as you're limited to text. The only way to get data in and out of iSH is currently the file system, which is less convenient in some cases.

I think the feature in itself is pretty cool, but it would also be very powerful to use together with Siri Shortcuts (#59).

**Comment by kkk669** [comment]
iSH runs Linux, so `xsel` and `xclip` are good alternatives. But, they normally requires a X window server which currently doesn’t supported by iSH.

**Comment by tbodt** [comment]
A /dev/clipboard device would be pretty easy to add.

**Comment by JayBrown** [comment]
How would you go about reading from the clipboard?

I can write to it easily with `echo foo > /dev/clipboard`

But `echo $(</dev/clipboard)` doesn't seem to cut it… iOS tells me that text was pasted from the originating app, e.g. Apple Notes, but the `ash` in **iSH** doesn't print anything.

**Comment by tbodt** [comment]
cat /dev/clipboard

**Comment by digitalguy99** [comment]
> How would you go about reading from the clipboard?
> 
> I can write to it easily with `echo foo > /dev/clipboard`
> 
> But `echo $(</dev/clipboard)` doesn't seem to cut it… iOS tells me that text was pasted from the originating app, e.g. Apple Notes, but the `ash` in **iSH** doesn't print anything.

For a `pbcopy` equivalent:

1. Simply install zsh, set it as your default shell,:
```shell
apk add zsh; sed -i 's|ash|zsh|g' /etc/passwd; exit
```

2. Add this to your `~/.zshrc`:
```zsh
function clipcopy() {
    if [ -t 0 ]; then
        # If input is from a terminal, read from the file provided as an argument
        cat "$1" > /dev/clipboard
    else
        # If input is from a pipe, read from stdin
        cat > /dev/clipboard
    fi
}
```

3. Then you can just do something like
```zsh
cat content_to_copy.txt | clipcopy
```
and whatever content you want to copy would be in your clipboard

**Comment by verhovsky** [comment]
```sh
alias pbcopy="cat > /dev/clipboard"
alias pbpaste="cat /dev/clipboard"
```
