### ISSUE TITLE
apk search only gives warnings

### ISSUE THREAD

**Issue by sojournerverite** [tbodt/ish#194]
Just installed app on iOS. When I type `apk search` I get the following:

`WARNING: Ignoring APKINDEX.adfa7ceb.tar.gz: No such file or directory`
`WARNING: Ignoring APKINDEX.efaa1f73.tar.gz: No such file or directory`

`ls` only shows two root directories and apk_history.

`setup-alpine` is not found.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Mnpn03** [comment]
setup-alpine was just in the old default MOTD and has been fixed if you reinstall or change it yourself. Have you tried running `apk update`?

**Comment by sojournerverite** [comment]
>setup-alpine was just in the old default MOTD and has been fixed if you reinstall or change it yourself. Have you tried running `apk update`?

@Mnpn03 setup-alpine wasn't in the MOTD, it's in the README page of this GitHub project.

Thank you! `apk-update` worked.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Mnpn03** [comment]
Ah yes, those screenshots still need to be updated. I’ll make a PR to use the ones on the website. Thanks!
