### ISSUE TITLE
How to install apt ?

### ISSUE THREAD

**Issue by Antoxa223** [tbodt/ish#199]
~# apk add apt                            
ERROR: unsatisfiable constraints:                
  apt (missing):                                 
    required by: world[apt]

**Comment by itskenny0** [comment]
apt is the package manager for Debian-based systems. iSH uses an Alpine userland which doesn't use apt.

**Comment by jroberts0** [comment]
Alpine Linux uses Apk for installing packages instead of Apt. 
You can install packages by using Apk add

**Comment by tbodt** [comment]
Installing apt on alpine is not recommended.

**Comment by 58albay58** [comment]
Yes
