### ISSUE TITLE
traceroute does not work

### ISSUE THREAD

**Issue by muellermartin** [tbodt/ish#200]
Hi, I've just installed iSH and tried to run `traceroute`. Unfortunately the program failed to run with following error:

    traceroute: setsockopt(SO_SNDBUF): Invalid argument

iSH Version: 1.0 (37)
iOS: 12.1.1
Device: iPhone SE

**Comment by jusdepatate** [comment]
Try to look at issues about ping/network, iSH has a problems with this ;)

**Comment by tbodt** [comment]
@wallisch said he was working on this.
