### ISSUE TITLE
sshd segfaults 

### ISSUE THREAD

**Issue by orikad** [tbodt/ish#202]
```
apk add openssh-server
ssh-keygen -A
$(which sshd) -p2222
```
Segfaults iSH. Crash log: [iSH-2018-12-17-235047.ips.beta.zip](https://github.com/tbodt/ish/files/2687982/iSH-2018-12-17-235047.ips.beta.zip)

**Comment by tbodt** [comment]
Fixed in c42abb1

**Comment by ecx86** [comment]
It still segfaults for me unless I use `-d` :(
The app entirely crashes immediately unless `-D` is given, and crashes on connect unless `-d` is given.
No crash log right now.

**Comment by tbodt** [comment]
@ecx86 could you please open a new issue for that?
