### ISSUE TITLE
CMake is stuck after exec_program

### ISSUE THREAD

**Issue by kkk669** [tbodt/ish#205]
I have no idea to resolve it, but CMake is stuck after `exec_program ()`. It will be called by `project ()` at every running, and it wil be inserted into the first line if `CMakeLists.txt` doesn't have `project ()`, so this means that CMake does not work on iSH.

Minimum `CMakeLists.txt` example:

```cmake
cmake_minimum_required (VERSION 3.11)
exec_program (ls)
project (example)
```

Output (cmake never returned to prompt):

```bash
# cmake . --debug-output --trace-expand
Running with debug output on.
Running with expanded trace output on.
/root/test/CMakeLists.txt(1):  cmake_minimum_required(VERSION 3.11 )
   Called from: [1]     /root/test/CMakeLists.txt
/root/test/CMakeLists.txt(2):  exec_program(ls )
   Called from: [1]     /root/test/CMakeLists.txt
running ls 2>&1
CMakeFiles
CMakeLists.txt
```

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tbodt** [comment]
This is because nothing is sending SIGCHLD.

**Comment by tbodt** [comment]
This issue is fixed; now cmake runs through the configuration process, outputs the build files, and then dies from missing epoll #142
