### ISSUE TITLE
gnupg has bad system call

### ISSUE THREAD

**Issue by epstabler** [tbodt/ish#207]
Even just gpg --version

![img_1783](https://user-images.githubusercontent.com/2224049/50245979-01b90a00-03a2-11e9-9ae9-d3b4828bdc2c.jpeg)

![img_1812](https://user-images.githubusercontent.com/2224049/50245990-08478180-03a2-11e9-9215-000469f92df4.jpeg)

**Comment by tbodt** [comment]
The missing syscall is fixed now, but there are other problems, they seem to be related to lack of working unix domain sockets.
