### ISSUE TITLE
network not use

### ISSUE THREAD

**Issue by DHCMediWay** [tbodt/ish#209]
liuende:~# cat /etc/resolv.conf                       
nameserver 192.168.1.1                                
liuende:~# ping 192.168.1.1                           
PING 192.168.1.1 (192.168.1.1): 56 data bytes         
ping: sendto: Host is unreachable                     
liuende:~# apk add openssh                            
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x
86/APKINDEX.tar.gz                                    
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.8/main:
 temporary error (try again later)                    
WARNING: Ignoring APKINDEX.adfa7ceb.tar.gz: No such fi
le or directory                                       
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/commun
ity/x86/APKINDEX.tar.gz                               
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.8/commu
nity: temporary error (try again later)               
WARNING: Ignoring APKINDEX.efaa1f73.tar.gz: No such fi
le or directory                                       
ERROR: unsatisfiable constraints:                     
  openssh (missing):                                  
    required by: world[openssh]

**Comment by huhuhang** [comment]
same issues.

**Comment by tbodt** [comment]
This seems to be an issue with devices sold in China.

**Comment by huhuhang** [comment]
> This seems to be an issue with devices sold in China.

😂 I probably know it. iPhone sold in China have additional options, it can control network permissions.App needs to request authorization when they open for the first time.

Example:

![img_0855](https://user-images.githubusercontent.com/5147530/50533057-6a9c4100-0b5d-11e9-9e3c-747a2c3fe613.jpg)
![img_0856](https://user-images.githubusercontent.com/5147530/50533058-6b34d780-0b5d-11e9-809e-58b00fa5125a.jpg)

**Comment by tbodt** [comment]
How do I get the authorization popup to appear?

**Comment by huhuhang** [comment]
> How do I get the authorization popup to appear?

Sorry, I have no suggestion, I am not an iOS developer. 😂

**Comment by tbodt** [comment]
do I really have to find a chinese iphone on ebay to debug this

**Comment by huhuhang** [comment]
> do I really have to find a chinese iphone on ebay to debug this

Wait a moment, I am going to find a Chinese iOS developer to help you.

**Comment by uuunit** [comment]
https://github.com/Zuikyo/ZIKCellularAuthorization

**Comment by tbodt** [comment]
@huhuhang @uuunit thanks! Only thing is, I'd like to do something that's App Store safe if possible.

**Comment by tbodt** [comment]
Probably the issue is that I’m using sockets directly instead of using any iOS API.

**Comment by cyantreeguo** [comment]
1.vi /etc/profile. Add "apk update" to file. :wq
2.close ish
3.reset iphone
4.open ish, and authorization popup!
5.vi /etc/profile. Delete "apk update"
6.It's done!

**Comment by tbodt** [comment]
why does that work...

**Comment by cyantreeguo** [comment]
The authorization dialog will popup when app try to connect network with it startup.

**Comment by gaoyifan** [comment]
I think the solution is to call CellularDataRestrictionDidUpdateNotifier to trigger a network permission alert.

Here is some info about the problem, hope it helps.
https://stackoverflow.com/questions/40755428/ios-10-wlan-access-setting-doesnt-appear-in-some-ios-devices
https://stackoverflow.com/questions/41236056/detect-ios-network-permission-of-my-app
https://stackoverflow.com/questions/50837093/ios-network-access-permissions-in-china

**Comment by tbodt** [comment]
@gaoyifan cellularDataRestrictionDidUpdateNotifier seems like it would tell me when the user taps accept in the popup, but not open the popup.

**Comment by gaoyifan** [comment]
Great job! It's confirmed that the problem was solved in build 42.

**Comment by tbodt** [comment]
Sweet! I’ll close this now.

**Comment by CodeMeditator** [comment]
@huhuhang thx, it works!
