### ISSUE TITLE
macOS version (syscall translation only)

### ISSUE THREAD

**Issue by angerman** [tbodt/ish#210]
Any chance one could extract a pure macOS version from this? Say without the x86_64 -> aarch64 emulation. Just the syscall translation. The idea would be to end up with something like WINE but for linux.

I'm interested in something that would be maybe sufficiently good enough to run simple console applications compiled for linux (let's assume fully static, linked against musl) on macOS.

**Comment by tbodt** [comment]
https://github.com/linux-noah/noah/

**Comment by angerman** [comment]
@tbodt thanks. Do you have any comparison between both?

**Comment by tbodt** [comment]
noah seems to be somewhat more mature, though it's powered by hypervisor.framework instead of any sort of emulator, so it can't run anywhere beyond macos.

**Comment by angerman** [comment]
Thanks, I'll do some experiments. Any reason for ish to in principle not be a universal solution?

**Comment by tbodt** [comment]
No real reason, other than nobody cares enough to make it happen.
