### ISSUE TITLE
Xcode compilation issue  

### ISSUE THREAD

**Issue by francoisvignon** [tbodt/ish#211]
Dummy request, maybe.

after settings all to compile for simulator, I have following error at startup, a little help will be welcome.

Many thanks in advance.

2018-12-22 11:09:59.801025+0100 iSH[23145:7707260] Failed to set (highlightedBackgroundColor) user defined inspected property on (ArrowBarButton): [<ArrowBarButton 0x7fa46ae0e480> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key highlightedBackgroundColor.
2018-12-22 11:09:59.809049+0100 iSH[23145:7707260] idletimerdisabled 0
2018-12-22 11:09:59.845956+0100 iSH[23145:7707260] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSFileManager createDirectoryAtURL:withIntermediateDirectories:attributes:error:]: URL is nil'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010f2f51bb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000010e89b735 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010f2f5015 +[NSException raise:format:] + 197
	3   Foundation                          0x000000010e2ac222 -[NSFileManager createDirectoryAtURL:withIntermediateDirectories:attributes:error:] + 109
	4   iSH                                 0x000000010db37739 -[AppDelegate startThings] + 329
	5   iSH                                 0x000000010db37f5e -[AppDelegate application:didFinishLaunchingWithOptions:] + 174
	6   UIKitCore                           0x00000001184f7bde -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 280
	7   UIKitCore                           0x00000001184f95cb -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 3979
	8   UIKitCore                           0x00000001184fec2f -[UIApplication _runWithMainScene:transitionContext:completion:] + 1623
	9   UIKitCore                           0x0000000117d1d4e9 __111-[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:]_block_invoke + 866
	10  UIKitCore                           0x0000000117d2629c +[_UICanvas _enqueuePostSettingUpdateTransactionBlock:] + 153
	11  UIKitCore                           0x0000000117d1d126 -[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:] + 233
	12  UIKitCore                           0x0000000117d1dae0 -[__UICanvasLifecycleMonitor_Compatability activateEventsOnly:withContext:completion:] + 1085
	13  UIKitCore                           0x0000000117d1bcb5 __82-[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:]_block_invoke + 795
	14  UIKitCore                           0x0000000117d1b95f -[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:] + 435
	15  UIKitCore                           0x0000000117d20a90 __125-[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:]_block_invoke + 584
	16  UIKitCore                           0x0000000117d2180e _performActionsWithDelayForTransitionContext + 100
	17  UIKitCore                           0x0000000117d207ef -[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:] + 221
	18  UIKitCore                           0x0000000117d2593a -[_UICanvas scene:didUpdateWithDiff:transitionContext:completion:] + 392
	19  UIKitCore                           0x00000001184fd44e -[UIApplication workspace:didCreateScene:withTransitionContext:completion:] + 515
	20  UIKitCore                           0x00000001180a1d09 -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:] + 357
	21  FrontBoardServices                  0x000000011b27d2da -[FBSSceneImpl _didCreateWithTransitionContext:completion:] + 448
	22  FrontBoardServices                  0x000000011b288443 __56-[FBSWorkspace client:handleCreateScene:withCompletion:]_block_invoke_2 + 271
	23  FrontBoardServices                  0x000000011b287b3a __40-[FBSWorkspace _performDelegateCallOut:]_block_invoke + 53
	24  libdispatch.dylib                   0x0000000110e48602 _dispatch_client_callout + 8
	25  libdispatch.dylib                   0x0000000110e4bb78 _dispatch_block_invoke_direct + 301
	26  FrontBoardServices                  0x000000011b2bcba8 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 30
	27  FrontBoardServices                  0x000000011b2bc860 -[FBSSerialQueue _performNext] + 457
	28  FrontBoardServices                  0x000000011b2bce40 -[FBSSerialQueue _performNextFromRunLoopSource] + 45
	29  CoreFoundation                      0x000000010f25a721 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	30  CoreFoundation                      0x000000010f259f93 __CFRunLoopDoSources0 + 243
	31  CoreFoundation                      0x000000010f25463f __CFRunLoopRun + 1263
	32  CoreFoundation                      0x000000010f253e11 CFRunLoopRunSpecific + 625
	33  GraphicsServices                    0x00000001149f61dd GSEventRunModal + 62
	34  UIKitCore                           0x000000011850081d UIApplicationMain + 140
	35  iSH                                 0x000000010db33720 main + 112
	36  libdyld.dylib                       0x0000000110ebe575 start + 1
	37  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by francoisvignon** [comment]
find the issue: wrong group identifier in manager containerURLForSecurityApplicationGroupIdentifier

sorry for the disturb.

**Comment by wenmin-wu** [comment]
@francoisvignon I came across the same problem. How did you solve this?

**Comment by tbodt** [comment]
It's the app group id, there are a number of places in the app where it has to be set correctly. For best results, update the project file as described in https://github.com/tbodt/ish#build-for-ios, and don't change anything else about the project.

**Comment by wenmin-wu** [comment]
@tbodt Fixed by only changing the   `ROOT_BUNDLE_IDENTIFIER ` and team information. BTW, some apps can store data under `On My iPad` directory. Is there any way to create a directory for `iSH` and store its data under there?

**Comment by tbodt** [comment]
No, there's a lot of info stored in a sqlite database that wouldn't work well with that setup.
