### ISSUE TITLE
sshd crashes upon forking

### ISSUE THREAD

**Issue by ecx86** [tbodt/ish#212]
The app hard-crashes entirely to the home screen whenever `sshd` is run, unless `-d` or `-D` is given.
Workaround for now is to use `sshd -d &` and create many servers on different ports to support multiple ssh connections. Currently, pty allocation is broken, but `sshd` is massively useful for port-forwarding and tunneling.
The app entirely crashes immediately unless `-D` is given, and crashes on connect unless `-d` is given.
No crash log right now, apologies. Should be very easy to reproduce, however.

**Comment by tbodt** [comment]
I can’t reproduce any of this on the master branch. The fix for #202 is not pushed to testflight.
