### ISSUE TITLE
key remap with xmodmap/setxkbmap

### ISSUE THREAD

**Issue by matthoop** [tbodt/ish#214]
hi, I see that "CapsLock" can be remapped "Control" in the `Settings` section inside iSSH, but I think since it's an `alphine` linux, so maybe `xmodmap` or `setxkbmap` should work too. 
```
iPad-2:~# xmodmap                                                                                                                           
xmodmap:  unable to open display ''  
```

```
iPad-2:~# setxkbmap -option "ctrl:swapcaps"                                                                                                 
Cannot open display "default display"  
```

is there any methods to use that two commands to swap keys ?

Thank you!

**Comment by tbodt** [comment]
iSH isn't using X, so no.
