### ISSUE TITLE
ssh-agent needs UNIX domain sockets

### ISSUE THREAD

**Issue by zmwangx** [tbodt/ish#219]
```
# ssh-agent                                                                                                                                                   
unix_listener: cannot bind to path /tmp/ssh-66GGxWn5a3Ib/agent.4: No such file or directory
```

This is the root account, so there shouldn’t be permission problems.

Binding to somewhere in the home directory doesn’t help either:

```
# ssh-agent -a ~/.agent.$$                                                                                                                                    
unix_listener: cannot bind to path /root/.agent.3: No such file or directory
```

**Comment by tbodt** [comment]
Unix domain sockets are not implemented.

**Comment by zmwangx** [comment]
Oh, that explains it. Any plan to support Unix domain sockets? Of the top of my head, gpg-agent, emacsclient, etc. could benefit too.

**Comment by tbodt** [comment]
The main difficulty is doing it in a filesystem-agnostic way. The challenge there is similar to the challenge in fcntl() locks (https://github.com/tbodt/ish/issues/217#issuecomment-450234983).

**Comment by zmwangx** [comment]
Makes sense. Unfortunately I have zero iOS development experience...

**Comment by ankushnarula** [comment]
@tbodt Wouldn’t you want to use Dropbear rather than OpenSSL/ssh since it’s specifically for BusyBox? 

https://matt.ucc.asn.au/dropbear/dropbear.html

**Comment by zmwangx** [comment]
OpenSSH client already works fine (AFAICT). This issue is about ssh-agent, and the underlying issue is lack of support for Unix domain sockets. It seems Dropbear doesn't even have an agent.

**Comment by tbodt** [comment]
Unix domain sockets should be working now.
