### ISSUE TITLE
Gem install event-machine results in SEGV received in ILL handler

### ISSUE THREAD

**Issue by sausheong** [tbodt/ish#223]
Screenshots

![img_0069](https://user-images.githubusercontent.com/5962/50501540-e03bda80-0a93-11e9-9c55-18f5ab4b7049.png)
![img_0070](https://user-images.githubusercontent.com/5962/50501547-e92cac00-0a93-11e9-893d-3274915fb466.png)
![img_0071](https://user-images.githubusercontent.com/5962/50501555-f3e74100-0a93-11e9-85e0-78b15d4b1134.png)

**Comment by tbodt** [comment]
Fixed in build 40.
