### ISSUE TITLE
Can't move files into or out of iSH in Files app

### ISSUE THREAD

**Issue by jckarter** [tbodt/ish#229]
If you try to move files from iCloud Drive or another file provider into the iSH filesystem from the Files app, then you aren't allowed to select folders in the iSH filesystem as a destination. Conversely, you can't move iSH files out of the iSH filesystem either.

**Comment by tbodt** [comment]
Closing in favor of #231

**Comment by Sn0wfreezeDev** [comment]
Hi, 
Thank you for doing this project. I am not sure if it is maybe not included in the current Testfloight version. 
Some apps are able to mount folders of other file providers, so they can be accessed. 
For example "Textastic" does this to import git projects from "Working Copy". 
Currently when I select to open a folder in "Textastic" the app does not get the folder to mount. 
According to their documentation they cannot mount folders which are marked as cloud storage. So this could be an issue. 

Thank you, 
Alexander Heinrich

**Comment by tbodt** [comment]
There's no way that I can think of to expose the files from iSH as anything other than cloud storage. I could make it possible to mount a folder from another file provider into iSH though.

**Comment by Sn0wfreezeDev** [comment]
Good call. 
I will check how they do it and try to post a fix here
