### ISSUE TITLE
File provider sucks

### ISSUE THREAD

**Issue by tbodt** [tbodt/ish#231]
Merging a bunch of issues into one here: #120 #139 #228 #229

**Comment by macBender** [comment]
Can you add automatic refreshing of iSH’s directories inside the Files app?

Scenario:  Files app and iSH side by side in split screen.  Files app set to home directory in iSH.  Create new file in iSH in home, file should appear in Files app automatically. 

Workaround.  In Files app navigate to another provider such as iCloud Drive and then nagivate back to iSH to refresh the directory list.

**Comment by tbodt** [comment]
That is indeed possible.

**Comment by tbodt** [comment]
I just rewrote the file provider, now it sucks a lot less.
