### ISSUE TITLE
Terminal view gets offset, first letter offscreen

### ISSUE THREAD

**Issue by Patronics** [tbodt/ish#234]
Occasionally when using iSH on my iPhone X, the terminal view gets graphically offset, so most of the leftmost letter in each column is mostly off the screen (the edge of some letters are still visible). When this glitch happens, it is not resolved until force quitting and reopening the app.

**Comment by LittleHouse75** [comment]
![img_0663](https://user-images.githubusercontent.com/3247583/50576749-86664800-0de6-11e9-8d9d-bc0d03203407.png)
Maybe a related issue.  In Emacs, typing “This is the scratch buffer.  This is the text that will appear on the screen” yielded the results seen in the screenshot.  So offset cursor here too.

**Comment by tbodt** [comment]
Should be fixed now that I disabled every imaginable way the terminal could scroll.
