### ISSUE TITLE
selecting text on screen will copy displayed 'space' as unicode 0x00A0

### ISSUE THREAD

**Issue by francoisvignon** [tbodt/ish#235]
when selecting text containing space on iSH window (in example, the command "echo a") and then copying, the space between o and a is encoded as unicode 00A0 and this value is stored into clipboard.
So, when pasting the copied text, result is pasting "echo a", but the space between o and a is not a space (ascii 32) but a space (ascii/unicode 0x00A0)

as in this sample:
```
iFv:~# echo a                                 
a                      
iFv:~# ( now, select above 'echo a', then copy and then past) 
iFv:~# echo a                                  
-ash: echo a: not found           ( because it's not a space - ascii 32 - between o and a )             
iFv:~# 
```

the solution can be the following:
```
- (void)copy:(id)sender {
    [self.terminal.webView evaluateJavaScript:@"window.getSelection().toString()" completionHandler:^(NSString *selection, NSError *err) {
        if (err != nil) {
            NSLog(@"error copying: %@", err);
            return;
        }
        UIPasteboard.generalPasteboard.string = [selection stringByReplacingOccurrencesOfString:@"\u00A0" withString:@" "];
    }];
}
```
when copying into clipboard, replace all occurence of unicode strings "\u00A0" by " " (I think my solution is not the good one, but at least, it work)

**Comment by tbodt** [comment]
I've added code to replace nonbreaking spaces with regular spaces.

**Comment by francoisvignon** [comment]
thx, I wish you a great last day of the year.

send from my mobile.
____________________

François
