### ISSUE TITLE
Fusee-launcher fails with segmentation fault

### ISSUE THREAD

**Issue by nidstigator** [tbodt/ish#236]
Fusee launcher: 
https://github.com/Cease-and-DeSwitch/fusee-launcher

Basically used to upload arbitrary code to a Nintendo Switch through USB (to run Homebrew)

Installed libusb and Python3 (and pyusb through pip3) to see if I could run Fusee-Launcher through ish. 

dmesg output:
3 page fault on 0x14c at 0xf7699923

**Comment by itskenny0** [comment]
I have no idea about the Nintendo Switch, but I doubt delivering payloads via USB could ever work with iSH. The faux Linux kernel doesn't have hardware access to that degree, and I'm not sure an iOS device could even enumerate an attached Switch.

**Comment by tbodt** [comment]
Yeah iSH probably isn't ever going to be able to flash a switch. It shouldn't segfault though.

**Comment by nidstigator** [comment]
@itskenny0 @tbodt can iSH have access hardware access (or is it on the cards at all)?

On the mac (or linux) you don’t need any drivers or special kexts to talk to the switch in revovery mode. 

I guess this bug was filed under my (maybe wrong) assumption that the answer to my question above is yes.

**Comment by tbodt** [comment]
iOS apps can't talk to generic USB devices. It's not impossible that some sort of dongle could be made as an adapter though.

**Comment by nidstigator** [comment]
Gotcha. Love the app! It’s getting so much better every testflight build.
Feel free to close the issue, unless you want to investigate this segfault. 

In case this wasn’t clear, fusee-launcher runs through python3.

**Comment by tbodt** [comment]
I would have expected something nicer than a segfault, so I will be investigating a bit.

**Comment by nidstigator** [comment]
@kiding Thanks, that requires Jailbreaking though, which isn’t possible on 3rd Gen iPad Pros

**Comment by kiding** [comment]
Ah, sorry about that. Though I have a feeling that manually codesigning NXBoot binary (so it can be run on a non-jailbroken iOS) would be much easier than expecting iSH to fully support Linux USB on top of iOS, not to mention this kind of hackery purpose: abnormally long control frames in this case.

**Comment by thisisnadeem** [comment]
That’s actually a very good poin. I’ll look into it!

**Comment by nidstigator** [comment]
That’s actually a very good point. I’ll look into it!

**Comment by tbodt** [comment]
*task closed out of spite*

**Comment by 62f** [comment]
dfu-util -d 20b7:1540 -D atusb.dfu
dfu-util 0.7

Copyright 2005-2008 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2012 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to dfu-util@lists.gnumonks.org

Filter on vendor = 0x20b7 product = 0x1540
unable to initialize libusb: -99
