### ISSUE TITLE
Fontconfig Script exits with error 6 (ocrmypdf install) or 5 (font-noto install)

### ISSUE THREAD

**Issue by JaquesBoum** [tbodt/ish#237]
On installation of ocrmypdf package I get the following error:

`Executing fontconfig-2.12.6-r1.trigger
/usr/share/fonts: failed to write cache
/usr/share/fonts/Type1: failed to write cache
/usr/share/fonts/encodings: failed to write cache
/usr/share/fonts/encodings/large: failed to write cache
/usr/share/fonts/ttf-dejavu: failed to write cache
ERROR: fontconfig-2.12.6-r1.trigger: script exited with error 5 `

On installation of font-noto I get the following error:
`(1/1) Installing font-noto (0_git20170920-r0)
Executing fontconfig-2.12.6-r1.trigger
/usr/share/fonts: failed to write cache
/usr/share/fonts/Type1: failed to write cache
/usr/share/fonts/encodings: failed to write cache
/usr/share/fonts/encodings/large: failed to write cache
/usr/share/fonts/noto: failed to write cache
/usr/share/fonts/ttf-dejavu: failed to write cache
ERROR: fontconfig-2.12.6-r1.trigger: script exited with error 6
Executing mkfontscale-1.1.3-r0.trigger
Executing mkfontdir-1.0.7-r1.trigger
1 error; 791 MiB in 220 packages`

Errors are reproducable.

I tried the ocrmypdf install on a whim and now I can see the option to have a mobile pdf-ocr toolchain on my ipad on the horizon. This would be so awesome!

Unfortunately I can’t even seem to find out what the exact error is. Any help on where to start looking into this?

**Comment by JaquesBoum** [comment]
Did more testing:
`XXXX:/usr/share/fonts# apk add font-noto
(1/1) Installing font-noto (0_git20170920-r0)
Executing fontconfig-2.12.6-r1.trigger
/usr/share/fonts: failed to write cache
/usr/share/fonts/noto: failed to write cache
ERROR: fontconfig-2.12.6-r1.trigger: script exited with error 2
OK: 56 MiB in 41 packages
XXXX:/usr/share/fonts# ls /usr/share/fonts
noto
XXXX:/usr/share/fonts# ls /usr/share/fonts/noto/
NotoMono-Regular.ttf               NotoSansDisplay-Italic.ttf         NotoSansSymbols-Medium.ttf         NotoSerif-Thin.ttf
NotoSans-Black.ttf                 NotoSansDisplay-Light.ttf          NotoSansSymbols-Regular.ttf        NotoSerif-ThinItalic.ttf
NotoSans-BlackItalic.ttf           NotoSansDisplay-LightItalic.ttf    NotoSansSymbols-Thin.ttf           NotoSerifDisplay-Black.ttf
NotoSans-Bold.ttf                  NotoSansDisplay-Medium.ttf         NotoSansUI-Bold.ttf                NotoSerifDisplay-BlackItalic.ttf
NotoSans-BoldItalic.ttf            NotoSansDisplay-MediumItalic.ttf   NotoSansUI-BoldItalic.ttf          NotoSerifDisplay-Bold.ttf
NotoSans-Italic.ttf                NotoSansDisplay-Regular.ttf        NotoSansUI-Italic.ttf              NotoSerifDisplay-BoldItalic.ttf
NotoSans-Light.ttf                 NotoSansDisplay-Thin.ttf           NotoSansUI-Regular.ttf             NotoSerifDisplay-Italic.ttf
NotoSans-LightItalic.ttf           NotoSansDisplay-ThinItalic.ttf     NotoSerif-Black.ttf                NotoSerifDisplay-Light.ttf
NotoSans-Medium.ttf                NotoSansMono-Black.ttf             NotoSerif-BlackItalic.ttf          NotoSerifDisplay-LightItalic.ttf
NotoSans-MediumItalic.ttf          NotoSansMono-Bold.ttf              NotoSerif-Bold.ttf                 NotoSerifDisplay-Medium.ttf
NotoSans-Regular.ttf               NotoSansMono-Light.ttf             NotoSerif-BoldItalic.ttf           NotoSerifDisplay-MediumItalic.ttf
NotoSans-Thin.ttf                  NotoSansMono-Medium.ttf            NotoSerif-Italic.ttf               NotoSerifDisplay-Regular.ttf
NotoSans-ThinItalic.ttf            NotoSansMono-Regular.ttf           NotoSerif-Light.ttf                NotoSerifDisplay-Thin.ttf
NotoSansDisplay-Black.ttf          NotoSansMono-Thin.ttf              NotoSerif-LightItalic.ttf          NotoSerifDisplay-ThinItalic.ttf   
NotoSansDisplay-BlackItalic.ttf    NotoSansSymbols-Black.ttf          NotoSerif-Medium.ttf                                                                        
NotoSansDisplay-Bold.ttf           NotoSansSymbols-Bold.ttf           NotoSerif-MediumItalic.ttf                                                                  
NotoSansDisplay-BoldItalic.ttf     NotoSansSymbols-Light.ttf          NotoSerif-Regular.ttf                                                                       
XXXX:/usr/share/fonts#`

**Comment by tbodt** [comment]
If you turn on syscall logging (follow the steps to build from source, but change ISH_LOG to strace in project build settings) you might be able to find more information in the resulting log.

**Comment by JaquesBoum** [comment]
My MBP 2012 unfortunately has left me with only the iPad as computing device - so I will not be able to build stuff in the near future.
But I will remain a comitted tester for this greatest of apps on the iPad :)

@tbodt if there is need to test anything give me a heads up!

**Comment by tbodt** [comment]
@JaquesBoum Can you verify this is still an issue?

**Comment by JaquesBoum** [comment]
Yes of course!

On a clean install of iSSH I issued:
`apk add ocrmypdf`

With the result 

...  
 (99/102) Installing py3-cffi (1.11.5-r0)  
(100/102) Installing py-defusedxml (0.5.0-r0)
(101/102) Installing py3-defusedxml (0.5.0-r0)
(102/102) Installing ocrmypdf (8.0.0-r0)
Executing busybox-1.29.3-r10.trigger
Executing fontconfig-2.13.1-r0.trigger
Assertion failed: fcCacheChains[i] == NULL (fccache.c: FcCacheFini: 795)
Aborted
ERROR: fontconfig-2.13.1-r0.trigger: script exited with error 134
Executing mkfontscale-1.1.3-r1.trigger
Executing mkfontdir-1.0.7-r1.trigger
Executing glib-2.58.1-r2.trigger
OK: 277 MiB in 116 packages

**Comment by tbodt** [comment]
Should be fixed now.

**Comment by JaquesBoum** [comment]
Hm, I just reinstalled and tried - same result. Do I have to wait for the next test-release?

**Comment by tbodt** [comment]
Yeah
