### ISSUE TITLE
ctrl-g in emacs causes segfault

### ISSUE THREAD

**Issue by tbodt** [tbodt/ish#238]
```
3 page fault on 0x3 at 0x80be95d
```
Emacs 26.1, executable SHA1 db4c62d1ef040b5bb3ced216983d79b815ffea19
Workaround: ESC ESC ESC

**Comment by LittleHouse75** [comment]
Related — Control-x d enter (Dired with default directory) - Fatal error 11: Segmentation violation

**Comment by tbodt** [comment]
This is one of those "i'm a dumbass" bugs. Signal stacks were being based on the lowest address of the alternate stack region, so they would smash any variables found below. Just pushed a fix.

**Comment by LittleHouse75** [comment]
Great!  Waiting for Test Flight to update the code — I will check this out this weekend!  Thanks so much!
