### ISSUE TITLE
Improvement Ideas & Feedback

### ISSUE THREAD

**Issue by MishUshakov** [tbodt/ish#241]
Hey, @tbodt, thank you for building this amazing project. It's just unbelievable how good and snappy it works. Just wondering why Apple hasn't done it before (for iPads at least) it's so powerful and straightforward, I even managed to run Tor relay on my iPhone, dude. I have some suggestions for you (unfortunately can't send a pull-request, im not iOS developer yet):

- Moving cursor with 3D Touch
- Apple Watch App for viewing files & more
- Repair `top` command (crashes the app)
- Also wondering if it is possible to launch multiple Terminals
- Drag n dropping files from multitasking view to guest machine's current path (not via Files)?
- What about better power management? I can do a benchmark of battery usage running various software using ish, we need to find some leaks there. Are there currently any limits of CPU/Battery Voltage?

Thank you a lot.
Best regards.

**Comment by MishUshakov** [comment]
And if the app will ever be published on App Store, could you then add in-App purchase for donations, it would be much more convenient to support the project via iTunes as with Patreon :)

**Comment by tbodt** [comment]
> Hey, @tbodt, thank you for building this amazing project. It's just unbelievable how good and snappy it works. 

Glad you enjoy using it!

> Moving cursor with 3D Touch

I guess this could be done by sending arrow keys, though I'd prefer to find a way to make the built-in two-finger-drag or space-bar-drag work. That way it would work on devices without touch ID.

> Apple Watch App for viewing files & more

An Apple Watch app doesn't sound like it would really be all that useful to me.

> Repair top command (crashes the app)

It doesn't crash the app anymore, but it complains about missing /proc/meminfo, which is a little annoying to generate. Not hard, just annoying.

> Also wondering if it is possible to launch multiple Terminals

Yes, eventually.

> Drag n dropping files from multitasking view to guest machine's current path (not via Files)?

That's actually a really good idea, aside from the difficulty of finding your current path. Maybe I could do it like a desktop terminal and paste a file path.

> What about better power management? I can do a benchmark of battery usage running various software using ish, we need to find some leaks there. Are there currently any limits of CPU/Battery Voltage?

Given the fact that it runs an emulator, I don't think there's any way to reduce CPU usage without slowing down the programs you run. It doesn't use any CPU if you're not running anything, at least.

> And if the app will ever be published on App Store, could you then add in-App purchase for donations, it would be much more convenient to support the project via iTunes as with Patreon :)

The only thing is I don't know if I want "includes in-app purchases" under the "FREE" button.

**Comment by MishUshakov** [comment]
TANK you for your response. I was just recently thinking, whether it could make sense to build ish using wasm (web assembly) using WebKit's JavaScriptCore framework. There is project going on, called "JSLinux", it runs a buildroot directly through browser using wasm. It runs fast and technically works nearly the same way as your project does (if im talking about the right things). They even managed to run X11 on it
Here a is link: bellard.org/jslinux

**Comment by tbodt** [comment]
The problem with running anything through JavaScriptCore is you have to wait 100 microseconds for any message to be passed between your JavaScript and your main app, which gets ridiculous. jslinux is already several times slower than iSH, at 6 seconds to compile hello.c vs around 2 in iSH.
