### ISSUE TITLE
Youtube-dl does not work

### ISSUE THREAD

**Issue by VincentCCandela** [tbodt/ish#243]
I was able to install youtube-dl by doing “apk add youtube-dl” however when run youtube-dl no matter the flags, I always get:

Traceback (most recent call last):                                                                             
  File "/usr/bin/youtube-dl", line 4, in <module>                                                              
    import re                                                                                                  
  File "/usr/lib/python3.6/re.py", line 122, in <module>                                                       
    import enum                                                                                                
  File "/usr/lib/python3.6/enum.py", line 2, in <module>                                                       
    from types import MappingProxyType, DynamicClassAttribute                                                  
  File "/usr/lib/python3.6/types.py", line 171, in <module>                                                    
    import functools as _functools                                                                             
  File "/usr/lib/python3.6/functools.py", line 403, in <module>                                                
    _CacheInfo = namedtuple("CacheInfo", ["hits", "misses", "maxsize", "currsize"])                            
  File "/usr/lib/python3.6/collections/__init__.py", line 429, in namedtuple                                   
    exec(class_definition, namespace)                                                                          
  File "<string>", line 1, in <module>                                                                         
KeyboardInterrupt                      

It would not do anything so I would have to control- c it. If anybody could help it would be great because downloading youtube through Ish would be really useful.

**Comment by tbodt** [comment]
You’ll need to wait a minute or two for anything to happen.
