### ISSUE TITLE
Ssh-keygen copy paste adding or missing line breaks

### ISSUE THREAD

**Issue by jwknz** [tbodt/ish#247]
I generated an ssh-key successfully after installing openssl, but the copy and pasting broke the ssh key after displaying it onto the screen using `cat`.

The `vi` editor also had the same issues.

It took copying the key into an HTML file and copying it from safari to format it properly to paste it into Github.

Within the app using the command `ssh-keygen -l -f ~/.ssh/id_rsa.pub` showed that it had generated a valid ssh key. 

Using the github api, I had to paste the key into the api which gave me the malformed message.

After reading some forums, it seems that the \n break lines aren’t copied properly.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tbodt** [comment]
This is probably going to mean rewriting the entire terminal emulator to handle selection properly.

**Comment by francoisvignon** [comment]
I agree :-( 
the currently used term is nice to do quickly the job, but this one is not enough to do the job correctly
rewriting it may allow nicer things ... but some works.

regarding the current issue, maybe implementing pbcopy can be a good placeholder (already required in a previous issue):
cat id_rsa | pbcopy and the clipboard contains good data with good format.

implementing pbcopy and pbpast can be faster to setup than a correct terminal emulator.

you can defined two non standard syscall (or maybe this one was already present) and then make two short tools using it to move data to/from clipboard ;-)

from my point a view: selecting from the screen is not the ideal way to copy terminal output to clipboard (may be a lot a scroll for big output)

**Comment by francoisvignon** [comment]
these additional tools will can be provided in file system or as additional package (?) or from a repo ... don't know the good one.

this way open some opportunity: settings font size, theme, etc. from a script

**Comment by francoisvignon** [comment]
and also, some tools to interact with iOs: battery level, network information, sensors informations (accelerometer, gps position, ... ) from a script or from user software  :-) :-) :-)

**Comment by tbodt** [comment]
These sorts of things are probably better implemented as files such as /dev/clipboard.

**Comment by francoisvignon** [comment]
I agree ... easy to setup in your app (my opinion)

**Comment by tbodt** [comment]
Closing as "too hard"
