### ISSUE TITLE
Feature Request: Allow the Ish app to run in the background.

### ISSUE THREAD

**Issue by VincentCCandela** [tbodt/ish#249]
The Ish app should be allowed to run in the background if you leave the app. Sometimes I have to leave the app, and then the in-app processes would stop so allowing the app to run in the background would be great.

**Comment by tbodt** [comment]
iOS severely restricts running apps in the background, unless they're doing one of 9 specifically sanctioned background activities. One of these is playing audio, so the obvious solution is to add a mixtape player.

**Comment by Ronsor** [comment]
Let us choose a song to play in the background on repeat. some may choose music, others may play a silent mp3 or something.

**Comment by crcastle** [comment]
Anyone know if the ["Multitasking" functionality](https://support.apple.com/en-us/HT207582) on iPads as of iOS 11 would allow iSH to stay alive while using another app?

If not, is it possible to [hibernate](https://en.wikipedia.org/wiki/Hibernation_(computing)) all the processes running inside iSH before iOS stop iSH?

**Comment by tbodt** [comment]
> Anyone know if the "Multitasking" functionality on iPads as of iOS 11 would allow iSH to stay alive while using another app?

Nope.

> If not, is it possible to hibernate all the processes running inside iSH before iOS stop iSH?

That's what happens right now.

**Comment by jedieaston** [comment]
What if it was in slide-over view?

**Comment by tbodt** [comment]
That works the same as split view

**Comment by FD-** [comment]
iOS 13 brings a new background tasks API that might be worth investigating: https://developer.apple.com/documentation/backgroundtasks/bgtaskscheduler

**Comment by tbodt** [comment]
It doesn't really help. Background tasks have a time limit, and give no control over when they're started.

**Comment by FD-** [comment]
Alright, seems I didn’t read carefully enough: The docs don’t seem to explicitly mention a time limit, but the possibility to install an expiration handler implies there is one. I don’t understand what’s the difference between this new one and the old [beginBackgroundTask](https://developer.apple.com/documentation/uikit/uiapplication/1623051-beginbackgroundtask) API then.

**Comment by drpump** [comment]
Regarding slide over and ssh in particular (see #408, closed), port forwarding works when iSH is visible as a slide over panel, but as soon as you flick it off the screen, it stops working. 

So yes, need a better way to keep the app open in the background. The author of the [sshtunnel](https://apps.apple.com/us/app/ssh-tunnel-with-socks5-proxy/id1260223542) app notes in his responses to reviews that he had to switch from using the audio hack to using geolocation to make his app work in the background.

**Comment by b-** [comment]
I have a suggestion, though I don't know anything about implementation.

The Termius app, which is my preferred mobile SSH client, requests precise geolocation data in order to keep itself open in the background. It's _never_ closed on me when I didn't want it to, and requesting location data like that means I can easily tell that I left a session open by mistake if I do. I'd prefer if it had the option to enable location usage.

It's certainly abuse of the rules, but if they let Termius get away with it I'm sure they'd let this TestFlight app do it too.

**Comment by tbodt** [comment]
bump

**Comment by tbodt** [comment]
From #513:
> This is really a duplicate of #249, but location tracking is possibly a good idea. Background audio probably uses less battery though.

**Comment by itskenny0** [comment]
Background audio would pause my music playback though. That’s a no-no for me.

**Comment by tbodt** [comment]
I believe it is possible to play audio without affecting other audio.

**Comment by drpump** [comment]
Worthwhile to read the notes from the guy who built sshtunnel linked above. He says audio no longer works reliably and he had to switch to geolocation.

**Comment by tbodt** [comment]
@drpump He says he stopped using audio because it didn't pass app store review, not because it didn't work.

**Comment by tbodt** [comment]
You can now keep the app running in the background with the invocation `cat /dev/location > /dev/null &`.

**Comment by allisonober** [comment]
> 
> 
> iOS severely restricts running apps in the background, unless they're doing one of 9 specifically sanctioned background activities. One of these is playing audio, so the obvious solution is to add a mixtape player.

Legit though, why not play a silent MP3 on a loop?

**Comment by jedieaston** [comment]
It interrupts the user's currently playing music, since only one app can be playing music at a time (at least, iOS will only keep one alive at one time).
