### ISSUE TITLE
C floor() rounds toward zero, not toward -Inf

### ISSUE THREAD

**Issue by trwyant** [tbodt/ish#258]
The man page for floor() says it returns the largest integral value not greater than its argument. I have always understood "not greater than" in the algebraic sense -- that is, floor( -0.75 ) should return -1.0. I wrote some C to demonstrate, and in fact the macOS and VirtualBox Alpine runs do this. But the iSH run returns 0.0.

The attached .zip contains the test code, and logs of its output in various environments.
[floor.zip](https://github.com/tbodt/ish/files/2734427/floor.zip)

**Comment by tbodt** [comment]
floor(-2.75) gives -3 as expected. The issue is that attempting to convert anything whose absolute value is less than 1 to an int always gives 0.
