### ISSUE TITLE
Julia won't start

### ISSUE THREAD

**Issue by MasonProtter** [tbodt/ish#259]
Tried loading the Julia programming language from a compiled binary. Crashed from an illegal byte sequence(?). Steps to reproduce:
```
iPad:~# apk add curl 

iPad:~# curl https://julialang-s3.julialang.org/bin/linux/x64/1.0/julia-1.0.3-linux-x86_64.tar.gz --output julia-1.0.3-linux-x86_64.tar.gz

iPad:~# tar xvzf julia-1.0.3-linux-x86_64.tar.gz  

iPad:~# julia-1.0.3/bin/julia
julia-1.0.3/bin/julia: line 1: can't create @@@8: Illegal byte sequence                                                                                                                   
julia-1.0.3/bin/julia: line 1: ELF: not found                                                                                                                                             
julia-1.0.3/bin/julia: line 1: syntax error: unterminated quoted string      
```

This shouldn't be particularly surprising, but it'd be really freaking cool if we got this working. I'd love to run Julia code directly on my ipad.

**Comment by tbodt** [comment]
You're trying to run the 64-bit version and iSH is 32 bit only at the moment.

**Comment by tbodt** [comment]
Even the 32-bit version probably won't work because it depends on glibc. This is similar to the issue with Rust (#67).

**Comment by MasonProtter** [comment]
Right you are! I'm a little embarrassed to admit that I didn't even check if ish was 32 or 64 bit. I tried again with the 32 bit version of julia and I'm getting an even stranger error:
```
iPad:~# apk add curl 

iPad:~# curl https://julialang-s3.julialang.org/bin/linux/x86/1.0/julia-1.0.3-linux-i686.tar.gz --output julia-1.0.3-linux-i686.tar.gz

iPad:~# tar xvzf julia-1.0.3-linux-i686.tar.gz

iPad:~# julia-1.0.3/bin/julia
-ash: julia-1.0.3/bin/julia: not found                             
```
even though `julia-1.0.3/bin/julia` definitely exists and is an executable.

I was mostly just doing this (like the Rust guy) so it could go on the compatibility list.

**Comment by tbodt** [comment]
That's the error you get when running a glibc-dependent executable on a system without glibc.

**Comment by tbodt** [comment]
Gonna close this for the same reason as the rust issue.

**Comment by MasonProtter** [comment]
I noticed this is in he `Works` category for Compatability. I just checked and it seems to not work still for the same reasons as before.

**Comment by tbodt** [comment]
I think it moved because I closed the project?

**Comment by sbromberger** [comment]
Happy to help test if you need.
