### ISSUE TITLE
Error when downloading most things

### ISSUE THREAD

**Issue by cristeahub** [tbodt/ish#26]
When I tried to download rustup I got an SSL read error when trying to download the rustup installer, or cloning into github repos.

I run the following:
```
# apk add curl
# curl https://sh.rustup.rs | sh
...
curl: (56) LibreSSL SSL_read: error:06FFF064:digital envelope routines:CRYPTO_internal:bad decrypt, errno 0
...
```

Any pointers into what's happening? I am very new to this :)

**Comment by tbodt** [comment]
curl doesn't work on https websites right now, probably due to some subtle emulation bug. It's on my list.

**Comment by cristeahub** [comment]
That has to be a github record for response time. Thanks for letting me know! 👍 Feel free to close this if you want to track this issue in another way.

**Comment by cristeahub** [comment]
> As a workaround, you could try `wget -O - https://sh.rustup.rs | sh`.

I tried this. Hit a similar error `sl_client: tls read: read failed: error:06FFF064:digital envelope routines:CRYPTO_internal:bad decrypt, No error information`

**Comment by tbodt** [comment]
I coulda sworn that was working last time I tried it...

**Comment by cristeahub** [comment]
Turns out this error was from running the actual script that was downloaded, so the command did indeed work!

**Comment by tbodt** [comment]
Oh cool! Seems like the script is using curl. There are probably a dozen other reasons why rustup won't successfully install, and someday I'll go through the process and fix all of them, but that won't be for a while.

**Comment by tbodt** [comment]
I've tested curl and busybox wget with HTTPS, and they both work now.
