### ISSUE TITLE
spawn in expect does not work

### ISSUE THREAD

**Issue by fancl20** [tbodt/ish#261]
executing
```
expect -c "spawn ls"
```
get
```
The system has no more ptys.  Ask your system administrator to create more.
    while executing
"spawn ls"
```
may related to: http://www.linuxfromscratch.org//lfs/faq.html#no-ptys

**Comment by tbodt** [comment]
ptys are not implemented at the moment.

**Comment by tbodt** [comment]
This isn't quite fixed, `expect -c "spawn ls; interact"` just hangs after ls finishes

**Comment by tbodt** [comment]
ok seems to work now. fbd3212
