### ISSUE TITLE
small iOs issue when changing Init Command in about 

### ISSUE THREAD

**Issue by francoisvignon** [tbodt/ish#264]
If you change the init command and after you quit the shell by typing ^D or exit, you have a kind popup indicating "attempted to kill init", exit or "I typed the init command wrong, let me to fix it", thanks.

if you select "let me to fix it", the current bash input is broken. the only way to exit is to kill iSh.
of course, you can go into about, etc. but the bash is lost.

**Comment by tbodt** [comment]
This is intentional, there's currently no sane way to restart everything. I'm assuming if you're mucking around with the init command, you're an advanced user and you know what you're doing. Maybe I should move it to an "advanced settings" section.

**Comment by tbodt** [comment]
Or do what uBlock origin does and have a switch that says "I am an advanced user" that reveals advanced settings.

**Comment by francoisvignon** [comment]
ok, in this case, maybe if you select "let me to fix it", can you directly activate about screen ?

**Comment by francoisvignon** [comment]
but not very important, it's just for information, don't waste time with that ;-)
