### ISSUE TITLE
Ghostscript fails to install with apk

### ISSUE THREAD

**Issue by weiszr** [tbodt/ish#265]
I tried to install ghost view and it give the following error message:
Robert-Weisss-iPad:~# apk add ghostscript                                                                                                                                   
(1/5) Installing dbus-libs (1.10.24-r1)                                                                                                                                     
(2/5) Installing avahi-libs (0.7-r1)                                                                                                                                        
(3/5) Installing cups-libs (2.2.6-r0)                                                                                                                                       
(4/5) Installing jbig2dec (0.14-r0)                                                                                                                                         
(5/5) Installing ghostscript (9.26-r0)                                                                                                                                      
Executing busybox-1.28.4-r3.trigger                                                                                                                                         
Executing fontconfig-2.12.6-r1.trigger                                                                                                                                      
/usr/share/fonts: failed to write cache                                                                                                                                     
/usr/share/fonts/Type1: failed to write cache                                                                                                                               
ERROR: fontconfig-2.12.6-r1.trigger: script exited with error 2                                                                                                             
OK: 3199 MiB in 165 packages

**Comment by JaquesBoum** [comment]
Matches my ticket #237  - fontconfig seems to be the actual culprit.

**Comment by tbodt** [comment]
Yeah it looks very similar. Gonna close as duplicate.
