### ISSUE TITLE
Feature request: Add X-Callback and URL scheme to run shell commands

### ISSUE THREAD

**Issue by yonika** [tbodt/ish#268]
• iOS X callback and URL Scheme to run a shell command with arguments can be very very useful.
• With SIRI Shortcuts it can be used to run a bash / Perl / python script with command line arguments.
• X-callback also allows the called app to return a to the calling app with a success / error / canceled value.
• This would open a world of options to use this app

**Comment by yonika** [comment]
An example use of url scheme for such a thing is in Pythonista. The following is a url I use with x-callback in shortcuts to run a script in Pythonista- 
pythonista3://switcher.py?action=run&args=-mget_state

To call back to the shortcuts app from Pythonista- I use the following in my python script:
app = UIApplication.sharedApplication()
app.openURL_(nsurl('shortcuts://x-success'))

**Comment by tbodt** [comment]
This has been requested before, #260
