### ISSUE TITLE
Colorful error)

### ISSUE THREAD

**Issue by Antoxa223** [tbodt/ish#269]
If you enter "cat /bin/login", then you can get a very beautiful interface error)

**Comment by Antoxa223** [comment]
Version 44

**Comment by Antoxa223** [comment]
![12a1a12f-9888-4ea0-a023-d5c4c82a46d5](https://user-images.githubusercontent.com/42963432/50926011-a50ab580-145c-11e9-8e18-86cda0030a27.png)
![32c07ad3-4cd3-42aa-b227-f06e4b3c9152](https://user-images.githubusercontent.com/42963432/50926013-a50ab580-145c-11e9-8c29-dc7436b87431.png)

**Comment by tbodt** [comment]
The /bin/login file happens to contain an escape sequence that changes your background color. Nothing I can do about it.
