### ISSUE TITLE
Crash from badly formatted curl piped into shell

### ISSUE THREAD

**Issue by cristeahub** [tbodt/ish#27]
I got this crash when trying to download the rustup toolchain. Full crash in the app.

Here's my command to reproduce it.
```
# curl https://sh.rustup.rs | sh -s --y
```

After doing this two times I now have a crash-on-launch version of the app. I believe I might need a reinstall. I will send you the crashlogs by mail.

**Comment by tbodt** [comment]
Before you reinstall, would it be possible to make an iTunes backup and extract the files? (I think you'd have to use some third party extractor. They're in the app.ish.iSH app group.)

**Comment by cristeahub** [comment]
Interesting, I'll check that out tomorrow. Haven't reinstalled yet, so I still have the possibility to do that. I get a popup on launch where it says "attempted to kill init" and when I press "goodbye" the app crashes.

**Comment by tbodt** [comment]
Is there anything on the screen behind the "attempted to kill init" message? That message (and the crash when pressing goodbye) is what's supposed to happen when you type `exit` at the prompt.

**Comment by cristeahub** [comment]
Yes, it's the following:

```

Welcome to Alpine!

The Alpine Wiki contains a large amount of how-to guides and general
information about administrating Alpine systems.
See <http://wiki.alpinelinux.org>.

You can setup the system with the command: setup-alpine

You may change this message by editing /etc/motd.

<cursor>
```

**Comment by tbodt** [comment]
Something seems to be up with your bashrc...

In the next version, I'm going to add some way to easily export the files so you can send them to me; that would make debugging these kinds of things a lot easier. In the meantime, I tested out [iBackupMounter](https://github.com/k06a/iBackupMounter) and it seems like it would work, the files would be in AppDomainGroup/group.app.ish.iSH.

**Comment by cristeahub** [comment]
Thanks! I'll check this out after work today and see if I can extract the files (I'm on Europe time). I haven't edited my bashrc, so if that's the problem it has to be some crash that caused that file to be changed.

Anyway I'll pick this back up after work.

**Comment by cristeahub** [comment]
After a lot of tries I unfortunately won't be able to retrieve the files. I couldn't get all the components for iBackupMounter working correctly on my system, sorry. I'll wait for the version where the files can be exported instead!

**Comment by tbodt** [comment]
Can't reproduce anymore. I now get
```
info: downloading installer
```
followed by an error about being unable to download the installer.
