### ISSUE TITLE
Bashrc 

### ISSUE THREAD

**Issue by mkapra** [tbodt/ish#277]
Is the bashrc for bash working or am I making a mistake?

**I tried to import .bash_aliases with .bashrc:**
```
If [ -f ~/.bash_aliases ];
then
    . ~/.bash_aliases
fi
```

Is there something wrong?

**Comment by tbodt** [comment]
What did it do instead of working? (the `If` definitely shouldn't be capitalized, but that could be a copy-paste error)`

**Comment by mkapra** [comment]
There wasn‘t any message. The aliases in the .bash_aliases are not working.

**Comment by tbodt** [comment]
Did you install bash and set it as your default shell? If you don't, you'll be using the busybox shell, which reads .profile instead of .bashrc.

**Comment by mkapra** [comment]
Yes I‘ve installed bash and in /etc/passwd the Shell for root is bash. 

$echo $SHELL
/bin/bash

**Comment by tbodt** [comment]
When starting bash as a login shell it doesn't execute .bashrc, it executes .bash_profile. But when you start a shell by typing `bash` at the prompt, it executes .bashrc and not .bash_profile. I'd recommend putting `. .bashrc` in your `.bash_profile`. This isn't a problem with iSH though.
