### ISSUE TITLE
/etc/skel not found

### ISSUE THREAD

**Issue by mkapra** [tbodt/ish#278]
I did not found /etc/skel while adding a new user.

**Comment by tbodt** [comment]
alpine doesn’t have an /etc/skel.

**Comment by mkapra** [comment]
Hmmm okay. I found in command ‚adduser‘ an option -k (Skel)

`BusyBox v1.28.4 (2018-05-30 10:45:59 UTC) multi-call binary.                                                                                                      
                                                                                                                                                                  
Usage: adduser [OPTIONS] USER [GROUP]                                                                                                                             
                                                                                                                                                                  
Create new user, or add USER to GROUP                                                                                                                             
                                                                                                                                                                  
        -h DIR          Home directory                                                                                                                            
        -g GECOS        GECOS field                                                                                                                               
        -s SHELL        Login shell                                                                                                                               
        -G GRP          Group                                                                                                                                     
        -S              Create a system user                                                                                                                      
        -D              Don't assign a password                                                                                                                   
        -H              Don't create home directory                                                                                                               
        -u UID          User id                                                                                                                                   
        -k SKEL         Skeleton directory (/etc/skel)               `

**Comment by tbodt** [comment]
If it doesn't exist it should be fine with creating an empty home directory.
