### ISSUE TITLE
Add support for UTF-8 or something

### ISSUE THREAD

**Issue by Mnpn03** [tbodt/ish#28]
Trying to use special characters (emoji not included?) iSH displays it with the ASCII encoding?
`å`, `ä`, `ö` and `ü` are a few problematic characters.

![](https://i.imgur.com/huqs0Da_d.jpg)

**Comment by tbodt** [comment]
I actually have no idea what's causing this. Will leave the issue open.

(wow that image is low resolution)

**Comment by Mnpn03** [comment]
I have absolutely no idea why that happened, here:

![](https://cdn.discordapp.com/attachments/371009660465184778/510531751505035264/image0.png)

**Comment by tbodt** [comment]
Fixed in 
https://github.com/tbodt/ish/commit/fc4da4c1127d630580fbd3d3a6dd76dae84ab74e
