### ISSUE TITLE
x86_64 Alpine Support

### ISSUE THREAD

**Issue by sboddeus** [tbodt/ish#282]
Sorry for being vague.
Is there a tracker or project plan for supporting x86_64?
There are some Alpine packages that seem to only support x86_64 (ghc) that I would like to eventually run.

I would be happy to create a tracker, but I thought I would check first.

**Comment by tbodt** [comment]
I have no plans for 64-bit support, making the emulator work for 32-bit code was hard enough.

GHC has 32-bit glibc builds available, so you could probably build glibc from source and use that.
