### ISSUE TITLE
SSHD not showing up in latest version

### ISSUE THREAD

**Issue by jwknz** [tbodt/ish#283]
To make the ssh server work, do I need to install something? Or is it built in?

To clarify: there is no sshd in /usr/sbin as I can see in this tweet:

[https://twitter.com/ish_app/status/1087827694664835072?s=21](https://twitter.com/ish_app/status/1087827694664835072?s=21)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by DavidSouthgate** [comment]
You'll need to install it first:
`ask add openssh`

**Comment by tbodt** [comment]
There are instructions in the release notes (though i forgot to mention you have to enable AllowRootLogin in /etc/ssh/sshd_config)
