### ISSUE TITLE
gcc doesn’t work when I try to compile c++ source code

### ISSUE THREAD

**Issue by VincentCCandela** [tbodt/ish#286]
When I try to compile c++ with gcc, I get the error:

gcc: error trying to exec 'cc1plus': execvp: No such file or directory 

It would be great if you guys could fix this because I intend on using this app for my c++ class. 

BTW great app!

**Comment by tbodt** [comment]
Glad you like the app! This is because when you install gcc with apk it doesn’t include a lot of important things. Install build-base instead.

**Comment by sboddeus** [comment]
These could be Alpine issues (as opposed to iSH).
In the meantime install g++, it will include everything you want.
`apk add g++12th

**Comment by tbodt** [comment]
@sboddeus if you just install g++ it will be missing header files

**Comment by sboddeus** [comment]
@tbodt That’s a shame, all the little c++ programs I had tried compiled. But I didn’t include more than iostream. 😐
