### ISSUE TITLE
times command weird bug

### ISSUE THREAD

**Issue by M4cs** [tbodt/ish#29]
When you run the times command in the latest test flight build it will just black screen and crash producing the log attached. If you are screen recording it will show a UIAlertView and say "Attemping to kill init" with the closing button "goodbye". Dont know what the times command does but I'm guessing this is a bug?

**Comment by M4cs** [comment]
https://ufile.io/fg225 Link to log file

**Comment by tbodt** [comment]
I had no idea there was a times command, and I don't know what it's supposed to do either.

**Comment by tbodt** [comment]
Oh turns out it's a shell builtin, which explains why it crashes the whole app. I'll fix it later.

**Comment by tbodt** [comment]
This was fixed by @woachk in #45
