### ISSUE TITLE
Emojis Incorrect Character

### ISSUE THREAD

**Issue by ntindle** [tbodt/ish#297]
When typing the first emoji, it appears as 
ð??? Instead of whatever emoji it is supposed to be. All subsequent emojis work fine except for the width #296

**Comment by tbodt** [comment]
busybox shell is reading the first byte, deciding that's a complete unicode sequence when it isn't, and then reading the next 3 bytes as a complete unicode sequence. WHY

**Comment by tbodt** [comment]
Seems to be working now, probably since the switch to hterm.
