### ISSUE TITLE
Lower screen covered by meta keys with Apple keyboard attached

### ISSUE THREAD

**Issue by jjcheramie** [tbodt/ish#298]
When using iSH with the apple keyboard with my 2018 iPad Pro 10.5, the meta keys cover the lower screen in at the command prompt and when I run emacs.

**Comment by drpump** [comment]
Have also seen this. It's also a problem in Pythonista, so I suspect that there's something amiss in the iOS libraries. One workaround (kind-of) is to open another app in split view, which seems to realign the bottom border of the ish window.

**Comment by tbodt** [comment]
Getting this perfect is really, really hard. If you do anything to change the size of the window though, such as rotating your device, that should improve the situation.
