### ISSUE TITLE
Emacs does not work

### ISSUE THREAD

**Issue by ghanan94** [tbodt/ish#30]
When do apk add emacs then try to run emacs, I get:
\# emacs
Fatal error 31: Bad argument to system callBad system call
\#

**Comment by MasonProtter** [comment]
Do we have any idea what is needed to get emacs working?

**Comment by tbodt** [comment]
I had a quick look at this and the system call emacs is trying to use is `timerfd_create`. That's a significant subsystem that would take probably a day to implement right.

**Comment by cmore-zz** [comment]
Would love to have emacs on iOS... would be a real game changer. Any way to donate to move this up on the priority list?

**Comment by tbodt** [comment]
I'm a vim user so no 😛 But if you want to work on it, feel free!

**Comment by davidradkowski** [comment]
So is it on a todo list at all mate?

**Comment by tbodt** [comment]
![img_2868](https://user-images.githubusercontent.com/5678977/49781608-440a8900-fcc8-11e8-979c-3d0797e948e6.PNG)
