### ISSUE TITLE
DNS config should probably be updated when network changes

### ISSUE THREAD

**Issue by DavidSouthgate** [tbodt/ish#300]
As DNS config is only loaded when the app is loaded, changing networks or using a VPN may result in networking being effectively lost. This would happen if the current network uses an internal DNS server which isn't accessible by the new network.

An ideal solution would be to regenerate /etc/resolv.conf every time the network changes

I believe this might fix #227

**Comment by tbodt** [comment]
How do I detect when the network changes?

**Comment by fernandotcl** [comment]
You could use the ‘SCNetworkReachability’ APIs or maybe the new Network framework.

**Comment by jaclu** [comment]
This would help with the current issue where many iOS VPNs change DNS and since iSH doesn't detect it can't resolve names until you either update /etc/resolv.conf or reboot.
So even if the issue is old, there is still demand for this to be sorted.
