### ISSUE TITLE
Crash in apk upgrade

### ISSUE THREAD

**Issue by tbodt** [tbodt/ish#302]
Current theory: it's a foreign key constraint violation. The crashdumps I have for this are screwed up unfortunately, so let's wait for a massive spike in TestFlight crash reports and see if that's more helpful.

**Comment by mr100percent** [comment]
The crash happens quickly, but in my experience it happens during a specific step of upgrading libvorbis 1.3.6-r1 to 1.3.6-r2 . It gets specifically to 97% in the progress bar and crashes instantly.

**Comment by mr100percent** [comment]
Resolved for me with latest hotfix update (47)

**Comment by tbodt** [comment]
The hotfix changed nothing in the problematic code, sounds like it's simply the act of reinstalling, and triggering a rebuild.

**Comment by tbodt** [comment]
No one's complained about this for a while so I'm going to close the issue.

**Comment by cafeninja** [comment]
It happens to me today on (48).  It seems to get to the last downloaded item and then the whole app crashes.  I can’t find a way to get the dump.  But the processes announces that it will launch busy box once completed. Could it be that which is causing the crash?

If I need to open a different report because this one is closed.  Let me know.
Please feel free to guide me on how to get the crash report out, happy to help any way I can.

**Comment by tbodt** [comment]
The crash dump can be found in Settings -> Privacy -> Analytics -> Analytics Data.

**Comment by cafeninja** [comment]
{"share_with_app_devs":false,"bug_type":"179","os_version":"iPhone OS 12.1.4 (16D57)"}
{
  "scheduled" : true,
  "machine_config" : "iPad7,2",
  "log_version" : 2,
  "region_format" : "US",
  "os_version" : "iPhone OS 12.1.4 (16D57)",
  "language" : "en-US",
  "sessions_data" : [
{
  "app_arch" : "arm-64bit",
  "app_build_version" : "48",
  "app_version" : "1.0",
  "app_adamid" : 1436902243,
  "app_sessionreporter_key" : "21267A62-4962-45E7-B8F2-E24BE1F6B3B5",
  "app_storefront" : 143441,
  "app_bundleid" : "app.ish.iSH",
  "app_events" : [
    {
      "date" : "2019-03-29T07:26:16+0100",
      "state" : "foregroundRunning",
      "type" : "app_session",
      "duration" : 18
    }
  ],
  "app_is_beta" : true,
  "slice_uuid" : "9038D303-F50F-39C3-9DAB-555F25416852",
  "app_cohort" : "2|date=1550435400000&sf=143441&tid=8abf45dc8afff68317056821136e5c44ed90618dc9ee99f9bb6914d6e960d95f&ttype=e"
}
  ],
  "log_timestamp" : "2019-03-29T19:04:25+0100"
}

**Comment by tbodt** [comment]
Can you send the entire thing, not just the bit of json at the top? Thanks!

**Comment by cafeninja** [comment]
[ish_crash_logs.zip](https://github.com/tbodt/ish/files/3026798/ish_crash_logs.zip)
 I tried to crash the app to get a fresh .session file.  But it updated correctly this time.  I have two session files, one which is the content you see above.  I will try to attach them both here.

**Comment by tbodt** [comment]
Ah those are the wrong files. The ones you want start with iSH.

**Comment by cafeninja** [comment]
I didn’t have any others there.  Sorry.  But upgrade isn’t crashing it now, I’m not very worried about it. Kinda glad I didn’t open a new case.  But I can say it did happen 3 times in a row on the last package update (there were 14).  I’ll look for other files if it happens again.  Thanks for checking.
