### ISSUE TITLE
File app showing incorrect content

### ISSUE THREAD

**Issue by TheLastDestroyer** [tbodt/ish#303]
Opening files in the files app seems to show the content of old or different files and fails to open for some extensions (so far .py).
I have two files, test.py which shows up as test and opens as a blank screen in files and test2.txt which shows up as test2 and shows the contents of test.py.

![img_0142](https://user-images.githubusercontent.com/17359435/52520057-a34f3000-2c5c-11e9-9e60-02ea6cddc499.png)
![img_0136](https://user-images.githubusercontent.com/17359435/52519992-d7762100-2c5b-11e9-91a4-7e7ff46bc110.jpeg)
![img_0137](https://user-images.githubusercontent.com/17359435/52519995-d93fe480-2c5b-11e9-8a51-799af3e60833.png)
![img_0138](https://user-images.githubusercontent.com/17359435/52519996-dba23e80-2c5b-11e9-91eb-d16905ce3f97.jpeg)

Also when opening files outside files (in my case pythonista) it sometimes works but loses the file name (goes form test.py to a random string of numbers), and other times fails to open. Attempting to rename the file in pythonista also fails.

![img_0139](https://user-images.githubusercontent.com/17359435/52520022-2a4fd880-2c5c-11e9-8c90-411a965cdfc5.jpeg)
![img_0140](https://user-images.githubusercontent.com/17359435/52520023-2cb23280-2c5c-11e9-9b8b-0098820918ef.png)

**Comment by donwb** [comment]
Can confirm, seeing same behavior here regarding file names. I’ve been able to successfully open files every time edit/save with no issues in both Textastic and GoCoEdit, but the file name is just random numbers w/no extension
![d8129614-4297-4fde-878e-5020cec30b52](https://user-images.githubusercontent.com/532590/52544796-15209a00-2d81-11e9-8ba8-71b4ed11943c.jpeg)

**Comment by tbodt** [comment]
Attempting to rename any file from a file provider in Pythonista fails, so that's not super interesting.

I just fixed this in master, would it be worth pushing a new build just with that fix?

**Comment by TheLastDestroyer** [comment]
If its not too much trouble

**Comment by donwb** [comment]
agreed, from what I can tell atm this is the last piece of a really important workflow (clone in ish, code in Textastic, build in ish, repeat).  This bug makes it tough to discern files from each other in the editor, plus breaks syntax highlighting... once it's fixed, it's on... 🙌
