### ISSUE TITLE
Running Python programs with arguements

### ISSUE THREAD

**Issue by VincentCCandela** [tbodt/ish#305]
Running single python files without arguements works just fine. However, when I try to run other python programs with arguements such as youtube-dl, I get:

Asdfhaklsdjfh:~/youtube-dl# ./youtube-dl https://www.youtube.com/watch?v=S-Xm7s9eGxU                           
Usage: youtube-dl [OPTIONS] URL [URL...]                                                                       
                                                                                                               
youtube-dl: error: You must provide at least one URL.                                                          
Type youtube-dl --help to see a list of all options.                                                         

Which is the same error I get with the pip installed version of youtube-dl.

In addition. When I try to run pip, no matter what the arguements or commands are, I get the help printout. 

None of these errors were happening before the upgrade so I assume there’s some problem that’s been introduced in the upgrade.

**Comment by TheLastDestroyer** [comment]
When running python files directly (ie with a shebang, ./file.py rather than python file.py) arguments are not getting to sys.argv
![img_0144](https://user-images.githubusercontent.com/17359435/52523376-99dbbd00-2c88-11e9-8fc5-3e765762839c.png)

Could get round it by running python(3) /path/to/file.py args

**Comment by TheLastDestroyer** [comment]
This isn't a python problem, happens every time a script is run directly
![img_0145](https://user-images.githubusercontent.com/17359435/52523648-8120d680-2c8b-11e9-917a-1254162e4dc4.png)

**Comment by VincentCCandela** [comment]
I think this issue has been patched.
