### ISSUE TITLE
expect fails with segmentation fault

### ISSUE THREAD

**Issue by fancl20** [tbodt/ish#308]
I'm trying to use a expect script to auto login ssh server with password and TOTP. It sometimes fails with a segmentation fault. dmesg reported
```
unknown ioctl 5413
68 page fault on 0x0 at 0xf7f57877
```
It can't be reproduced stably.

Version 1.0 (47)

**Comment by tbodt** [comment]
Can you post an expect script that sometimes reproduces the problem?

**Comment by fancl20** [comment]
```
#!/usr/bin/expect
spawn oathtool --totp AAAAAAAAAAAAAAAAAAAA
expect "\r" {
    set TOTP $expect_out(buffer);
}
spawn ssh xxx@yyy
expect {
    "Password:" {
        send "aaabbbccc\r";
        exp_continue;
    }
    "Verification code:" {
        send "$TOTP\r";
    }
}
interact
```

**Comment by tbodt** [comment]
Can't reproduce. Let me know if it's still a problem.
