### ISSUE TITLE
‘mv’ command internal to bash fails with ‘Bad System Call’

### ISSUE THREAD

**Issue by mthused** [tbodt/ish#312]
Dmesg shows:
‘missing syscall 353’ when mv is attempted within bash- busybox mv works fine.

Sorry, this is ‘coreutils’ mv after looking further.

**Comment by Mnpn03** [comment]
`mv` launches the busybox mv for me in bash on TF build 48, and does work:
```
Device:~# mv
=> BusyBox v1.28.4...
Device:~# mv thing thong
Device:~#
```
Although `neofetch` still reports ash when in bash, but `echo $0` correctly displays `bash`.

**Comment by tbodt** [comment]
Can reproduce after upgrading to 3.9 and installing coreutils.
