### ISSUE TITLE
A Few Bad Syscalls

### ISSUE THREAD

**Issue by iamrecursion** [tbodt/ish#316]
I've been trying to set up a chroot with `debootstrap`, and it fails with a bad system call part-way through.

The sequence of commands is as follows (run as root):
```
mkdir ~/chroot
debootstrap --arch=i386 --no-check-gpg jessie ~/chroot
```

Checking the log, this fails with a bad system call. I imagine the most relevant part of the `dmesg` output is `668 missing syscall 353`, but I can provide the full dmesg output if needed.

**Comment by tbodt** [comment]
syscall 353 (renameat2) is implemented in master.

**Comment by iamrecursion** [comment]
Excellent. Just not made it to TestFlight yet? I’m not building myself.

**Comment by tbodt** [comment]
Indeed not. I expect to be pushing a new build in a few days.

**Comment by iamrecursion** [comment]
Glad to hear it! I’m trying to get GHC working on here, so I imagine I’ll run into a few more non-working syscalls that turn out to be important!
