### ISSUE TITLE
feature request / suggestion: exit

### ISSUE THREAD

**Issue by rmanly** [tbodt/ish#320]
Similar to #171 I was wondering if it would be possible to capture the exit command or something and simply cause iOS to go to the home screen.

I type exit a lot out of habit when I'm done doing something and it would be nice if iSH could just kick you back to home.

Not sure if this is even possible on iOS but it would be a nice behavior.

Thanks!

**Comment by saagarjha** [comment]
Is this not what iSH does today?

**Comment by ntindle** [comment]
It doesn’t do it gracefully.

**Comment by tbodt** [comment]
It does this already actually. Your shell session is restarted though, there's no way around that.
