### ISSUE TITLE
When I run git clone,if lock the screen ,then unlock,the process will stop

### ISSUE THREAD

**Issue by flyfire100** [tbodt/ish#324]
When I run git clone , if. Lock the screen , then unlock , the   Clone process will  stop

**Comment by viniciussalmeida** [comment]
I think that this is an expected behaviour, since iSH can't run in background yet...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tbodt** [comment]
It shouldn't stay stopped when you reopen the app.

**Comment by tbodt** [comment]
It shouldn't stay stopped when you reopen the app.

**Comment by viniciussalmeida** [comment]
Just to record what I've sent on Discord, can reproduce the bug, apparently always occurs (I tried 4 times in a row). When unlocking the screen, I can type but iSH keeps unresponsive until I hit ^C: ![GitHawk Upload by viniciussalmeida](https://i.imgur.com/k3MSY4x.jpg)

As you requested, I'll try to reproduce this on Xcode to send you the stack trace.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tbodt** [comment]
I've managed to fix this so it will fail immediately saying "the remote end hung up unexpectedly".
