### ISSUE TITLE
after upgrade ios to 12.1.4 (ipad) .Program flashback

### ISSUE THREAD

**Issue by daDaiMa** [tbodt/ish#330]
hello . i found that when i use vim and run the command :q! or :wq .  then the ish will flashback

 the situation never happened before i upgrade my ios to 12.1.4   

and now ,when i open file with vim . the file loaded slowly and the vim is bluntness ,I had to wait a few seconds to edit

**Comment by tbodt** [comment]
What do you mean by "flashback"?

**Comment by daDaiMa** [comment]
> What do you mean by "flashback"?
the mean is the ish will exits

**Comment by tbodt** [comment]
Sounds like it crashed. Can you send a crash dump? You can find that in Settings > Privacy > Analytics > Analytics Data.

**Comment by jonathan-w-king** [comment]
I just tried it, and I cannot replicate the crash with vim 8.1 on Alpine 3.9.0 and iOS 12.1.4.

(Actually, vim seems to work just fine as far as I can tell, which is more than I can currently say for the editor of my religion.)

(Reaching for an explanation here, but on my keyboard set-up I use `^[` as `ESC` to get to the `:` prompt; is this what you are doing?)

**Comment by tbodt** [comment]
Closing for lack of repro.
