### ISSUE TITLE
rtorrent runs, creates .meta file but stops with “Low diskspace” warning

### ISSUE THREAD

**Issue by JaquesBoum** [tbodt/ish#332]
On my quest to test packages running in ish I recently tried rtorrent. It starts fine and accepts magnet-links. It creates a .meta-file in the home directory (so writing files has to work), but then stops with

“Inactive: Low diskspace.”

After quitting console shows:
`Caught Segmentation fault, dumping stack:
Stack dump not enabled.
Aborted`

**Comment by tbodt** [comment]
First thing to check, are you actually out of disk space on your device? If not, this is a bug.

**Comment by JaquesBoum** [comment]
Good Advice - but space is available in ample quantities. The torrents I used for testing are only about 100mb and I have 300gb+ of free space. :)

**Comment by tbodt** [comment]
rtorrent doesn't do this anymore.

**Comment by tbodt** [comment]
Apparently I was wrong about this being fixed, but it really is fixed now. #509
