### ISSUE TITLE
iSH crashes installing a python3 module

### ISSUE THREAD

**Issue by Teg79** [tbodt/ish#334]
After installing python3, libc-dev, gcc and upgraded pip I tun the command:
`pip install uvloop`

Then, after a long wait the app crashed
[iSH-2019-03-07-162123.ips.beta.txt](https://github.com/tbodt/ish/files/2942257/iSH-2019-03-07-162123.ips.beta.txt)

**Comment by tbodt** [comment]
That crash seems like an out-of-memory error. That might make it hard to reproduce.

**Comment by tbodt** [comment]
@Teg79 Did you get it to work?

**Comment by Teg79** [comment]
No, but if it is an out of memory error there is little we can do

**Comment by tbodt** [comment]
Still worth investigating.

**Comment by tbodt** [comment]
I fixed a major memory leak recently so I'm going to close this for now. I'll be doing more heap profiling later.
