### ISSUE TITLE
Can't install any ruby gems: “ERROR:  While executing gem ... (Errno::EINVAL)    Invalid argument” 

### ISSUE THREAD

**Issue by ahope1** [tbodt/ish#335]
Always get the error “ERROR:  While executing gem ... (Errno::EINVAL)    Invalid argument” whenever I try to install any ruby gem. (I've already apk-added ruby, ruby-full, and ruby-dev.)

[iSHFileProvider-2019-03-07-124445.ips.beta.zip](https://github.com/tbodt/ish/files/2943522/iSHFileProvider-2019-03-07-124445.ips.beta.zip)

https://twitter.com/iSH_app/status/1103690775987073026

**Comment by tbodt** [comment]
Works for me. Was this with a clean install of iSH?

**Comment by ahope1** [comment]
Yes. Here is what I get from a clean install:

![IMG_3955](https://user-images.githubusercontent.com/11441088/54078863-21d4d700-42c8-11e9-9326-5b089e836986.PNG)
![IMG_3956](https://user-images.githubusercontent.com/11441088/54078864-25685e00-42c8-11e9-9c1b-03111f8a5cd4.PNG)
![IMG_3957](https://user-images.githubusercontent.com/11441088/54078865-28fbe500-42c8-11e9-98c9-9008dc89a766.PNG)
![IMG_3958](https://user-images.githubusercontent.com/11441088/54078868-2d280280-42c8-11e9-9607-36c206cd1505.PNG)
![IMG_3960](https://user-images.githubusercontent.com/11441088/54078871-30bb8980-42c8-11e9-88ad-b907b7b6df54.PNG)

**Comment by ahope1** [comment]
Reinstalled iSH and Ruby yesterday, and gem now works!
