### ISSUE TITLE
Keyboard Language support problem when execute script

### ISSUE THREAD

**Issue by JimChrModder** [tbodt/ish#338]
When I open my script which has some Greek parts,it prints them fine,but when I type in Greek,it just types ^^^^^
But when I just open iSH, before get in the script, it supports all Greek alphabet...
![jpeg_20190308_133550](https://user-images.githubusercontent.com/30021291/54026985-b0c0e280-4154-11e9-84b4-8b5125366e25.jpg)

**Comment by TheLastDestroyer** [comment]
Seems the corect characters are getting through, just some sort of display bug
![img_0148](https://user-images.githubusercontent.com/17359435/54040139-96baea80-41bc-11e9-9597-deb7cf568600.png)

**Comment by tbodt** [comment]
This has been fixed and the fix will be in the next build.
