### ISSUE TITLE
make not working

### ISSUE THREAD

**Issue by showgood** [tbodt/ish#341]
when run make, it gives me error:
```
make: *** INTERNAL: readdir: Not a directory.  Stop.
```

**Comment by tbodt** [comment]
Can you provide more details? What are you trying to do?

**Comment by showgood** [comment]
I was trying to install doom-emacs.

Basically I did following steps:
```
git clone https://github.com/hlissner/doom-emacs.git ~/.emacs.d
git checkout develop
cd ~/.emacs.d
make quickstart
```

which triggers the error I mentioned earlier.

**Comment by saagarjha** [comment]
Commenting out [this check](
https://github.com/tbodt/ish/blob/d6ca8f99a043e97b1eea610b8cceebcc5bee3a05/fs/dir.c#L35) makes it seem to work. But I’m sure there’s something else going on :/

**Comment by tbodt** [comment]
@saagarjha do you know if this is a problem with make in general or is specific to doom-emacs?

**Comment by saagarjha** [comment]
It’s a problem with make in general. For some reason it tries to call `readdir` on a file :/

**Comment by tbodt** [comment]
Which file?

**Comment by saagarjha** [comment]
Argh, now I need to get out of bed…give me a second to set up all the stuff I had when I was debugging this.

**Comment by tbodt** [comment]
Ah, don't bother, it wouldn't take me long to find out.

**Comment by saagarjha** [comment]
I'm out of bed, but I don't have npm installed, so you are likely to get this information faster than I can.

**Comment by tbodt** [comment]
`modules/README.org`. strange...

**Comment by saagarjha** [comment]
So it's reusing the file descriptor, or what?

**Comment by tbodt** [comment]
I was messing around and got it to call `dup2(1, 1)` which crashed. That's not related to this issue though.

**Comment by saagarjha** [comment]
IIRC it was trying to call this on a closed file descriptor or a file or something stupid which is why it was messing up.

**Comment by tbodt** [comment]
It seems to be related to how make does globbing. Minimal repro:

```
all:
	echo $(wildcard Makefile/*)
```

**Comment by tbodt** [comment]
This is due to O_DIRECTORY not being implemented.

**Comment by showgood** [comment]
thanks for all the investigation, what would be the solution to get it working? or it won't work as of now until some feature is added to ish?

**Comment by tbodt** [comment]
It'll work better in the next update.

**Comment by showgood** [comment]
thanks
