### ISSUE TITLE
Cloning Private Github Repository Hangs

### ISSUE THREAD

**Issue by EthanReese** [tbodt/ish#350]
![4F1F3193-80A7-4408-97A7-F1D8053ED1FB](https://user-images.githubusercontent.com/12105934/54578494-321e3d80-49bd-11e9-85e8-8dd21f8e66a0.png)
The issue is that when I try to clone a private github repository it appears to be working but simply hangs when it hits 60% completed. I have retried numerous times after quitting the app but it has always been the exact same result.

**Comment by tbodt** [comment]
My guess is your repository contains big files, and iSH is just trying to decompress them. iSH is entirely emulated, so things are 20-50 times slower than they should be.
