### ISSUE TITLE
Feature request: Escape key mapping

### ISSUE THREAD

**Issue by Luavis** [tbodt/ish#354]
Apple's new Smart keyboard folio for iPad does not have ESC key. So some terminal simlation application provide Keyboard key mapping feature. For example, [Blink.sh](https://www.blink.sh/) can config mapping Backquote key to ESC key.

I hope I can use vim easily... and this feature make special keys bar to remove for keyboard users.

**Comment by tbodt** [comment]
We should have this. In the meantime, you can use ctrl-[ for escape.

**Comment by iamrecursion** [comment]
Alternatively you can map caps lock to escape. That's what I've done using the app's built in settings.

**Comment by tbodt** [comment]
Wow I entirely forgot about that. Gonna close the issue now. If you'd like to be able to map some other key to escape, send a pull request.
