### ISSUE TITLE
Running .net core is not working, needs SSE2

### ISSUE THREAD

**Issue by tegaaa** [tbodt/ish#357]
First of all.  I love the initiative!!

I'm trying to get dot net core to run on the emulator but once installed it just puts a big dump of text and doesn't really work

line1: can't create @@8: illegal byte sequence
line1: ELF: not found
Line2: Not found
Line 5: syntax error: unexpected ")"

I just rand dotnet-install.sh from https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script with no parameters.  
It would be nice to be able to run dot net projects in there.
Thanks for you efforts it's really cool.

**Comment by tbodt** [comment]
That would be because you tried to run a 64 bit executable and iSH only supports 32 bit executables.

**Comment by tegaaa** [comment]
Does it work in 32 bits?

**Comment by tbodt** [comment]
Don't know. Probably not, most precompiled binaries are compiled against glibc and that doesn't work as discussed in #355 and #67.

**Comment by tegaaa** [comment]
Ok thanks Théodore. I did use switch auto for the architecture so it should have taken x86 but I can force it and see

**Comment by tegaaa** [comment]
Ok just tried and it detect x64 in iSH and the installer claims that x86 is not supported in there

**Comment by woachk** [comment]
Hi,

.NET Core requires SSE2. Forget about it for now.

Thanks,

**Comment by tegaaa** [comment]
Roger that

________________________________
