### ISSUE TITLE
Lock order inversion between inode_release and fakefs_unlink

### ISSUE THREAD

**Issue by saagarjha** [tbodt/ish#358]
There is a potential deadlock between `inode_release` and `fakefs_unlink` (accessible via simultaneous `fd_close` and `sys_unlink` calls). In particular:

* `inode_release` grabs `inodes_lock`, then can call `fakefs_inode_orphaned` which grabs `mount->lock` via `db_begin`.
* `fakefs_unlink` grabs `mount->lock` via `db_begin`, then calls `path_unlink` which in turn calls `inode_is_orphaned`, which grabs `inodes_lock`.

**Comment by tbodt** [comment]
This should be fixable by moving the call to fakefs_inode_orphaned outside the inodes_lock.

**Comment by saagarjha** [comment]
Would dropping the lock immediately prior to `fakefs_inode_orphaned` be OK? Should this still be performed under `inode->lock`?

**Comment by tbodt** [comment]
The point of inodes_lock is to guarantee no other threads have a pointer to the inode at the point of the free call. So there's no need to lock anything if you do it just before the free call.

**Comment by tbodt** [comment]
To clarify: it's safe to release inodes_lock right after the list_remove call.

**Comment by tbodt** [comment]
Fixed in 21defaa35e83e322ad133b87c698cdb50f30eeed
