### ISSUE TITLE
IPA for self sign

### ISSUE THREAD

**Issue by ecstaticax** [tbodt/ish#365]
Hi, is there an IPA to self sign it? I joined the beta, but I’d like to use the app freely.
This app is really great.

**Comment by tbodt** [comment]
No, but you can build one if you have xcode.

**Comment by ecstaticax** [comment]
I fear it’s very complicated. Perhaps an ipa would be easier for many people...

**Comment by tbodt** [comment]
It's not that complicated. If it's too complicated for you, TestFlight always works.

**Comment by ecstaticax** [comment]
I still tried to self sign the latest version of ipa but it doesn't start.
