### ISSUE TITLE
unable to spawn process (No such file or directory)

### ISSUE THREAD

**Issue by ecstaticax** [tbodt/ish#367]
I've done everything, installed the older pip version, but now xcode gives me this error

**Comment by saagarjha** [comment]
This likely means Xcode can't find one of the build dependencies. Which target failed to build?

**Comment by tbodt** [comment]
Did you install ninja?

If that's not the problem, click the text bubble icon tab on the right of the left sidebar, click the most recent build, and see if you can find more information there.

**Comment by ecstaticax** [comment]
I installed ninja, otherwise I could not have run it after the meson build.

This is the verbose info:

![Schermata 2019-04-17 alle 10 18 39](https://user-images.githubusercontent.com/66459/56272075-452a4780-60fa-11e9-94ef-dd3519b1152a.png)

**Comment by saagarjha** [comment]
What is your path to ninja?

**Comment by ecstaticax** [comment]
![Schermata 2019-04-17 alle 10 18 39](https://user-images.githubusercontent.com/66459/56272281-ab16cf00-60fa-11e9-98af-96ab26ab7246.png)

**Comment by ecstaticax** [comment]
![Schermata 2019-04-17 alle 10 22 47](https://user-images.githubusercontent.com/66459/56272298-b5d16400-60fa-11e9-8244-fc436fe028fd.png)

**Comment by saagarjha** [comment]
I've actually had this issue myself, but I've chalked it up to having ninja in a nonstandard `PATH`. Does cleaning the build folder or restarting Xcode do anything for you?

**Comment by ecstaticax** [comment]
I cleaned with xcode, deleted DerivedData folder, closed and restarted xcode, but the error persists :-(

**Comment by saagarjha** [comment]
What happens if you replace the build tool in the Ninja target to point to /usr/local/bin/ninja?

**Comment by ecstaticax** [comment]
How can I do it?

**Comment by saagarjha** [comment]
It's under "Info" in the Ninja target:

<img width="1392" alt="Screen Shot 2019-04-17 at 01 40 08" src="https://user-images.githubusercontent.com/13786931/56273533-beea1300-60b1-11e9-80e8-8f6dd69eb921.png">

**Comment by ecstaticax** [comment]
Thanks. It worked. But now:

![Schermata 2019-04-17 alle 10 45 51](https://user-images.githubusercontent.com/66459/56273860-ea92ea80-60fd-11e9-846c-f3e4865b4c2b.png)

**Comment by ecstaticax** [comment]
It seems I don't have "parcel"..

**Comment by ecstaticax** [comment]
It did it. I had to put the full parcel path on the script and it worked! 
Thanks for help, you can close.

**Comment by ecstaticax** [comment]
Just a question: i can see the iSH on Files if I use the TestFlight version, while compiling it's not present. Why?

**Comment by nipun3560** [comment]
Hi, I have same issue "unable to spawn process '/usr/bin/make' (No such file or directory)" when I'm going to archive. do you have any solution?

**Comment by Kirito139** [comment]
i have this same problem. i found a tutorial online on how to run python on xcode, i followed the steps but when i try to run my code it says "error: unable to spawn process '/usr/bin/pythonw' (No such file or directory) (in target 'Python' from project 'Python')" is there a way to fix this?
[Python.zip](https://github.com/ish-app/ish/files/8310580/Python.zip)
