### ISSUE TITLE
Inform 7 (interactive fiction)

### ISSUE THREAD

**Issue by ecstaticax** [tbodt/ish#368]
Can someone tell me if Inform 7 works on iSH? I tried to install it with script but obviously it didn't work. I manually unzipped the right files, but when I try to compile a sample file, it doesn't work.

http://inform7.com/download/content/6M62/I7_6M62_Linux_all.tar.gz

**Comment by tbodt** [comment]
What does it do instead of working?

My psychic debugging powers tell me you're probably running into #355.

**Comment by ecstaticax** [comment]
Bad System Call. What can be done?

![IMG_0123](https://user-images.githubusercontent.com/66459/56454129-a34e6900-634c-11e9-8133-7351901a10c5.jpeg)

**Comment by tbodt** [comment]
What does dmesg say?

**Comment by ecstaticax** [comment]
`missing syscall 141`

**Comment by tbodt** [comment]
getdents, that's not too hard to implement

**Comment by ecstaticax** [comment]
Excuse me, can you explain me better? Do I have to install getdents? And then?

**Comment by tbodt** [comment]
No, getdents is a system call that's not implemented in iSH. There's an almost identical system call, getdents64 which is already implemented, so it shouldn't be hard to implement.

**Comment by tbodt** [comment]
No, getdents is a system call that's not implemented in iSH. There's an almost identical system call, getdents64 which is already implemented, so it shouldn't be hard to implement.

**Comment by ecstaticax** [comment]
Ahhhhh, thanks a lot for your reply. You are speaking arab for me. I will patiently wait for getdents to be implemented, if it ever will be. Thanks.

**Comment by tbodt** [comment]
Where did you get the test file?

**Comment by ecstaticax** [comment]
I wrote a simple line:

“House is a room”

It’s enough to run a compile.

**Comment by tbodt** [comment]
Got this particular crash fixed. Note that it happens only after the program has finished running and decides to exit.

**Comment by ecstaticax** [comment]
Yes, it quits but doesn’t compile... do you think it’s a software problem?

**Comment by tbodt** [comment]
Not sure how inform works. What should it be outputting?

**Comment by ecstaticax** [comment]
A .z5 or .z8 file, instead it gives error (bad system call)

**Comment by tbodt** [comment]
Realized I didn't fix the error you reported and instead fixed a different error.

**Comment by tbodt** [comment]
Implemented getdents and it printed this. I assume this means it's working.
```
Inform 7 build 6M62 has started.
++ 0% (Reading text)
I've now read your source text, which is 4 words long.
++ 5% (Analysing sentences)
I've also read Standard Rules by Graham Nelson, which is 42655 words long.
I've also read English Language by Graham Nelson, which is 2297 words long.
++ 15% (Drawing inferences)
++ 20% (Binding rulebooks)
++ 23% (Binding rulebooks)
++ 26% (Binding rulebooks)
++ 29% (Binding rulebooks)
++ 32% (Binding rulebooks)
++ 35% (Binding rulebooks)
++ 38% (Binding rulebooks)
++ 41% (Generating code)
++ 44% (Generating code)
++ 47% (Generating code)
++ 50% (Generating code)
++ 53% (Generating code)
++ 56% (Generating code)
++ 59% (Generating code)
++ 62% (Generating code)
++ 65% (Generating code)
++ 68% (Generating code)
++ 71% (Generating code)
++ 74% (Generating code)
++ 77% (Generating code)
++ 80% (Generating code)
++ 83% (Generating code)
++ 86% (Generating code)
++ 89% (Generating code)
++ 92% (Generating code)
++ 95% (Generating code)
++ 98% (Generating code)
I've also read Basic Help Menu by Emily Short, which is 2368 words long.
I've also read Basic Screen Effects by Emily Short, which is 2218 words long.
I've also read Complex Listing by Emily Short, which is 3410 words long.
I've also read Glulx Entry Points by Emily Short, which is 2682 words long.
I've also read Glulx Image Centering by Emily Short, which is 265 words long.
I've also read Glulx Text Effects by Emily Short, which is 2182 words long.
I've also read Inanimate Listeners by Emily Short, which is 412 words long.
I've also read Locksmith by Emily Short, which is 4122 words long.
I've also read Menus by Emily Short, which is 2001 words long.
I've also read Punctuation Removal by Emily Short, which is 906 words long.
I've also read Skeleton Keys by Emily Short, which is 638 words long.
I've also read Epistemology by Eric Eve, which is 1500 words long.
I've also read Approximate Metric Units by Graham Nelson, which is 6289 words long.
I've also read Metric Units by Graham Nelson, which is 5340 words long.
I've also read Rideable Vehicles by Graham Nelson, which is 1819 words long.
I've also read Unicode Character Names by Graham Nelson, which is 28382 words long.
I've also read Unicode Full Character Names by Graham Nelson, which is 118361 words long.

  The 4-word source text has successfully been translated into an intermediate
    description which can be run through Inform 6 to complete compilation.
    There were 1 room and 1 thing.
++ 100% (Finishing work)
++ Ended: Translation succeeded: 1 room, 1 thing
Inform 7 has finished.
```

**Comment by ecstaticax** [comment]
Now it works! When will you release a new TestFlight?

**Comment by tbodt** [comment]
This weekend probably

**Comment by ecstaticax** [comment]
Great!!!!!
