### ISSUE TITLE
pacman doesn't work

### ISSUE THREAD

**Issue by jusdepatate** [tbodt/ish#369]
Hello,
Today i tried to install Arch Linux on iSH with [tokland's script](https://github.com/tokland/arch-bootstrap),
for this the host OS needs to have a [working `pacman` installation](https://github.com/tokland/arch-bootstrap/blob/master/get-pacman-dependencies.sh).
[Alpine provides `pacman`](https://pkgs.alpinelinux.org/package/v3.4/main/x86/pacman) ([i used this mirrorlist](https://www.archlinux32.org/mirrorlist/?country=all&protocol=http&ip_version=4))
But it seems like it doesn't work on iSH : 
```
Jus-de-Patate :~# pacman -Syu
warning: config file /etc/pacman.d/mirrorlist, line 21: directive 'Server' in section 'options' not recognized.
error: no usable package repositories configured.
```
When I ran [`get-pacman-dependencies.sh`](https://github.com/tokland/arch-bootstrap/blob/master/get-pacman-dependencies.sh) i got another interesting error
```
Jus-de-Patate :~# pacman -Syu
warning: config file /etc/pacman.d/mirrorlist, line 21: directive 'Server' in section 'options' not recognized.
error: No package owns /usr/lib/libalpm.so.10
```

- Idea from [rami3l](https://discordapp.com/channels/508839261924229141/508839261924229143/569069096600207371)
- Test made from an iPhone 6s
- I had to change `/etc/pacman.conf` to make it look at `/etc/pacman.d/mirrorlist`
- Also i know there are problems with [`/proc`](https://github.com/tbodt/ish/issues/145) (which means `chroot` won't work) on iSH but with some luck it may works :D

**Comment by tbodt** [comment]
pacman does work, you just configured it wrong. I ran the arch-bootstrap script, pointed it at the archlinux32.org repositories, and it worked (after a hell of a lot of arch-related fixes).
