### ISSUE TITLE
Error with docker

### ISSUE THREAD

**Issue by josete89** [tbodt/ish#37]
I ran `apk add docker` and I got `Error executing docker-18-06-1.pre-install: script exited with error  127 `
But it seems the install  finish somehow, then when I run it:
`docker                                                                                                                    
This program can only be run on processors with MMX support.`

**Comment by tbodt** [comment]
Docker support is a very long way off, so I'm closing this issue for now.

**Comment by petr-motejlek** [comment]
@tbodt, r we talking Docker Engine support or Docker CLI support? I for one was a bit sad when I first spotted iSH a couple minutes ago, installed it, and literally my first impulse was to check whether Docker CLI works. SSH client and mosh were the second ;).

I understand that Docker Engine support might be beyond any perceivable future, however Docker CLI would be pretty cool.

Cheers

**Comment by tbodt** [comment]
Docker CLI is more within reach, if you have a server to run the Docker Engine on. That would just require a bit more CPU support for running Go programs.

**Comment by petr-motejlek** [comment]
Yup. Well, let's see if anybody else would want this. I guess, if you have a remote Docker Engine to connect to, you will likely just SSH to the box and interact with it that way. But perhaps there's a use case somebody else (other than me) has in mind?

**Comment by chfanghr** [comment]
I run into this issue when I tried to run go toolchain in ish today. I would like to try recompiling go to see if this solves the problem. But first, have anyone solve the issue？

**Comment by tbodt** [comment]
No, this is still a problem, and recompiling go won't work because that requires working go. #57
