### ISSUE TITLE
MySQL needs cmpxchg8b

### ISSUE THREAD

**Issue by SINOPW** [tbodt/ish#372]
unknown ioctl 5413                               
unknown ioctl 5413                               
unknown ioctl 5413                               
unknown ioctl 5413                               
unknown ioctl 5413                               
unknown ioctl 5413                               
unknown ioctl 5413                               
44 illegal instruction at 0x567dddf9: f0 0f c7 0e
 75 e2 8b 44                                     
unknown ioctl 5413

**Comment by tbodt** [comment]
cmpxchg8b

**Comment by tbodt** [comment]
cmpxchg8b has been implemented. No idea if this is fixed yet.

**Comment by tbodt** [comment]
Closing because we now have cmpxchg8b

**Comment by tbodt** [comment]
#597
