### ISSUE TITLE
cannot connect to ssh from same iDevice

### ISSUE THREAD

**Issue by Asmod4n** [tbodt/ish#374]
When trying to connect to the ssh daemon from the iOS device itself all one is getting is operation not permitted, works fine from other devices on the same LAN.
Tried it with 127.0.0.1, ::1 and the IPv4 Adress it got via DHCP.

**Comment by tbodt** [comment]
Are you using split view? It probably won't work if the app is in the background.

**Comment by Asmod4n** [comment]
Tried it with and without, am running iOS 12.2.

**Comment by Asmod4n** [comment]
When i change the Port to something else, like 80, it works.

**Comment by tbodt** [comment]
Only 22 doesn't work? 🤔

**Comment by Asmod4n** [comment]
I tried that port because other iOS Apps from the AppStore use that too. Maybe others won't work either.

**Comment by Asmod4n** [comment]
Guess this could be added as a limitation to the wiki, closing.
