### ISSUE TITLE
Increase maximum size of arguments 

### ISSUE THREAD

**Issue by Asmod4n** [tbodt/ish#375]
What’s the limits of passed arguments to a program? It seams to be rather lowish, like 16?

**Comment by tbodt** [comment]
The limit is 4096 bytes, same as linux.

**Comment by tbodt** [comment]
Just checked and apparently I was wrong, the Linux limit is way more than 4k. Since 2007, it's been a per-argument limit of 128k, with up to 2^31 arguments.

**Comment by Regularcheckm8** [comment]
Haha
