### ISSUE TITLE
Neofetch breaks prompt

### ISSUE THREAD

**Issue by AM6331** [tbodt/ish#378]
If running neofetch, the prompt disappears, I can still write but not run commands, and no prompt
![939A02B7-84B3-4F9D-96F4-B2FFFCE06D6F](https://user-images.githubusercontent.com/41810442/57424762-a7dca380-71cd-11e9-9209-4540a72ff169.png)

**Comment by adrianrocamora** [comment]
Odd, mine seems fine and I just set it up in the last 24 hours

**Comment by tbodt** [comment]
Did you install neofetch with `apk add neofetch`?

**Comment by Mnpn03** [comment]
Seems to work for me when installed with `apk`.

**Comment by AM6331** [comment]
Yes, I will reinstall and try again

**Comment by tbodt** [comment]
Works on my machine
