### ISSUE TITLE
No cursor or other keys on iPad Pro

### ISSUE THREAD

**Issue by mrWheel** [tbodt/ish#379]
hi,

This is a great app. ... but rather useless if I cannot move the cursor around in, f.o. `vi`.

Is there a way to get those extra keys found on most iOS terminal emulators?

**Comment by saagarjha** [comment]
The arrow keys are at the top of the keyboard: they point in four directions and you can swipe on them to move the cursor in that direction. Of course, in `vi` you should also be able to use h, j, k, and l…

**Comment by mrWheel** [comment]
Hi,

Ok, takes some getting used to.
The h,j,k and l keys give strange results in vi.

Four cursor keys would make this more ‘workable’ and intuitive.
Any plans to implement these keys?

Regards,

Willem 

gsm: 0653 - 499 551
www: http://willem.aandewiel.nl/


---
Thank God I'm Atheist

Verstuurd vanaf mijn iPad

**Comment by saagarjha** [comment]
You’re not the first person to express confusion at the arrow keys, so there has been previous discussion on making them more discoverable. I’m not sure that it ever went anywhere, though. 

Also, the directional navigational keys should not be giving strange results in `vi`: if they are, that would probably be a bug.

**Comment by tbodt** [comment]
The unanswered questions are 1) what does the alternative look like and 2) how does it fit on a vertical iPhone 5s.

You can drag and hold the arrow key widget to simulate holding down an arrow.

**Comment by mrWheel** [comment]
The “vi” keys are not set correct. “u” places an “u” under the cursor.

I can not find an “escape” key either .. that’s a bommer in “vi”.

Regards,

Willem 

gsm: 0653 - 499 551
www: http://willem.aandewiel.nl/


---
Thank God I'm Atheist

Verstuurd vanaf mijn iPad

**Comment by saagarjha** [comment]
Escape the is key that looks like ⎋.

**Comment by munsie** [comment]
> I can not find an “escape” key either .. that’s a bommer in “vi”.

As a workaround, you can always use ctrl-[ on pretty much everything that runs vi/vim as a substitution for escape.  I’ve actually gotten into the habit of doing this now because of the lack of a proper escape key on the iPad Pro keyboard and the MacBook Pro touchbar (tapping on glass is not a proper escape key).
