### ISSUE TITLE
can i view the image?

### ISSUE THREAD

**Issue by kno3a87** [tbodt/ish#381]
I wanna view some images, but cannot use some commands; display, eog, imgcat ...
cannot "apk add", too. Can I view the image; .jpg, .png on; on shell?

**Comment by tbodt** [comment]
No, try the files app

**Comment by kno3a87** [comment]
can i download images?

**Comment by saagarjha** [comment]
You may also find some success with a sixel image viewer, such as [this one](https://github.com/hackerb9/lsix).

-

**Comment by tbodt** [comment]
xterm.js doesn't support sixel. Can't you download the images in safari much more easily?

**Comment by kno3a87** [comment]
i wanna download or display the image on the ssh server...

**Comment by tbodt** [comment]
scp it, then.

**Comment by kno3a87** [comment]
i can download it to my home directory using scp, but can't download it on iphone-app, right?

**Comment by tbodt** [comment]
You can then find it in the Files app.

**Comment by kno3a87** [comment]
i find!!!!!!!!!thx!!!!!!!!!!!!♥
