### ISSUE TITLE
halt_system mismatch in arg count

### ISSUE THREAD

**Issue by MatthewMerrill** [tbodt/ish#383]
7a45420 introduces build error when I run `ninja` in build

```
../kernel/exit.c: In function ‘halt_system’:
../kernel/exit.c:124:1: error: number of arguments doesn’t match prototype
 static void halt_system() {
 ^~~~~~
../kernel/exit.c:9:13: error: prototype declaration
 static void halt_system(int status);
             ^~~~~~~~~~~
```

`status` argument [was removed from the halt_system's definition](https://github.com/tbodt/ish/commit/7a45420ac0bd67852f2a898a6f0d565f67d8cbf9#diff-2fab5c2f0efa9b89d9b17cc88d9b37fbL116) but [the prototype still had that argument](https://github.com/tbodt/ish/blob/7a45420ac0bd67852f2a898a6f0d565f67d8cbf9/kernel/exit.c#L9).

Fix could be to remove the argument from the prototype or add it back but ignored?

**Comment by tbodt** [comment]
Fix is to take out the argument. It works on my machine so you'll have to do it.

**Comment by fernandotcl** [comment]
Actually, what you probably want is `halt_system(void)`, which actually means no parameters. `halt_system()` means it takes any combination of parameters.
