### ISSUE TITLE
Enable xtermjs links

### ISSUE THREAD

**Issue by filfat** [tbodt/ish#390]
Clicking on links in the terminal emulator should probably result in the in-app-browser or a user-configurable one (Safari, Chrome, Firefox & Edge).

https://github.com/tbodt/ish/blob/master/app/xtermjs/term.js#L15

**Comment by tbodt** [comment]
Note that I disabled it because it didn't work.

**Comment by uwe-schwarz** [comment]
Could you make a command (like xdg-open or open on MacOS) to open links? Or like in https://github.com/tbodt/ish/issues/192 a /dev/open device?

`echo -e "http://google.com/\nfirefox://open-url?url=https://www.google.com/" > /dev/open`

**Comment by tbodt** [comment]
iSH is now using hterm, which doesn't support automatic links.

**Comment by tbodt** [comment]
Though it does support hyperlinks using escape sequences: https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda
