### ISSUE TITLE
Rtorrent caught illegal instruction.

### ISSUE THREAD

**Issue by jackpal** [tbodt/ish#392]
Reproducible.

1. apk add rtorrent
2. torrent 
3. Press delete key
4. Paste a torrent url like http://releases.ubuntu.com/19.04/ubuntu-19.04-desktop-amd64.iso.torrent
5. Press return key

Result:
                                                                                                               
Caught Illegal instruction, dumping stack:                                                                                                  
Stack dump not enabled.                                                                                                                     
Aborted

**Comment by tbodt** [comment]
Which illegal instruction? Run `dmesg` and paste the output.

**Comment by jackpal** [comment]
$ dmesg                                                                                                                                                                 
unknown ioctl 5600                                                                                                                                                                         
unknown ioctl 5429                                                                                                                                                                         
unknown ioctl 5409                                                                                                                                                                         
unknown ioctl 5422                                                                                                                                                                         
unknown ioctl 5429                                                                                                                                                                         
unknown ioctl 5409                                                                                                                                                                         
unknown ioctl 5422                                                                                                                                                                         
unknown ioctl 5429                                                                                                                                                                         
unknown ioctl 5409                                                                                                                                                                         
unknown ioctl 5422                                                                                                                                                                         
unknown ioctl 5429                                                                                                                                                                         
unknown ioctl 5409                                                                                                                                                                         
unknown ioctl 5422                                                                                                                                                                         
unknown ioctl 5429                                                                                                                                                                         
unknown ioctl 5409                                                                                                                                                                         
unknown ioctl 5422                                                                                                                                                                         
unknown ioctl 5429                                                                                                                                                                         
unknown ioctl 5409                                                                                                                                                                         
18 illegal instruction at 0xf7e111da: f0 0f b0 99 80 00 00 00                                                                                                                              
$

**Comment by tbodt** [comment]
8bit cmpxchg

**Comment by jackpal** [comment]
Is implementing 8bit cmpxchg as simple as adapting the existing cmpxchg implementation to work on a byte? (I'm guessing it's more complicated than that, or you would have made cmpxchg work on all sizes.)

**Comment by tbodt** [comment]
I just did that, but now I'm debugging an issue with racket to make sure it's not related.

**Comment by tbodt** [comment]
rtorrent seems to be working now (at least it got 25% through checking the hash of a torrent)
