### ISSUE TITLE
Chsh doesn't work. 

### ISSUE THREAD

**Issue by saytosid** [tbodt/ish#393]

**Comment by tbodt** [comment]
What did you try to do? What did it do instead of working?

**Comment by saytosid** [comment]
Forry for not providing enough details.

I tried to change my login shell to fish using `chsh`. It returned the following error:
```
# chsh                                                                                  
-ash: chsh: not found                                                                                   
```

It looks like `chsh` is not supported. Considering its a basic command, it would be nice to have it.

**Comment by tbodt** [comment]
Alpine is such a minimal distribution that you have to install it. Try `apk add shadow`. You then have to set a password for some reason with `passwd` before it can work. It's a lot easier to manually edit /etc/passwd.

**Comment by saytosid** [comment]
Ah! Gotcha :) thanks a lot mate

**Comment by rebane2001** [comment]
This is the first Google result, so for those new to alpine - you'll also need to [enable the community repo](https://wiki.alpinelinux.org/wiki/Enable_Community_Repository) to install `shadow`.

**Comment by lucasvazq** [comment]
Just to leave an example, these are the commands that I execute:
```Dockerfile
RUN apk update
RUN apk add shadow
RUN printf "MyPassword\nMyPassword" | passwd
RUN echo "MyPassword" | chsh -s $(which zsh)
```
