### ISSUE TITLE
App will not launch

### ISSUE THREAD

**Issue by joubin** [tbodt/ish#395]
I've been able to run this app on my iPad in the past. I pulled recently and noticed an issue which I've noted #394 

The app simply just crashes. When running with debugger mode, both `*alpineRoot` and `*container` in `AppDelegate:startThings` are `nil`.
[iSH-2019-05-26-220601.txt](https://github.com/tbodt/ish/files/3221938/iSH-2019-05-26-220601.txt)

**Comment by tbodt** [comment]
Did you follow the instructions in the readme to customize ROOT_BUNDLE_IDENTIFIER?

**Comment by tbodt** [comment]
Oh whoops, the instructions say to update the product bundle identifier, not ROOT_BUNDLE_IDENTIFIER. Fixing.

**Comment by joubin** [comment]
Can confirm that fixed it. You may have to clean and rebuild for it to work.
