### ISSUE TITLE
Apache tries to start then crashes

### ISSUE THREAD

**Issue by zoptech** [tbodt/ish#397]
Hi!

I have been trying and investigating on how to run Apache 2 on iSH and I have got to various errors and crashes.

First of all I have installed Apache with `apk add apache2`. I have also installed OpenRC, but this will not work as it says that there isn't a interfaces files, etc... (that's another story).

Then I have managed to start it with `/usr/sbin/httpd -D FOREGROUND`, but instantly the app crashes.

With screen recording and the error.log of Apache this error:
`Invalid argument: AH00076: Failed to enable APR_TCP_DEFER_ACCEPT`
After this message the app crashes.

I have attached the crash log that appears on analytics.

Also to remark, lighttpd works fine, it can be included on the list of things that works. but I would like to have Apache as I wanted to try on working with Apache Modules from my iPad.

Thanks.
[iSH-2019-05-28-202634.ips.txt](https://github.com/tbodt/ish/files/3229179/iSH-2019-05-28-202634.ips.txt)

**Comment by tbodt** [comment]
Thanks for all the information!

**Comment by tbodt** [comment]
MMAP_SHARED AA

**Comment by tbodt** [comment]
and it works.
