### ISSUE TITLE
Consider Same-Arch Emulation Instead

### ISSUE THREAD

**Issue by sr229** [tbodt/ish#399]
I already posted this under my feedback mail but I wanted to log it for everyone.

Alpine already supports ARM in the core - therefore we can just do same-architecture emulation which should have minimal performance impact. This should considerably grant us greater flexibility by using the same architecture the phone uses, rather than emulating x86 ISA.

**Comment by itskenny0** [comment]
I think I remember part of the reason why x86_64 was used being that Apple doesn't want you distributing 'executables' outside of the App Store. I could be wrong though.

**Comment by tbodt** [comment]
That doesn't help. iOS won't let you have memory that's writable and executable.
