### ISSUE TITLE
Problem with ssh-agent

### ISSUE THREAD

**Issue by yohoc** [tbodt/ish#400]
```
iPad:/etc/profile.d# ssh-add -L                                                                                                 
error fetching identities: communication with agent failed  
```

Can’t add ssh key to ssh-agent.

**Comment by tbodt** [comment]
This seems to be because it fails to send things over /dev/log. Closing as it isn't something I can fix on its own.

**Comment by tbodt** [comment]
I was too quick to close. This is an issue and should be tracked, even if it's hard to fix.

**Comment by yifan-w** [comment]
> I was too quick to close. This is an issue and should be tracked, even if it's hard to fix.

Had the same issue. Glad to find out it's reopened. Got any plan to fix it in the foreseeable future?

**Comment by tbodt** [comment]
Actually no, it was just writing an error message on /dev/log: "ssh-agent[13]: error: getpeereid 4 failed: Invalid argument"

**Comment by tbodt** [comment]
ssh agent seems to work now.
