### ISSUE TITLE
Cross-compilation

### ISSUE THREAD

**Issue by chancancode** [tbodt/ish#407]
I meant to ask this in the discord server, but I couldn't due to #406. In any case it's probably a good idea to have an answer for this show up in the issues search.

I was wondering, are there instructions for cross-compiling binaries to run on the iOS environment? When you run, say, `apk add open-ssh`, it fetches pre-built binaries instead of compiling the on-device. How were *those* binaries built? Were they just vanilla i686 builds, or were they originally compiled on-device, or somehow specially cross-compiled from a Mac?

The reason I ask is that, I frequently fail to compile certain packages due to OOM errors. I'm not really sure *why*, since the iPad pro supposedly have 4GB of memory and they would have compiled fine on a physical machine with much less RAM than that. Presumably that is due to a combination of emulation overhead and the "JIT". I was also wondering if getting the 1TB model (6GB RAM) would help – or if there are some other limits at play that would have prevented the extra RAM from being useful here.

In any case, even though the packages may be expensive to *build*, I'm pretty sure they are not nearly as expensive to *run*. Therefore, I was hoping that there is some ways I could cross-compile the needed binaries from a Mac, using Docker or a VM, and then copy those files into the device's file system.

In case it matters, I'm mostly compiling native Ruby extensions (e.g. nokogiri), but learning how to build a vanilla library with the raw tools would be a great start even if you can't provide Ruby-specific help (I can figure that out myself).

**Comment by saagarjha** [comment]
iSH runs vanilla Linux ELF binaries, albeit compiled for Alpine Linux's musl instead of your typical glibc. These binaries come from [x86 packages](https://pkgs.alpinelinux.org/packages?name=&branch=edge&arch=x86) that Alpine builds. If you're looking to compile your own binaries, grab an Alpine image and build whatever you'd like and copy them over to your iPad: ideally they should run without modification.

**Comment by tbodt** [comment]
About memory usage, I haven't done a huge amount to reduce the memory usage, so there are probably a lot of leaks. But how do you know it's out of memory? What sort of error do you get?

**Comment by tbodt** [comment]
I just fixed the one really big memory leak, the fix will be pushed this weekend.

**Comment by tbodt** [comment]
I just fixed the one really big memory leak, the fix will be pushed this weekend.
