### ISSUE TITLE
SSH port forwarding not working

### ISSUE THREAD

**Issue by thomashw** [tbodt/ish#408]
Using ssh to port forward is not working. The ssh connection succeeds but the port forward does not. For example, if the service running on the remote system is a web server, attempting to load the remote web page using the forwarded port will time out. The same scenario using a different device (a laptop, for example) succeeds.

Sample commands for a remote web server listening on port 55000:
`ssh -L 55000:localhost:55000 <remote_ip_address>`
`ssh -L 55000:127.0.0.1:55000 <remote_ip_address>`

**Comment by okwme** [comment]
this worked for me but i had to keep the app open witha split screen. as soon as it was in the background the process stopped

**Comment by tbodt** [comment]
@thomashw let me know if you can still reproduce after keeping the app open in split screen.

**Comment by thomashw** [comment]
@tbodt I'm using the app on an iPhone so split screen isn't an option.

**Comment by tbodt** [comment]
I see. Eventually (not sure when) I'll find some other way to keep the app open in the background.

**Comment by felipenv** [comment]
I tried with split screen in iPad Pro and still doesn’t work for me. Any other option?

**Comment by jhollowayj** [comment]
Keeping it running the background might be possible following [this wiki](https://github.com/ish-app/ish/wiki/Running-in-background) post

```
cat /dev/location > /dev/null & 
```
`killall -9 cat` # will stop it, and all other jobs running `cat`.
