### ISSUE TITLE
When running a php program called PocketMine-MP it outputs a “Bad system call” error

### ISSUE THREAD

**Issue by MFDGaming** [tbodt/ish#414]
i used the php 7.0.x binary from pmmp (i686)

**Comment by tbodt** [comment]
Which bad system call? Please read the issue template.

**Comment by MFDGaming** [comment]
unknown ioctl 5600                                            
unknown ioctl 5422                                            
unknown ioctl 5429                                            
unknown ioctl 5409                                            
unknown ioctl 5429                                            
unknown ioctl 5409                                            
unknown ioctl 5422                                            
unknown ioctl 5429                                            
unknown ioctl 5409                                            
unknown ioctl 5422                                            
unknown ioctl 5429                                            
unknown ioctl 5409                                            
unknown ioctl 5422                                            
unknown ioctl 5429                                            
unknown ioctl 5409                                            
unknown ioctl 5422                                            
unknown ioctl 5429                                            
unknown ioctl 5409                                            
unknown ioctl 5401                                            
unknown ioctl 5401                                            
18 missing syscall 144                                        
unknown ioctl 5413                                            
unknown ioctl 5413                                            
unknown ioctl 5413                                            
unknown ioctl 5401                                            
unknown ioctl 5401                                            
unknown ioctl 5401                                            
37 missing syscall 55

**Comment by tbodt** [comment]
msync and 32-bit fcntl, doesn't seem too hard. What's pmmp?

**Comment by MFDGaming** [comment]
Minecraft pocket edition server software server software

**Comment by tbodt** [comment]
Can you link to where you got the php binary?

**Comment by MFDGaming** [comment]
Ok

**Comment by MFDGaming** [comment]
Let me upload it

**Comment by MFDGaming** [comment]
https://drive.google.com/file/d/10380bmF8w9EZ7Q1QF3scXuppcby1P0hQ/view?usp=drivesdk

**Comment by tbodt** [comment]
Where did you download it from though?

**Comment by MFDGaming** [comment]
Sorry wrong file

**Comment by MFDGaming** [comment]
https://cdn.discordapp.com/attachments/577523636722728970/593049888158253106/i686.tar.xz

**Comment by MFDGaming** [comment]
I found it in the pocketserver apk

**Comment by MFDGaming** [comment]
Can you fix it?

**Comment by MFDGaming** [comment]
@tbodt

**Comment by tbodt** [comment]
@MFDGaming which version of pmmp are you running?

**Comment by tbodt** [comment]
Tried to run PocketMine-MP_1.6.2dev-562_2c6205e3_API-3.0.0-ALPHA7.phar and after fixing a few things got
```
[23:05:22] [Server thread/CRITICAL]: Running PocketMine-MP with 32-bit systems/PHP is no longer supported. Please upgrade to a 64-bit system or use a 64-bit PHP binary.
```
That's not something I can really fix so I'll move on now.
