### ISSUE TITLE
[Help wanted] Can't scroll on iOS 13

### ISSUE THREAD

**Issue by tbodt** [tbodt/ish#417]

**Comment by Mnpn03** [comment]
If it’s also supposed to be scrollable on iPhone, that too seems to be broken in iOS 13.

**Comment by jusdepatate** [comment]
Can reproduce on iOS13 Dev. Build 2 on an iPhone 6s

**Comment by dcordero** [comment]
Can reproduce on iOS13 Dev. Build 3 on an iPad Pro 10.5-inch

**Comment by Ragingninja22** [comment]
Can reproduce on iOS Dev Build 3. iPhone XR

**Comment by G3bE** [comment]
Can reproduce. iOS 13 Public beta 2, iPhone 8 Plus

**Comment by tbodt** [comment]
It turns out to fix this I essentially have to either reimplement scrolling from first principles or reimplement text selection from first principles. I don't have time to deal with this, so any help would be appreciated.

**Comment by leeramsay** [comment]
FYI all, there is a workaround at the moment, I just tested on iPad and iPhone, on iOS/iPadOS 13 beta 4, you can scroll using an invisible scroll bar located roughly here:

![image](https://user-images.githubusercontent.com/965319/61679413-b9e3d200-ad38-11e9-9640-43c2c6b667e6.jpeg)

Props to maskeda on discord for discovering.

**Comment by A-Human-Person** [comment]
cannot even use it on iphone xr 13.0 (17A5572a)

just white screen

will try to reinstal

**Comment by A-Human-Person** [comment]
nevermind it works now and scrolling is broken like said in the issue

**Comment by tbodt** [comment]
Got this working on master.
