### ISSUE TITLE
Failure to build ish

### ISSUE THREAD

**Issue by leonchas17** [tbodt/ish#419]
Hi there,

When trying to build ninja I´m getting the following warnings and failure messages:

Selenes-iMac:build leon$ ninja
[2/80] Compiling C object 'float80_test@exe/emu_float80.c.o'.
../emu/float80.c:336:32: warning: missing field '' initializer [-Wmissing-field-initializers]
            return (float80) {0};
                               ^
../emu/float80.c:396:25: warning: missing field '' initializer [-Wmissing-field-initializers]
        f = (float80) {0};
                        ^
2 warnings generated.
[20/80] Compiling C object 'ish@sta/kernel_uname.c.o'.
../kernel/uname.c:73:30: warning: missing field 'loads' initializer [-Wmissing-field-initializers]
    struct sys_info info = {0};
                             ^
1 warning generated.
[21/80] Compiling C object 'ish@sta/kernel_getset.c.o'.
../kernel/getset.c:165:25: warning: unused parameter 'header_addr' [-Wunused-parameter]
int_t sys_capget(addr_t header_addr, addr_t data_addr) {
                        ^
../kernel/getset.c:165:45: warning: unused parameter 'data_addr' [-Wunused-parameter]
int_t sys_capget(addr_t header_addr, addr_t data_addr) {
                                            ^
../kernel/getset.c:169:25: warning: unused parameter 'header_addr' [-Wunused-parameter]
int_t sys_capset(addr_t header_addr, addr_t data_addr) {
                        ^
../kernel/getset.c:169:45: warning: unused parameter 'data_addr' [-Wunused-parameter]
int_t sys_capset(addr_t header_addr, addr_t data_addr) {
                                            ^
4 warnings generated.
[23/80] Compiling C object 'ish@sta/kernel_futex.c.o'.
../kernel/futex.c:101:33: warning: missing field 'tv_nsec' initializer [-Wmissing-field-initializers]
    struct timespec timeout = {0};
                                ^
../kernel/futex.c:97:89: warning: unused parameter 'uaddr2' [-Wunused-parameter]
dword_t sys_futex(addr_t uaddr, dword_t op, dword_t val, addr_t timeout_or_val2, addr_t uaddr2, dword_t val3) {
                                                                                        ^
../kernel/futex.c:97:105: warning: unused parameter 'val3' [-Wunused-parameter]
dword_t sys_futex(addr_t uaddr, dword_t op, dword_t val, addr_t timeout_or_val2, addr_t uaddr2, dword_t val3) {
                                                                                                        ^
3 warnings generated.
[26/80] Compiling C object 'ish@sta/kernel_misc.c.o'.
../kernel/misc.c:16:28: warning: unused parameter 'code' [-Wunused-parameter]
int_t sys_arch_prctl(int_t code, addr_t addr) {
                           ^
../kernel/misc.c:16:41: warning: unused parameter 'addr' [-Wunused-parameter]
int_t sys_arch_prctl(int_t code, addr_t addr) {
                                        ^
2 warnings generated.
[30/80] Compiling C object 'ish@sta/kernel_resource.c.o'.
../kernel/resource.c:213:29: warning: unused parameter 'which' [-Wunused-parameter]
int_t sys_getpriority(int_t which, pid_t_ who) {
                            ^
../kernel/resource.c:213:43: warning: unused parameter 'who' [-Wunused-parameter]
int_t sys_getpriority(int_t which, pid_t_ who) {
                                          ^
../kernel/resource.c:217:29: warning: unused parameter 'which' [-Wunused-parameter]
int_t sys_setpriority(int_t which, pid_t_ who, int_t prio) {
                            ^
../kernel/resource.c:217:43: warning: unused parameter 'who' [-Wunused-parameter]
int_t sys_setpriority(int_t which, pid_t_ who, int_t prio) {
                                          ^
../kernel/resource.c:217:54: warning: unused parameter 'prio' [-Wunused-parameter]
int_t sys_setpriority(int_t which, pid_t_ who, int_t prio) {
                                                     ^
5 warnings generated.
[32/80] Compiling C object 'ish@sta/fs_mount.c.o'.
../fs/mount.c:103:98: warning: unused parameter 'data_addr' [-Wunused-parameter]
dword_t sys_mount(addr_t source_addr, addr_t point_addr, addr_t type_addr, dword_t flags, addr_t data_addr) {
                                                                                                 ^
1 warning generated.
[33/80] Compiling C object 'ish@sta/kernel_fs.c.o'.
../kernel/fs.c:31:74: warning: unused parameter 'flags' [-Wunused-parameter]
dword_t sys_faccessat(fd_t at_f, addr_t path_addr, mode_t_ mode, dword_t flags) {
                                                                         ^
1 warning generated.
[39/80] Compiling C object 'ish@sta/fs_real.c.o'.
../fs/real.c:361:15: warning: implicit declaration of function 'utimensat' is invalid in C99 [-Wimplicit-function-declaration]
    int err = utimensat(mount->root_fd, fix_path(path), times, 0);
              ^
1 warning generated.
[43/80] Compiling C object 'ish@sta/fs_proc.c.o'.
../fs/proc.c:144:20: warning: comparison of unsigned expression < 0 is always false [-Wtautological-compare]
    if (fd->offset < 0) {
        ~~~~~~~~~~ ^ ~
1 warning generated.
[51/80] Compiling C object 'ish@sta/fs_sock.c.o'.
../fs/sock.c:577:26: warning: comparison of integers of different signs: 'size_t' (aka 'unsigned long') and 'int' [-Wsign-compare]
    for (size_t i = 0; i < msg.msg_iovlen; i++) {
                       ~ ^ ~~~~~~~~~~~~~~
../fs/sock.c:611:26: warning: comparison of integers of different signs: 'size_t' (aka 'unsigned long') and 'int' [-Wsign-compare]
    for (size_t i = 0; i < msg.msg_iovlen; i++)
                       ~ ^ ~~~~~~~~~~~~~~
../fs/sock.c:653:26: warning: comparison of integers of different signs: 'size_t' (aka 'unsigned long') and 'int' [-Wsign-compare]
    for (size_t i = 0; i < msg.msg_iovlen; i++) {
                       ~ ^ ~~~~~~~~~~~~~~
../fs/sock.c:666:26: warning: comparison of integers of different signs: 'size_t' (aka 'unsigned long') and 'int' [-Wsign-compare]
    for (size_t i = 0; i < msg.msg_iovlen; i++) {
                       ~ ^ ~~~~~~~~~~~~~~
4 warnings generated.
[67/80] Compiling C object 'ish@sta/emu_float80.c.o'.
../emu/float80.c:336:32: warning: missing field '' initializer [-Wmissing-field-initializers]
            return (float80) {0};
                               ^
../emu/float80.c:396:25: warning: missing field '' initializer [-Wmissing-field-initializers]
        f = (float80) {0};
                        ^
2 warnings generated.
[80/80] Linking target ish.
FAILED: ish 
cc  -o ish 'ish@exe/main.c.o' -Wl,-dead_strip_dylibs -Wl,-headerpad_max_install_names libish.a -lm -lsqlite3 -Wl,-headerpad_max_install_names -Wl,-rpath,@loader_path/  
Undefined symbols for architecture x86_64:
  "_utimensat", referenced from:
      _realfs_utime in libish.a(fs_real.c.o)
     (maybe you meant: _sys_utimensat)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

So, no ish. Any ideas?

This is happening on an iMac retina 5k 2017,  with macOS Sierra 10.12.6. With Python 3.7.3 running under pyenv . For the record, I´m trying to generate iSH for an iPod touch  with iOS 9.3.5, using Xcode 9.2  Eventually I´d like to do the same thing with an old iPhone 4 running iOS 7.1.2 using Xcode 7.3.1, but first things first, let´s build that fish.


Leon

<!--
If you're reporting a crash, please include a crash dump. You can find them in Settings -> Privacy -> Analytics -> Analytics Data on iOS 12, or Settings -> Privacy -> Diagnostics and Usage on iOS 11.
If this is a "Bad system call", "Illegal instruction", or "Segmentation fault", run `dmesg` to get a dump of the log messages and include the relevant output.
-->

**Comment by tbodt** [comment]
iSH is right now only compatible with iOS 11, hence the utimensat linker error.
