### ISSUE TITLE
ssh

### ISSUE THREAD

**Issue by Jon-Schneider** [tbodt/ish#42]
Attempting to ssh into a server fails with:
```bash
fcntl(3, F_GETFL): Invalid argument
Host key verification failed.
```

**Comment by tbodt** [comment]
ssh is [on the list](https://github.com/tbodt/ish/projects/7).

**Comment by TrashcanCoder** [comment]
And sshd seems to work:
apk install openssh , Generate host Keys, change sshd server  port, /usr/sbin/sshd

Connection refused ;(

**Comment by smhdale** [comment]
@owah It looks like SSH is having trouble populating the `~/.ssh/known_hosts` file.

Try running `ssh -o StrictHostKeyChecking=no [user]@[ip] uptime` - that seems to force SSH to save host identities, and fixed the `Host key verification failed` error for me.

I still can’t actually SSH in yet - the app crashes and (sometimes?) ruins my `~/.ssh` folder when I try.

**Comment by ekloster** [comment]
Would be great if ssh-agent was working (after ssh, I’m still having host key issues).

iPad:~# ssh-agent                                                                                                                                                                 
unix_listener: cannot bind to path /tmp/ssh-W9yyR5vG4IJ8/agent.3: No such file or directory

**Comment by smhdale** [comment]
@owah yep I was using an identity file. No luck yet but hopefully this will work soon!

**Comment by tbodt** [comment]
ssh now gets right up to the point where it starts communication and then dies with the message `TODO select with multiple fds`

**Comment by tbodt** [comment]
it uh. WORKS
