### ISSUE TITLE
Extra software keys above keyboard don’t work (iPadOS 13)

### ISSUE THREAD

**Issue by jack-the-coder** [tbodt/ish#420]
The buttons don’t do anything at all. The main software keyboard underneath still works fine. I’m using iPadOS 13.0 (17A5522g / beta 3).

**Comment by tbodt** [comment]
Can't reproduce (beta 4)

**Comment by jack-the-coder** [comment]
I just upgraded (to beta 4) and found that the app starts but no longer displays any text in the console above the keyboard. The buttons above the keyboard also do not become darker when tapped as if to indicate that they were pressed.

I’m beginning to think that this is an issue that only manifests in fresh installs as opposed to upgrades from a previous version, based on the fact that it works fine for you.

If you’d like any more information (like a TestFlight feedback report), I’d be happy to help!

On Jul 20, 2019, at 8:50 PM, Theodore Dubois <notifications@github.com<mailto:notifications@github.com>> wrote:


Can't reproduce (beta 4)

**Comment by tbodt** [comment]
There will be an update later today that fixes the blank screen.
