### ISSUE TITLE
ffmpeg mp3 needs pushal

### ISSUE THREAD

**Issue by VincentCCandela** [tbodt/ish#423]
When running 

ffmpeg -i "$
f" -codec:v copy -codec:a libmp3lame -q:a 2 "${f%.webm}.mp3"

I get:

ffmpeg version 4.0.2 Copyright (c) 2000-2018 the FFmpeg developers                  
  built with gcc 8.2.0 (Alpine 8.2.0)                                               
  configuration: --prefix=/usr --enable-avresample --enable-avfilter --enable-gnutls
 --enable-gpl --enable-libass --enable-libmp3lame --enable-libvorbis --enable-libvpx
 --enable-libxvid --enable-libx264 --enable-libx265 --enable-libtheora --enable-libv
4l2 --enable-postproc --enable-pic --enable-pthreads --enable-shared --enable-libxcb
 --disable-stripping --disable-static --disable-librtmp --enable-vaapi --enable-vdpa
u --enable-libopus --disable-asm --disable-debug                                    
  libavutil      56. 14.100 / 56. 14.100                                            
  libavcodec     58. 18.100 / 58. 18.100                                            
  libavformat    58. 12.100 / 58. 12.100                                            
  libavdevice    58.  3.100 / 58.  3.100                                            
  libavfilter     7. 16.100 /  7. 16.100                                            
  libavresample   4.  0.  0 /  4.  0.  0                                            
  libswscale      5.  1.100 /  5.  1.100                                            
  libswresample   3.  1.100 /  3.  1.100                                            
  libpostproc    55.  1.100 / 55.  1.100                                            
Input #0, matroska,webm, from 'lit.webm':                                           
  Metadata:                                                                         
    encoder         : google/video-file                                             
  Duration: 00:03:13.59, start: 0.000000, bitrate: 149 kb/s                         
    Stream #0:0(eng): Audio: vorbis, 44100 Hz, stereo, fltp (default)               
File 'lit.mp3' already exists. Overwrite ? [y/N] y                                  
Stream mapping:                                                                     
  Stream #0:0 -> #0:0 (vorbis (native) -> mp3 (libmp3lame))                         
Press [q] to stop, [?] for help                                                     
/root/.local/bin/music_converter: line 6:    15 Illegal instruction     ffmpeg -i "$
f" -codec:v copy -codec:a libmp3lame -q:a 2 "${f%.webm}.mp3"

Dmesg returns:

unknown ioctl 5600                                                                  
unknown ioctl 5422                                                                  
unknown ioctl 5429                                                                  
unknown ioctl 5409                                                                  
unknown ioctl 5422                                                                  
unknown ioctl 5429                                                                  
unknown ioctl 5429                                                                  
unknown ioctl 5409                                                                  
unknown ioctl 5409                                                                  
unknown ioctl 5422                                                                  
unknown ioctl 5429                                                                  
unknown ioctl 5409                                                                  
unknown ioctl 5422                                                                  
unknown ioctl 5429                                                                  
unknown ioctl 5422                                                                  
unknown ioctl 5429                                                                  
unknown ioctl 5409                                                                  
unknown ioctl 5409                                                                  
unknown ioctl 5413                                                                  
15 illegal instruction at 0xf5ef7a8b: 60 e8 9f ff ff ff 74 22

**Comment by tbodt** [comment]
pushal

**Comment by obisims** [comment]
Can reproduce, iPhone 7 (NN8X2ZP/A), 12.3.1


Here's what dmesg returns- although I'm not the most familiar with it

```
""
unknown ioctl 5413                                
23 illegal instruction at 0xf59f203b: 60 e8 9f ff ff ff 74 22
```
