### ISSUE TITLE
Blank screen on iPadOS beta 4

### ISSUE THREAD

**Issue by Schr3da** [tbodt/ish#428]
Unfortunately the app launches in a black screen and does not show up on ipados beta 4 .

**Comment by fishcharlie** [comment]
It looks like iOS 13 beta 4 also has this issue running on my iPhone (not just iPadOS).

**Comment by helmut72** [comment]
Same for me. Same for Blink Shell (but Testflight is coming next hours).

**Comment by lorenzodla** [comment]
I have made a Pull Request solving the problem :)

**Comment by Mnpn03** [comment]
#431

**Comment by tbodt** [comment]
Fixed by #431
