### ISSUE TITLE
Alt key  on external keyboard not acting as meta 

### ISSUE THREAD

**Issue by MasonProtter** [tbodt/ish#432]
I’m using an ipad pro with an external keyboard and `Alt` seems to not be used as `meta` in ish whereas other apps seem to get this right. ie. pressing `alt-x` produces `≈` instead of sending `meta-x`.

**Comment by tbodt** [comment]
option-x produces ≈ in the english keyboard layout. In some languages there's no way to type accented characters without option key combinations, so I'm not going to change the default functionality of the option key.

**Comment by MasonProtter** [comment]
Could this issue at least be open for if someone feels like implementing it as an option? There are other ways to input characters like  `≈` that don't make external keyboards almost completely useless for the app.

**Comment by tbodt** [comment]
I probably shouldn't have closed this. It would make sense to have a setting to change the alt key behavior between typing special characters and pressing meta.
