### ISSUE TITLE
Unable to load Spacemacs

### ISSUE THREAD

**Issue by msanders** [tbodt/ish#433]
![IMG_0006](https://user-images.githubusercontent.com/54970/61549981-ef3ea600-aa40-11e9-9e66-80063d842bb5.png)

To reproduce:

```sh
git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d

# Necessary so start page renders correctly.
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

emacs
```

Then press enter three times to choose the defaults.

**Comment by tdegrunt** [comment]
Sounds a lot like this:
https://github.com/syl20bnr/spacemacs/issues/8341

**Comment by tbodt** [comment]
@tdegrunt Looks completely different to me.

**Comment by tbodt** [comment]
Fixed in master
