### ISSUE TITLE
Please put a new release in TestFlight (for iOS 13b4)

### ISSUE THREAD

**Issue by Styden** [tbodt/ish#434]
Please, could you put a new release of ish for iOS 13b4 ? I’ve been trying to build it myself and install the ipa with my certificates (paid one, not 7 days provided by apple) but it crashes at launch. The only way to get it work for me is going through TestFlight.

**Comment by tbodt** [comment]
There will be a new build today (PDT).

*tbodt closed this task out of spite.*
