### ISSUE TITLE
iOS 13 multi window support

### ISSUE THREAD

**Issue by tbodt** [tbodt/ish#435]
User feedback:
> It would be cool if you could have multiple instances of iSH open using iPad’s splitscreen/multitasking/slideover functionalities.

**Comment by Mnpn03** [comment]
Has this been resolved by #545?

**Comment by tbodt** [comment]
Yeah why isn't this closed

**Comment by rluvaton** [comment]
Great work!
Is it possible to do it on iPhone?

**Comment by kkk669** [comment]
@rluvaton No. It's exclusive for iPadOS.
