### ISSUE TITLE
tmux has problems with split panes

### ISSUE THREAD

**Issue by tbodt** [tbodt/ish#437]
User feedback on crash:
> Installed tmux, split horizontally via Ctrl+b % - then iSH got stuck and crashed shortly later.

**Comment by tbodt** [comment]
@chrizel

**Comment by leeramsay** [comment]
I don’t use tmux but can replicate.

Open tmux, run the ‘make two panes split horizontally’ command above, sometimes my panes are healthy for a little while, but then either:

* The pane you have highlighted will ‘freeze’,
* The whole iSH app locks up.

iPadOS 13 beta 4, build 53

**Comment by tbodt** [comment]
Fixed in master.
