### ISSUE TITLE
YouTube-DL issue with iOS 13

### ISSUE THREAD

**Issue by BrammyH** [tbodt/ish#442]
When I run YouTube-dl on iOS 13 (iPadOS) I get the following error: ERROR: S58B_UN16FY: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the late
st version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.       

I can DL the video fine on my iPhone running iOS 12. I uninstalled and reinstalled on iPad to make sure I was getting the latest version.

**Comment by Mnpn03** [comment]
I cannot replicate this on iOS 13 Public Beta 3 with iSH build 53, not even with the same video. How have you installed youtube-dl, and what version are you running? (apk/pip, `youtube-dl --version`)
Mine's installed through Pip, using `pip3 install youtube-dl` from packages `python3` and `py3-pip`, I'm running version 2019.07.16.

This does sound similar to an issue with youtube-dl itself (commonly reported from outdated versions), and making sure you're on the latest version should help.

**Comment by BrammyH** [comment]
Huh, this is weird. It is a version issue. On my iPad apk grabs 2018.06.25 but my iPhone gets the latest. Ok, we can close this issue. Sorry.

**Comment by tbodt** [comment]
You can update your youtube-dl on your ipad by upgrading your system: edit /etc/apk/repositories, change the version number to the latest (3.10), and apk upgrade.

**Comment by CyberWarrior101** [comment]
I have error with "apk not found"

**Comment by saagarjha** [comment]
I have no idea how you picked this specific issue to comment on…however, the version of iSH on the App Store has had package management functionality removed. The ability to run Linux programs, as well as import files, has not been changed.

**Comment by CyberWarrior101** [comment]
Я запускал через TestFlight

**Comment by saagarjha** [comment]
This applies to recent versions on TestFlight as well.

**Comment by CyberWarrior101** [comment]
откуда скачивать полноценно-рабочий ISH ?

**Comment by saagarjha** [comment]
I would hesitate to call it "full-fledged", but you can download build 76 (the last build with a package manager) [here](https://github.com/ish-app/ish/releases/tag/builds%2F76).
