### ISSUE TITLE
zsh with oh-my-zsh hangs up with ish (53)

### ISSUE THREAD

**Issue by moldabekov** [tbodt/ish#443]
Device: iPad Pro 11
OS: iOS 12.3.1
iSH version: 1.0 (53)
—

I run ish with default oh-my-zsh installation. On iSH 1.0(52) it were running smoothly. 
With latest update it just shows MOTD and doesn’t react to any escape sequence (such as ctrl+c, ctrl+d, ctrl+z, ctrl+[).

This issue looks like #438, but default zsh at least gives you a prompt.

**Comment by stek29** [comment]
It's the same issue -- zsh getting stuck waiting for SIGCHLD.
