### ISSUE TITLE
testflight shows This beta is full

### ISSUE THREAD

**Issue by contrun** [tbodt/ish#444]
Any other way for distribution?

**Comment by G3bE** [comment]
You can try to build the app yourself and copy it onto your iPhone/iPad/iPod via a USB-cable. Simply select your iPhone as a target in the upper left corner next to the build button. This works without the need to have a paid developer account.

**Comment by contrun** [comment]
The blocking issue is that I do not have a macbook!

**Comment by ogslimtony** [comment]
Ya still

**Comment by tbodt** [comment]
https://twitter.com/iSH_app/status/1154791959350767617
