### ISSUE TITLE
dig is broken

### ISSUE THREAD

**Issue by Spydar007** [tbodt/ish#455]
`dig` appears broken in the latest build.

I get: `Bad system call`.

dmesg reports `missing syscall 241`.

Latest iOS 13 developer beta if it makes any difference

**Comment by stek29** [comment]
`sched_setaffinity`

**Comment by uwe-schwarz** [comment]
nslookup and host have the same problem (Bad system call, missing syscall 241).

**Comment by tbodt** [comment]
Fixed in master.
