### ISSUE TITLE
Hello for it

### ISSUE THREAD

**Issue by H7777xx** [tbodt/ish#456]
<!-
If you're reporting a crash, please include a crash dump. You can find them in Settings -> Privacy -> Analytics -> Analytics Data on iOS 12, or Settings -> Privacy -> Diagnostics and Usage on iOS 11.
If this is a "Bad system call", "Illegal instruction", or "Segmentation fault", run `dmesg` to get a dump of the log messages and include the relevant output.
-->

**Comment by Rexogamer** [comment]
Don’t spam
