### ISSUE TITLE
TMUX does not work

### ISSUE THREAD

**Issue by ghanan94** [tbodt/ish#46]
Trying to run tmux results in a ‘Bad system call’ error

\# apk add tmux 
...
\# tmux
Bad system call
\#

**Comment by saptarshiguha** [comment]
now it crashes the app

**Comment by mrbrutti** [comment]
It no longer crashes the app or returns bad system call. The current message is
```
bad server
```

**Comment by tbodt** [comment]
The issue now is missing sendmsg and recvmsg, which I've been holding off on because they the most complicated parameter passing of any system call. I think @wallisch said he was working on recvmsg?

**Comment by wallisch** [comment]
Yes, I started working on them both. Going to take a bit, since - as you said - correctly copying the msghdr struct from/to userspace is a pain in the ass.

**Comment by scottstanfield** [comment]
I will happily test tmux when closed. Watching this thread.

**Comment by tbodt** [comment]
tmux is working now 🎉
