### ISSUE TITLE
Mono requires /proc to be mounted

### ISSUE THREAD

**Issue by hggz** [tbodt/ish#461]
Attempting to use mono / csharp after installing it returns with an error:

```
Mono requires /proc to be mounted
```

I was able to install mono with the following commands:

```
apk add --no-cache mono --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing && \
    apk add --no-cache --virtual=.build-dependencies ca-certificates && \
    cert-sync /etc/ssl/certs/ca-certificates.crt && \
    apk del .build-dependencies
```

If you run into an exception after installing it saying that it can't resolve the symbol 'get random' install a supported version of musl:

```
apk add --no-cache musl\>1.1.20 --repository http://dl-cdn.alpinelinux.org/alpine/edge/main
```

It would be great to get mono working on this. This is turning out to be the full dev sandbox environment I could ever need.

**Comment by tbodt** [comment]
It prints this after failing to find /proc/self/maps. The JVM also needs it.

https://github.com/mono/mono/blob/3c92cd8c94c027b7c9215a12044345106851262b/mono/mini/mini-runtime.c#L4084

**Comment by hggz** [comment]
Just circling back on this, without any rush of course (been tracking updates to the platform and love the work being done), but is there a way to mount /proc properly so it behaves with mono / jvm yet?

**Comment by tbodt** [comment]
No

**Comment by tbodt** [comment]
Mono is working much better now.

**Comment by hggz** [comment]
You're the man
