### ISSUE TITLE
zsh hangs when you hit C^C

### ISSUE THREAD

**Issue by idvorkin** [tbodt/ish#462]
Using zsh, when I hit C-C the system hangs.  I tend to use tmux, so need to kill the pane.  How can I help debug?

**Comment by tbodt** [comment]
Does this happen when you're not using tmux?

**Comment by idvorkin** [comment]
Yes. It freezes w/o tmux as well. Happy to help debugging. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tbodt** [comment]
It's possible this is fixed in master. I'll test and push a new build this weekend.

**Comment by idvorkin** [comment]
*Not sure where the right place to ask such questions is* 

BTW @tbodt ish is a super cool program. How did you come up  with the idea of it? How did you get the ASM chops? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by idvorkin** [comment]
Howdy! Any updates on when this’ll get pushed out? 


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tbodt** [comment]
Hello, I've been busy the past couple of weeks but I'm going to be working on it this weekend.

Re https://github.com/tbodt/ish/issues/462#issuecomment-522323683: mostly from reading books. The best place to ask questions like that is twitter or discord.

**Comment by tbodt** [comment]
Just confirmed that this works on master, new build will be pushed this weekend.

**Comment by idvorkin** [comment]
Hooray! Thanks for the new release @ tbodt 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
