### ISSUE TITLE
The shell - fish is not working

### ISSUE THREAD

**Issue by Nanoc-ice** [tbodt/ish#463]
After successfully adding the shell fish and then running it, it hangs ish with no way to Ctrl-c out of it.  Have to restart ish altogether.  This looks like the same issue reported previously that may have been broken on a new build.

**Comment by kkk669** [comment]
Same here. I'm using iSH 1.0 (55) on iPadOS 13 Developer Beta 8.

Run `fish` -> ❌
Run `exec fish` -> ❌
Run `echo 'fish; exit $?' >> ~/.profile` and restart the shell -> ❌
Change my login shell to fish by modifying /etc/passwd-> ❌

**Comment by A-Human-Person** [comment]
not a solution, but if anyone wants an alternative try YASH, it has all the same features except some completions missing and is much lighter and posix.

**Comment by A-Human-Person** [comment]
apk add ncurses-dev ncurses-terminfo gcc gcc-makedeps git

git clone https://github.com/magicant/yash
cd yash
./configure
make
make install

**Comment by tbodt** [comment]
Looks like this is something that changed in a fish update. It works on master now.
