### ISSUE TITLE
Compiling large projects can result in iSH crashing

### ISSUE THREAD

**Issue by tbodt** [tbodt/ish#464]
The crashes generally seem to be out of memory conditions.

**Comment by k16blfurm** [comment]
Honestly, if this is fixed you could fix a lot of the issues with memory leakage and incompatibility. I’m not sure how you’d do it or how hard it is but I’m looking forward to it lol.

**Comment by tbodt** [comment]
I think this is fixed now, I just ./configure'd python and the memory usage never went over 75MB (it used to just keep going up until it reached something like 300MB.)
