### ISSUE TITLE
Long-pressing backspace does not continuously erase line

### ISSUE THREAD

**Issue by sn3ksoftware** [tbodt/ish#465]
Long-pressing the backspace key does not continue to erase the whole line.
This is _kind_ of annoying because I have to keep pressing the backspace key to erase the whole line.

**Comment by tbodt** [comment]
You can press ctrl-u. This is very hard to do correctly because once you hold down delete for long enough, it starts trying to delete whole words, which is generally impossible in a terminal.

**Comment by sn3ksoftware** [comment]
Thanks for letting me know! :)
