### ISSUE TITLE
[BUG] UI bug when bluetooth keyboard connects

### ISSUE THREAD

**Issue by lunardog** [tbodt/ish#469]
Above-keyboard bar covers last lines of the terminal view when a bluetooth keyboard connects.

To reproduce:

0. make sure no external keyboard is connected to the iDevice
1. launch iSH, note on-screen keyboard
2. connect an external keyboard while iSH is on screen
3. on-screen keyboard disappears, shortcut bar stays
4. press Enter enough times to reach the bottom of the screen
5. note that the last lines are not visible

If the external keyboard is connected before iSH opens, this doesn't happen. It seems to happen only when the on-screen keyboard disappears.

Similar to old issue #154 , doesn't seem to be fixed now.

**Comment by tbodt** [comment]
I'm fairly sure that this is a UIKit bug. If I tried to work around it, that could get pretty disgusting, and break when/if they fix it.

**Comment by tbodt** [comment]
As a workaround, you can rotate your device and then rotate back.

**Comment by tbodt** [comment]
I think I found a good workaround for this.
