### ISSUE TITLE
iwconfig doesn’t work

### ISSUE THREAD

**Issue by DarkHelmet28** [tbodt/ish#473]
Hy,
when I try to use some network command like iwscan the response is:
“SIOCGIFCONF: Not a tty”.
I installed the wireless-tools package before lunch commands. Do you know how to fix this problem? This is a limitation of iSH or I made some mistakes? 

Thanks you in advance.

**Comment by tbodt** [comment]
Limitation of iSH. Apps don't have much access to network settings.
