### ISSUE TITLE
Can PowerShell 7 preview 3 run on iSH?

### ISSUE THREAD

**Issue by the-mentor** [tbodt/ish#476]
Dear iSH developers,
Per our discussion on twitter I'm opening this issue.
I was able to run PowerShell on android using an app called UserLAnd [Step-By-Step Guide](https://dev.to/thementor/i-run-powershell-on-android-and-so-can-you-458k)
I was wondering if the same process can be used to run PowerShell on iOS using iSH?

Thank you very much for all your hard work!
-DM

**Comment by tbodt** [comment]
There's no 32 bit alpine binary available, so doesn't look too easy.

**Comment by the-mentor** [comment]
@tbodt what about the generic Linux 32bit package?

**Comment by tbodt** [comment]
I don't see one in the list here https://github.com/powershell/powershell/releases

**Comment by ntindle** [comment]
You can try building from source

https://github.com/PowerShell/PowerShell/blob/master/docs/building/linux.md

**Comment by tbodt** [comment]
Looks like you need powershell to build powershell.

**Comment by the-mentor** [comment]
I wonder if @TylerLeonhardt can help or knows someone who can help.

**Comment by TylerLeonhardt** [comment]
ish is alpine based, yeah? We do ship an a couple alpine docker containers - https://github.com/PowerShell/PowerShell-Docker/blob/master/release/preview/alpine38/docker/Dockerfile

**Comment by tbodt** [comment]
Yeah this needs x86.

**Comment by TylerLeonhardt** [comment]
Yeah, unfortunately .NET Core doesn't offer any linux x86 builds so I don't think this can happen yet.
