### ISSUE TITLE
Documentation: specify --recurse-submodules otherwise  mkdist no such file or directory

### ISSUE THREAD

**Issue by tedgoddard** [tbodt/ish#488]
/Library/Developer/Xcode/DerivedData/iSH-arkakamrkrfnrhgcxvopqmxfrjek/Build/Intermediates.noindex/iSH.build/Debug-iphoneos/iSH.build/Script-BB4A53AC1FAA49CA00A72ACE.sh: line 3: ./hterm/bin/mkdist: No such file or directory

```
ls ./app/terminal/libapps/hterm/        
dist
```

To resolve this, the project must be checked out with 

`git clone --recurse-submodules https://github.com/tbodt/ish.git`

**Comment by tbodt** [comment]
Thanks for pointing this out.
