### ISSUE TITLE
mmap() failed out of memory, when running "php composer install"

### ISSUE THREAD

**Issue by AhmedTheGeek** [tbodt/ish#497]
I installed php composer https://getcomposer.org/ and cloned laravel to test if a `composer install` will work when trying to install many dependencies.

But after running the command it takes around 10 seconds then outputs the following error:

mmap() failed: [12] Out of memory.

Here's a screenshot:

![IMG_187A18562293-1](https://user-images.githubusercontent.com/1913834/65868354-5f8a7180-e378-11e9-8159-5f0511241676.jpeg)

I did that test on an iPhone X.

**Comment by tbodt** [comment]
Turns out it wasn't actually out of memory. Just fixed the bug.
