### ISSUE TITLE
Failed to run adb

### ISSUE THREAD

**Issue by faajaudai** [tbodt/ish#498]
I had run "apk add  android-tools  --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing"
to installe android-tools in iSH(iOS 12) successfuly.
But when I try to run "adb connect 192.168.1.1"  to connect a androidbox ,it shows :

>* daemon not running; starting now at tcp:5037
ADB server didn't ACK
Full server startup log: /tmp/adb.0.log
Server had pid: 29
--- adb starting (pid 29) ---
adb I 09-30 12:02:40 29 29 main.cpp:60] Android Debug Bridge version 1.0.41
adb I 09-30 12:02:40 29 29 main.cpp:60] Version 29.0.3-android-tools
adb I 09-30 12:02:40 29 29 main.cpp:60] Installed as /usr/bin/adb
adb I 09-30 12:02:40 29 29 main.cpp:60] 
adb I 09-30 12:02:40 29 29 auth.cpp:436] adb_auth_init...
adb I 09-30 12:02:40 29 29 auth.cpp:411] adb_auth_inotify_init...
* failed to start daemon
error: cannot connect to daemon

**Comment by F3000** [comment]
@faajaudai  can you connect to your phone ?

**Comment by tbodt** [comment]
I can't debug this super easily because I don't have an android phone. I'll try and set up an emulator at some point.

**Comment by tbodt** [comment]
https://twitter.com/lz__233/status/1228927002301759488 FWIW

**Comment by saagarjha** [comment]
I'm waiting for someone to build an Android app in iSH before we get Xcode for iOS…

**Comment by tbodt** [comment]
Just managed to get it to connect to an emulator. Will close now

**Comment by j005u** [comment]
I’m getting 

> Error relocating /usr/bin/adb: _ZNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found
> Error relocating /usr/bin/adb: _ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found

on the latest Testflight build when I try to run adb installed from testing.

**Comment by tbodt** [comment]
@j005u Odds are that's an alpine libc++ version mismatch, if so it can be fixed by upgrading your entire system to testing

**Comment by navanchauhan** [comment]
@tbodt I am getting the same error that @j005u is seeing

Even after running 

`apk upgrade all --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing`
