### ISSUE TITLE
Adduser crashes iSH

### ISSUE THREAD

**Issue by Mnpn03** [tbodt/ish#5]
Running `adduser` without any arguments works well, but once you add any argument(s) the app crashes.

[iPhone 6 running iOS 11.2]

**Comment by ELChris414** [comment]
Can reproduce.

**Comment by tbodt** [comment]
@Mnpn03 can you put a crash dump here?

**Comment by tbodt** [comment]
Tried it on mac, and it attempted to create a hard link. That can't be why the entire app is crashing though.

**Comment by tbodt** [comment]
Can't reproduce a crash on either the latest build or the one before it.
