### ISSUE TITLE
just cannot type in anything in console

### ISSUE THREAD

**Issue by 4096void** [tbodt/ish#50]
on iPhone SE IOS 12.1

**Comment by tbodt** [comment]
What did you do just before this happened?

**Comment by 4096void** [comment]
just installed TF version, open ish and try to type something 😂

**Comment by 4096void** [comment]
just installed TF version, open ish and try to type something 😂

**Comment by tbodt** [comment]
Funny, I haven't heard of anyone else having this problem. Can you record a video or something?

**Comment by 4096void** [comment]
Sorry, I found that I forgot switched keyboard to english, so just close me 😅
