### ISSUE TITLE
ADB/Android Tools support 

### ISSUE THREAD

**Issue by F3000** [tbodt/ish#502]
Is it possible to use this on your iOS app ?

https://pkgs.alpinelinux.org/package/edge/testing/x86/android-tools
(There is also an arm package ) 

Can I copy a file via the iOS file app into the ish file manager and use it with android tools ?

**Comment by tbodt** [comment]
`apk add` works with .apk files (alpine packages, not android apps). You can also edit /etc/apk/repositories and add the testing repository, and then just `apk add android-tools`.

**Comment by tbodt** [comment]
(They won't necessarily work, see #498)

**Comment by F3000** [comment]
I mean .andorid apk files . But copying files is possible in general ?

**Comment by tbodt** [comment]
You can copy files into iSH through the Files app.
