### ISSUE TITLE
Error when building iSH on Xcode 10.1 (High Sierra) for iPad 12.9'' (2nd Generation)

### ISSUE THREAD

**Issue by alextairbekov** [tbodt/ish#504]
I tried with two versions of meson (both latest and the one recommended in the README).

Python: 3.7.4
meson: 0.51.2 (latest on brew) and 0.49.2 (recommended).
ninja: 1.9.0
clang: Apple LLVM version 10.0.0 (clang-1000.10.44.4)
sqlite3: 3.19.3
OS: macOS High Sierra 10.13.6 (MBP 17" late 2011)

meson 0.49.2 error trace: https://pastebin.com/DNMTeVBB
This error does not occur with meson 0.51.2.

Both produce a Ninja error:

```
[1/2] Linking static target libish.a.
[2/2] Linking target ish.
FAILED: ish 
clang  -o ish 'ish@exe/main.c.o' -Wl,-dead_strip_dylibs -Wl,-headerpad_max_install_names libish.a -lm -lsqlite3 -Wl,-headerpad_max_install_names -Wl,-rpath,@loader_path/
Undefined symbols for architecture x86_64:
  "_NSLog", referenced from:
      _log_line in libish.a(kernel_log.c.o)
  "___CFConstantStringClassReference", referenced from:
      CFString in libish.a(kernel_log.c.o)
ld: symbol(s) not found for architecture x86_64

```

Also 5 warnings saying for 'Ninja' 'Meson' 'iSHFileProvider' 'libish' 'iSH' that look like this.

```
warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target <...>)
```

The following works when running in a shell:
```
meson build
cd build
ninja clean
ninja
```

I don't know how to do the same in Xcode though. I'm planning to try with Xcode 10.2 to see if this issue persists.

**Comment by tbodt** [comment]
This is weird. The target that failed isn't built in cross compiling mode. I'm not sure why the build would been seen as not cross compiling.

**Comment by tbodt** [comment]
Closing as "works on my machine"
