### ISSUE TITLE
Mounting network smb shares

### ISSUE THREAD

**Issue by febalci** [tbodt/ish#505]
Trying to mount nfs or smb shares.

Installed cifs-utils. 

mount -t cifs -o username=${SMB_USER},password=${SMB_PASS} "${SMB_SERVER}" /mnt

mount error(22): Invalid argument
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs) and kernel log messages (dmesg)
mount: mounting //192.168.1.90/volume1/dl on /mnt failed: Invalid argument

Am i being too optimistic for mounting network drives?

**Comment by tbodt** [comment]
Yeah, a bit too optimistic. CIFS support is implemented on Linux in the kernel. A FUSE type of thing might work once FUSE is working (#239).

**Comment by skm1980** [comment]
Now, nearly 2,5 years later it is still not possible to mount SMB shares from in ish right? Is someone working on that issue?
