### ISSUE TITLE
Vendor folders are not created on composer install

### ISSUE THREAD

**Issue by gatnu** [tbodt/ish#508]
Hi @tbodt ,

Love your work buddy. Currently testing to run web development environment for my ipad. 

Anyway, i have issue on generating composer autoload file. Which the folders inside vendor folder are not created. It keeps showing an error could not scan for classes inside, because the folders are not created on the process. And just installed sudo, though it should be running as a root, but nothing works. I've been following some tips from stackoverflow, still nothing works.

<img width="1194" alt="PNG image" src="https://user-images.githubusercontent.com/11384232/66287996-da680500-e901-11e9-8b27-f678a9ae8dbc.png">

Here is the analytics data from my ipad.
{"app_name":"iSH","app_cohort":"2|date=1570422600000&sf=143476&tid=b10912b00a52b43c81568d1f9dbf72b2b61418efb53c83ebc8cb1353d3bc4e7c&ttype=e","app_version":"1.0","timestamp":"2019-10-07 11:59:04.08 +0700","slice_uuid":"91604B76-0B34-35F7-9D87-493E8CA1AAEF","adam_id":1436902243,"build_version":"59","bundleID":"app.ish.iSH","share_with_app_devs":false,"is_first_party":false,"bug_type":"202","os_version":"iPhone OS 13.1 (17A844)","incident_id":"410D315B-9A06-49B7-9A53-B82658B48596","is_beta":true,"name":"iSH"}
Date/Time:        2019-10-07 11:57:29 +0700
End time:         2019-10-07 11:59:03 +0700
OS Version:       iPhone OS 13.1 (Build 17A844)
Architecture:     arm64e
Report Version:   29
Incident Identifier: 410D315B-9A06-49B7-9A53-B82658B48596

Data Source:      Microstackshots
Shared Cache:     0x42634000 31E822A5-6230-3455-A567-A2FBAB42A438

Command:          iSH
Path:             /private/var/containers/Bundle/Application/D661E882-DAA5-410F-805D-0C62271CE861/iSH.app/iSH
Identifier:       app.ish.iSH
Version:          1.0 (59)
Beta Identifier:  6DAD8C60-6973-412C-8FB3-AA8430C5F540
PID:              838

Event:            cpu usage
Action taken:     none
CPU:              90 seconds cpu time over 94 seconds (95% cpu average), exceeding limit of 50% cpu over 180 seconds
CPU limit:        90s
Limit duration:   180s
CPU used:         90s
CPU duration:     94s
Duration:         94.49s
Duration Sampled: 8.15s
Steps:            11

Hardware model:   iPad8,3
Active cpus:      8

Heaviest stack for the target process:
  11  ??? (libsystem_pthread.dylib + 7516) [0x1c279fd5c]
  11  ??? (iSH + 71976) [0x102c7d928]
  2   ??? (iSH + 372016) [0x102cc6d30]

Powerstats for:   iSH [838]
Bundle ID:        app.ish.iSH
Adam ID:          1436902243
Is first party:   No
App version:      1.0
Build version:    59
Is Beta:          Yes
Share with Devs:  No
UUID:             91604B76-0B34-35F7-9D87-493E8CA1AAEF
Path:             /private/var/containers/Bundle/Application/D661E882-DAA5-410F-805D-0C62271CE861/iSH.app/iSH
Architecture:     arm64
Footprint:        367.86 MB
Start time:       2019-10-07 11:58:55 +0700
End time:         2019-10-07 11:59:03 +0700
Num samples:      11 (100%)
CPU Time:         8.024s
Primary state:    11 samples Frontmost App, Non-Suppressed, User mode, Effective Thread QoS Default, Requested Thread QoS Default, Override Thread QoS Unspecified
User Activity:    0 samples Idle, 0 samples Active, 11 samples Unknown
Power Source:     0 samples on Battery, 0 samples on AC, 11 samples Unknown
  11  ??? (libsystem_pthread.dylib + 7516) [0x1c279fd5c]
    11  ??? (iSH + 71976) [0x102c7d928]
      2   ??? (iSH + 372016) [0x102cc6d30]
      1   ??? (iSH + 419336) [0x102cd2608]
      1   ??? (iSH + 404900) [0x102cceda4]
      1   ??? (iSH + 375776) [0x102cc7be0]
      1   ??? (iSH + 372048) [0x102cc6d50]
      1   ??? (iSH + 371200) [0x102cc6a00]
      1   ??? (iSH + 365936) [0x102cc5570]
      1   ??? (iSH + 365872) [0x102cc5530]
      1   ??? (iSH + 365808) [0x102cc54f0]
      1   ??? (iSH + 365328) [0x102cc5310]

  Binary Images:
           0x102c6c000 -                ???  iSH                     <91604B76-0B34-35F7-9D87-493E8CA1AAEF>  /private/var/containers/Bundle/Application/D661E882-DAA5-410F-805D-0C62271CE861/iSH.app/iSH
           0x1c279e000 -        0x1c27a8fff  libsystem_pthread.dylib <B3A6ABED-CFD0-38EF-9C78-47E0E67AC9B3>  /usr/lib/system/libsystem_pthread.dylib

Asides from this issue, i personally love the product. Keep up your good work buddy. Planning to subscribe your patreon by next week ;)

**Comment by bax137** [comment]
Same problem.
Is you interrupt composer during the installing step, you can see that:
- the directory of the library is created in vendor directory
- the zip file is copied in this directory
- the zip file is unzipped in a temporary directory in vendor/composer 

But that’s all.. When composer continue on next library, the directory in vendor directory has disappeared. For information, I have this error: unknown ioctl 5413.

(if you unzip manually all the zip files from ~/.composer/cache in vendor directory, you can relaunch composer without errors.)

**Comment by tbodt** [comment]
Can't reproduce on mac, but can reproduce on iOS.
