### ISSUE TITLE
Can't "compose" accents with hardware keyboard.

### ISSUE THREAD

**Issue by etra0** [tbodt/ish#510]
When I'm using my external keyboard (Logitech K380), I can't compose accents keys (á, é, í, ó, ú) and in general any other key. I can use the software keyboard to write this letters though.

I tried using the Option -> Meta config but nothing changes.

In the iPadOS seems like first it writes the accent and then they letter to compose the character, maybe that's the problem.

**Comment by etra0** [comment]
Updated to the latest build `1.0 (61)` and still have the same problem:

![video](https://i.imgur.com/hYVZujA.gif)

I'm running iPadOS 13.2

**Comment by tbodt** [comment]
OK I'll have to fix that. What keyboard layout are you using?

**Comment by etra0** [comment]
Spanish - ISO in the OS as in the keyboard layout.

**Comment by tbodt** [comment]
Works on my machine https://youtu.be/T_pP-Wi5tf8
