### ISSUE TITLE
Cat messes up Foreground Color

### ISSUE THREAD

**Issue by Regularcheckm8** [tbodt/ish#512]
Whenever you run cat than a file in bin over a certain amount of bytes it will take the foreground color and make it so that it acts as if it’s a background for the output instead of it being the color of the output. Thought this could be an issue because for me the only way to reverse it is to restart the application. -checkm8

**Comment by tbodt** [comment]
This type of thing happens when you cat a binary file. You can fix it with `reset`.

**Comment by Regularcheckm8** [comment]
Ok, wonder if there’s something I can do to at least stabilize it

**Comment by tbodt** [comment]
Nah that's just how terminals work. You can't really do anything about it. A long enough file will contain every possible escape sequence.

**Comment by Regularcheckm8** [comment]
Oof ok 😢
