### ISSUE TITLE
Caps to Control no longer clears the caps-lock key

### ISSUE THREAD

**Issue by idvorkin** [tbodt/ish#514]
On iOS 13.2 (and some build of 13.1 before I upgraded). 

1. Enable Caps -> Control Remap:
2. Press Caps Lock

I believe the old behavior was on KeyUp(Caps) CapsLock would be cleared. 
Now on KeyUp(Caps) Caplock remains set, which results in all the future keys having the C- modiffier until you KeyDown+KeyUp capslock again.

**Comment by idvorkin** [comment]
Sounds like: https://github.com/blinksh/blink/issues/732 which has reappered in 13.2

**Comment by tbodt** [comment]
iOS bug, not much I can do.

**Comment by idvorkin** [comment]
@tbodt  Agreed. Want to leave it open for others who have this issue and so we know when it'll be fixed?

**Comment by idvorkin** [comment]
Looks like this is fixed in Blink beta (testing in TF looks good).

**Comment by idvorkin** [comment]
I don’t know how it works, but i suspect it’s related to this https://github.com/blinksh/blink/commit/318fc41dde54a3bcdd59ebf29a9a345bab405f43

**Comment by tbodt** [comment]
oh god javascript

**Comment by tbodt** [comment]
iOS 13.4 has a cool new API that should make this relatively easy

**Comment by idvorkin** [comment]
Hooray

**Comment by tbodt** [comment]
I've deactivated the caps lock mapping thing in efc4876, and added a message saying that you can upgrade to iOS 13.4 to change the mapping system-wide. I could also add the setting back on iOS 13.4, but that would take a bit of work, still requires that you upgrade to 13.4, and it's not clear to me that there's any real benefit to having a different setting for one app, especially if that setting stacks in potentially confusing ways with the system-wide setting.
