### ISSUE TITLE
Ssh not found

### ISSUE THREAD

**Issue by jabba243** [tbodt/ish#520]
Attempting to connect to raspberry pi but keep getting

 -ash: ssh: not found

**Comment by Mnpn03** [comment]
`apk add openssh-client`

**Comment by jabba243** [comment]
Now getting this 

ssh: Could not resolve hostname rpigarage.local: Name does not resolve

**Comment by tbodt** [comment]
What does `cat /etc/resolv.conf` say?

**Comment by b-** [comment]
> rpigarage.local

I don't know if [Avahi](https://avahi.org) works in iSH, but I'm pretty sure you'll need it to use zeroconf aka Bonjour aka _.local_ hostnames. It doesn't appear to be falling to iOS's resolver, so that would make sense.

**Comment by jabba243** [comment]
> What does `cat /etc/resolv.conf` say?
I get this

search corcom41
nameserver 192.168.1.1

I tried on my MacBook and it connects fine.

**Comment by jabba243** [comment]
> > rpigarage.local
> 
> I don't know if [Avahi](https://avahi.org) works in iSH, but I'm pretty sure you'll need it to use zeroconf aka Bonjour aka _.local_ hostnames. It doesn't appear to be falling to iOS's resolver, so that would make sense.

Sorry this is beyond my knowledge or understanding

**Comment by tbodt** [comment]
Looks like mDNS (i.e. .local domains) can't work with alpine. https://wiki.musl-libc.org/future-ideas.html#mDNS_and_alternate_hostname_database_backends

**Comment by g6ai** [comment]
Does it mean whether mDNS will work or not depends on alpine? It there any workaround/package to make mDNS work?

**Comment by rakslice** [comment]
Also manually doing an mdns lookup with e.g. `avahi-resolve-host-name` from `avahi-tools` doesn't work because you can't run the service.
