### ISSUE TITLE
iOS 13.2, iSH 61, bg command may cause prompt disappear

### ISSUE THREAD

**Issue by onewayticket255** [tbodt/ish#537]
![A806F46B-825A-4042-870B-84B3CBC8535E](https://user-images.githubusercontent.com/37437616/67242122-6ee87080-f487-11e9-9d78-afd90a818a48.jpeg)

![1981BAB8-D42F-4132-9630-100DB4BF82D3](https://user-images.githubusercontent.com/37437616/67242209-9ccdb500-f487-11e9-86b2-e5edd9fb3a3e.jpeg)

**Comment by tbodt** [comment]
The first screenshot is expected behavior. Can you post your aria2 config file?

**Comment by onewayticket255** [comment]
root@Dominic-iPhone-Xs-Max  ~  cat aria.conf
dir=/root
async-dns=false  
enable-rpc=true
rpc-allow-origin-all=true
rpc-listen-all=true
rpc-listen-port=6800
max-concurrent-downloads=3
continue=true
max-connection-per-server=5
min-split-size=10M
split=10
max-overall-download-limit=0
max-download-limit=0
max-overall-upload-limit=0
max-upload-limit=0
file-allocation=prealloc
bt-enable-lpd=true
enable-dht=true
listen-port=6881-6999
seed-time=0
 ⚡ ⚙ root@Dominic-iPhone-Xs-Max  ~ 

**Comment by tbodt** [comment]
That also seems to be expected behavior, since aria2 expects to be the only program running on the terminal.
