### ISSUE TITLE
redo keyboard buttons

### ISSUE THREAD

**Issue by Rexogamer** [tbodt/ish#539]
currently it’s difficult to use the text movement button as it’s rather small. ideas:
- split it into 3 buttons (up/down, left and right)
- extend keyboard and make it bigger (or extend the keyboard and split it into 4)
although if we did the third option, we’d have to redesign the Linux equivalent of the control button (which is kinda confusing to a newbie anyway)

**Comment by Mnpn03** [comment]
I personally don't find it too small or difficult to use (can't say from an a11y perspective). Extending the keyboard (making it bigger) is a trade-off I don't think most people would like. Three buttons makes less sense than 2 or 4, and I personally think 1 is fine.

**Comment by Rexogamer** [comment]
hmmm... maybe just make the buttons a bit bigger at the expense of, say, one terminal line

**Comment by Mnpn03** [comment]
Doesn't sound like a better solution either, IMHO

**Comment by Rexogamer** [comment]
in any case the button is a bit small

**Comment by Rexogamer** [comment]
oh, you can drag in whatever direction. no need to stay on the button, I was unaware of this

**Comment by tbodt** [comment]
I agree it's not the best but I don't have better ideas. One constraint is that the toolbar needs to fit on a portrait oriented iPhone SE.

**Comment by tommythorn** [comment]
I know this is closed but I’d encourage studying the Terminus app which have iterated on this a billion times and come up with a (IMO) very well designed UI (including how gestures on the screen are done)
