### ISSUE TITLE
Causing network issues

### ISSUE THREAD

**Issue by joefitzgerald** [tbodt/ish#54]
I have observed network issues on iOS 12.1.1 beta 2.

- Use your device to access the internet and observe it works
- Open `ish`
- Invoke commands in `ish` that access the internet
- Attempt to access the internet in other iOS apps, and observe that it does not work anymore
- Reboot iOS device
- Observe the network working again
- Open `ish`, and use the network a bunch
- Observe a reoccurrence of the issue

**Comment by OxLemonxO** [comment]
works for me on iOS 11.2

**Comment by bordplate** [comment]
I assume you meant "iOS 12.1.1 beta 2" as there are no betas available for iOS 11?

**Comment by Mnpn03** [comment]
Cannot reproduce on iOS 12.1

**Comment by joefitzgerald** [comment]
Yes, apologies, I’m running 12.1.1 beta 2 (16C5043b). It is possible this is related to my use of a USB-C hub that has a network adapter (which works 🎉).

I have tried and can reproduce with:
* just the network adapter enabled
* both the network adapter and WiFi connected 

This may purely be an iOS issue, or it may be a combination of an iOS issue and an `ish` issue.

**Comment by joefitzgerald** [comment]
I just experienced the same issue during a reboot cycle where there was no use of `ish`, so I’m going to close this and will re-open if I can establish causation.
