### ISSUE TITLE
USB Support

### ISSUE THREAD

**Issue by brandonros** [tbodt/ish#546]
Just wanted to get the discussion going to see what is/isn't possible.

I know iOS 13 revamped USB support. Not sure what kind of glue would need to be written to bridge the iSH iOS app to the Linux kernel USB drivers.

**Comment by tbodt** [comment]
#543 will let you mount USB drives from the files app. That's the extent of iOS 13 USB support, so I don't think there's much else to discuss.

**Comment by brandonros** [comment]
I want to utilize the SocketCAN module (to be able to plug in a USB -> CAN over OBD-II module) and work with it inside of iSH.

**Comment by tbodt** [comment]
I'm afraid you can't, as iOS doesn't support that. Plus iSH doesn't use Linux so Linux drivers wouldn't work.
