### ISSUE TITLE
Function keys

### ISSUE THREAD

**Issue by Daisuke-sama** [tbodt/ish#547]
Hi,
Cool app, 
I have been stumbled by F keys using the Smart Keyboard. Are there any way to reach that stuff?

**Comment by tbodt** [comment]
No. Why do you need them? FYI Midnight Commander lets you use esc+1 instead of f1.

Duplicate of #311

**Comment by 7heaven** [comment]
same problem here, I login to my router via ssh using ish, my router runs RouterOS and F1 act as help command and it didn't work
