### ISSUE TITLE
Darwin Emulation

### ISSUE THREAD

**Issue by alessaba** [tbodt/ish#552]
Hi,
This is not really an issue, more like a suggestion (from a guy that uses iSH a lot but unfortunately has not yet explored how it works)

There's this article that explains how to run Darwin in QEMU:
https://alephsecurity.com/2019/06/17/xnu-qemu-arm64-1/

Would it be technically possible to do a similar thing in a separate branch of iSH (Running Darwin instead of Alpine Linux)? Would it involve rewriting most of the code or just the bare OS loading? 

Sorry if this might seem like a dumb question, but I just thought this would be interesting, and maybe I can try to contribute once I understand the necessary steps.

P.S: Related question: would it be even legal to do it? it's technically a closed source OS, property of Apple, right?

**Comment by tbodt** [comment]
iSH isn't a full system emulator, only usermode. Syscalls are reimplemented. So not easily. Of course you could try if you want.
