### ISSUE TITLE
Excuse me,how can I get the exchanging code to apply for testflight？

### ISSUE THREAD

**Issue by 435390736** [tbodt/ish#554]
Excuse me,how can I get the exchanging code to apply for testflight？

**Comment by Mnpn03** [comment]
You only have to visit the invite link that's on the website - https://testflight.apple.com/join/97i7KM8O

**Comment by 435390736** [comment]
OK，thank you.I have tested it for a little moment.It is woderful.Hope you can do it better🙏



发自我的iPhone


------------------ Original ------------------
