### ISSUE TITLE
Nslookup : error message if no dns specified

### ISSUE THREAD

**Issue by bax137** [tbodt/ish#560]
If I don’t specify a dns server in nslookup command, there is an error message :

iPad-Pro-:~# nslookup www.google.fr
nslookup: can't resolve '(null)': Name does not resolve

Name:      www.google.fr
Address 1: 2a00:1450:4007:812::2003 par21s05-in-x03.1e100.net
Address 2: 216.58.213.131 par21s03-in-f131.1e100.net

I am not sure if it’s a bug or not...

**Comment by tbodt** [comment]
Apparently this is an nslookup bug: https://stackoverflow.com/a/57066045/1455016
