### ISSUE TITLE
git push not working 

### ISSUE THREAD

**Issue by roxtigger2003** [tbodt/ish#562]
Hi, I installed a git package and nothing happened when I used the git push command, and I don't know if the error is from the app.  The device I use is ios.
![1446DE26-A0A8-48BB-AA12-12D005C73065](https://user-images.githubusercontent.com/36947924/69030787-216e0d80-0a0b-11ea-9122-3dfb81784985.png)

**Comment by tbodt** [comment]
This is what git push does when you haven't made any commits. Closing as that's the most likely explanation.

**Comment by roxtigger2003** [comment]
I did but nothing happened

**Comment by DoctorNSA** [comment]
Have you added your commits with git add<file>?

**Comment by roxtigger2003** [comment]
i have use command git add * but still not working =w=

**Comment by roxtigger2003** [comment]
before git add
![C9A4FB47-6920-4C5C-A14A-C9166342449D](https://user-images.githubusercontent.com/36947924/69084716-6760bb00-0a77-11ea-97a1-58724539e246.png)

after git add
![F3CB9C55-D2E9-4277-8789-DBB0ED8F131D](https://user-images.githubusercontent.com/36947924/69084996-e950e400-0a77-11ea-9c56-4f43fbcaf90c.png)

**Comment by Mnpn03** [comment]
As it says in there, the correct usage for adding everything is `git add .`, but this doesn't seem like an issue with iSH?

**Comment by tbodt** [comment]
After `git add`, you have to run `git commit` before `git push`. Did you?

**Comment by roxtigger2003** [comment]
> After `git add`, you have to run `git commit` before `git push`. Did you?

yea i have, after that i have uninstall app and install again is work 🤔
thanks guys
