### ISSUE TITLE
Add touch support

### ISSUE THREAD

**Issue by Mnpn03** [tbodt/ish#564]
While watching [this video](https://youtu.be/ceccuaz5lQE) I noticed that they tried to tap to simulate clicks in emacs by tapping at around 1:34:00. I have no idea how you'd go around implementing this, or how you would distinguish scrolling from this tapping ([UITapGestureRecognizer?](https://developer.apple.com/documentation/uikit/uitapgesturerecognizer)) but it could be interesting to have.

**Comment by saagarjha** [comment]
I wonder if this just requires [enabling it](https://chromium.googlesource.com/apps/libapps/+/master/hterm/doc/ControlSequences.md#Mouse-Reporting-Tracking) in hterm…

**Comment by tbodt** [comment]
Turns out it was already working, there just wasn't a way for hterm to send the mouse inputs to iSH.
