### ISSUE TITLE
Pip module object is not callable

### ISSUE THREAD

**Issue by danieltomasz** [tbodt/ish#566]
I am using using ish on IPad 2018 Pro with lates IPadOS.
After installing pip using py3-setuptools (40.8.0-r1) I started getting this error when I tried  to update  `pip `. Update went smoothly but when trying to install another module I am getting error, even after reinstalling pip

```
pip3 install --user -U virtualenv
Traceback (most recent call last):
  File "/usr/bin/pip3", line 10, in <module>
    sys.exit(main())
TypeError: 'module' object is not callable 
```
Similar error I was getting in Ubuntu (when updating pip from pip 9 to pip19, editing bin/pip3 file helped in that time, this time this doesn’t work)

**Comment by tbodt** [comment]
Not an iSH bug. See https://github.com/pypa/pip/issues/7205
