### ISSUE TITLE
Feature request: default to non-root accounts

### ISSUE THREAD

**Issue by jacobshapiro** [tbodt/ish#569]
This is somewhat related to https://github.com/tbodt/ish/issues/184 but not entirely.

It would be nice if the first time after you install iSH, you are prompted for a username (and password? or default to empty? Or even integrate FaceID??) that is created at the first run, so that you don't have to go through the process of setting up a user account, installing sudo, adding my account to sudoers, and writing a little script to always log you into that account in root's ~/.profile.

**Comment by tbodt** [comment]
I don't want to deviate from the default state of Alpine.
