### ISSUE TITLE
error when i run my bot discord use python3 and module discord.py

### ISSUE THREAD

**Issue by roxtigger2003** [tbodt/ish#571]
i have run my discord bot on ish (just test my code) and take this error

![6E9B09B1-A4CF-4A5E-8B14-7F18963854F2](https://user-images.githubusercontent.com/36947924/69566050-ca5ad080-0fe8-11ea-8f47-5e512a0c4edc.png)

**Comment by Rexogamer** [comment]
does the code work on python 3 on your desktop/whatever

**Comment by roxtigger2003** [comment]
my code work perfect on my pc

**Comment by roxtigger2003** [comment]
you cant help me ?

**Comment by tbodt** [comment]
No I fixed it, it'll be working in the next build

**Comment by roxtigger2003** [comment]
thanks very much
