### ISSUE TITLE
Cannot install texlive-full due to missing libpoppler dependency

### ISSUE THREAD

**Issue by orialb** [tbodt/ish#572]
Hi,
I am unable to install `texlive-full` from alpine-linux community edge repository as the package manager complaints that `so:libpoppler.so.92` is missing.
I tried installing `poppler`, but this didn't resolve the issue. 
(opened an issue as per the request in Discord)

Let me take this opportunity to thank you for this great project! I am really excited about the possibilities this brings to the iPad !

**Comment by tbodt** [comment]
Don't think this is an iSH bug. https://gitlab.alpinelinux.org/alpine/aports/issues/5335

**Comment by orialb** [comment]
Sorry for that. I tried to search this issue before opening an issue, apparently not well enough :) thanks for pointing me to the alpine Linux issue tracker.

 The problem was indeed solved by making sure that poppler was installed from the edge repository (where texlive is).
