### ISSUE TITLE
Feature proposal: option to clear scrollback on screen erase

### ISSUE THREAD

**Issue by Vasfed** [tbodt/ish#576]
iSH terminal supports "erase whole display including scroll-back buffer" (code `<esc>[3J`, can be used via `printf '\e[3J'`)
But `clear` command/`^l` shortcut outputs `<esc>[2J` (plain "erase display" command)

The former is harder to type and remember, so an option for clearing the scrollback on `[2J` will be useful.

**Comment by tbodt** [comment]
I can't easily and won't change the functionality of a command that's part of Alpine.

**Comment by Vasfed** [comment]
> I can't easily and won't change the functionality of a command that's part of Alpine.

You do not have to change anything inside alpine, the issue is about changing iSH handling of the escape sequence `\e[2J` that is produced by alpine

**Comment by tbodt** [comment]
I don't want to do that either because `\e[2J` means clear screen without clearing scrollback in every existing terminal emulator.
