### ISSUE TITLE
About apk add build-essential

### ISSUE THREAD

**Issue by 435390736** [tbodt/ish#593]
I want to write some C programs. After I install gcc,I need to install build-essential. But when I input “apk add build-essential”,it says
” ERROR: unsatisfiable constraints:
  build-essential (missing):
    required by: world[build-essential]”
Even if I change the file /etc/app/repositories, it doesn’t work.
How can I solve this problem?

**Comment by tbodt** [comment]
It's build-base

**Comment by OpticNullBytes** [comment]
okay thanks

**Comment by 435390736** [comment]
I try to uninstall ish,and install it again.I find it worked!I can use pip3 again.Maybe something wrong because I install python3 first and then install gcc.


------------------ Original ------------------
