### ISSUE TITLE
Test Flight beta is full

### ISSUE THREAD

**Issue by aschimmichanga** [tbodt/ish#595]
There should be an alternative download option for those who do not have XCode.

**Comment by tbodt** [comment]
What kind of download are you requesting?

**Comment by aschimmichanga** [comment]
Getting iSH on an iOS device

**Comment by tbodt** [comment]
How do you plan to do that without Testflight?

**Comment by aschimmichanga** [comment]
Exactly.. that’s what I’m wondering since the Testflight Beta is full. What other option is there?

**Comment by tbodt** [comment]
I don't know of one. I could build and upload an IPA, but cydia impactor doesn't work right now. I plan to remove some testflight testers tomorrow. Sorry for the delay, I've been on Christmas break.

**Comment by Rexogamer** [comment]
IIRC we’ll *eventually* try and get it on the App Store, but tbodt doesn’t feel it’s ready + there’s no guarantee Apple would accept it.

**Comment by tbodt** [comment]
The beta is no longer full.

**Comment by martinorob** [comment]
@tbodt please may you remove some testflight tester because the beta is full again and i cannot join?

Thanks
