### ISSUE TITLE
x11vnc xorg-server and xfce4

### ISSUE THREAD

**Issue by creepinson** [tbodt/ish#599]
I connected to my vnc server that is running in ish using Realvnc viewer iOS app and it says peername failed invalid argument
![Image](https://i.imgur.com/Vt4Pnuz.jpg)

**Comment by tbodt** [comment]
How did you start the vnc server?

**Comment by creepinson** [comment]
I ran 
x11vnc

**Comment by tbodt** [comment]
Is iSH running in the background? What log output appears in iSH? Also you need to run x11vnc with `-create` and `-noshm`.

**Comment by creepinson** [comment]
It also said unable to open display :0 but then it said trying again and nothing happened

**Comment by creepinson** [comment]
That helped
But
![Image](https://i.imgur.com/no6PIvA.jpg)![Image](https://i.imgur.com/aTNxobQ.jpg)

**Comment by tbodt** [comment]
Sounds like you need to create an xinitrc or install xterm

**Comment by creepinson** [comment]
Better
![Image](https://i.imgur.com/L88iQMS.jpg)

But vnc viewer just says connecting and when I go back to ish it looks like x11vnc crashed again

**Comment by creepinson** [comment]
And the whole ish app crashed

**Comment by creepinson** [comment]
https://pastebin.com/gd5QqaC4

**Comment by tbodt** [comment]
Filed #600 for the crash. I recommend using `cat /dev/location > /dev/null &` to keep iSH running in the background while you use VNC viewer.

**Comment by creepinson** [comment]
Seems to not crash
But I got the same or similar x11vnc output from before. Vnc viewer with port 5900 just says connecting... while vnc viewer with port 5901 says it cannot contact the port.

**Comment by creepinson** [comment]
![Image](https://i.imgur.com/1C5qpfh.jpg)

**Comment by tbodt** [comment]
Duping to #422
