### ISSUE TITLE
Crash when installing/uninstalling Lua

### ISSUE THREAD

**Issue by tbodt** [tbodt/ish#6]
This is the *weirdest fucking thing*. When you run ish in the debugger, it segfaults at the end of the install, and if you check the pointer in the debugger it looks valid. Then if you click continue, or step, it just keeps going as if nothing was wrong. When you run outside the debugger, it crashes before producing any output, and the crash dump shows the pointer is pointing to an unmapped page surrounded by mapped pages. Not quite sure if it's the same bug.

**Comment by Mnpn03** [comment]
Can reproduce.

**Comment by ELChris414** [comment]
Can reproduce.

**Comment by tbodt** [comment]
Plan for investigating further: find out how to ask Mach if a pointer is valid, then do this right before the crash and print the output.

**Comment by Mnpn03** [comment]
^ Try to print whenever you can.

**Comment by tbodt** [comment]
Turns out it was a cow problem. Fixed by https://github.com/tbodt/ish/commit/bd6ab0f1e21622976e3c4f89cc3c43c20b666c23.
