### ISSUE TITLE
Java websocket error

### ISSUE THREAD

**Issue by Nikita11790** [tbodt/ish#607]
![4CFE0515-0201-4C3F-AAA6-3D6D8601DA66](https://user-images.githubusercontent.com/37966860/71803030-7e05a600-3014-11ea-8a37-3f16489d3c9c.jpeg)

The jar is https://papermc.io/api/v1/paper/1.15.1/34/download

**Comment by ntindle** [comment]
What’s the output of dmesg?
What version/flavor of Java

**Comment by Nikita11790** [comment]
Jdk8
I’m not sure if other it was default

**Comment by Nikita11790** [comment]
I ran dmesg and I saw nothing happen on my screen or show

**Comment by tbodt** [comment]
FIONREAD is implemented. Minecraft still doesn't work.
