### ISSUE TITLE
Firefox Refuses to Launch

### ISSUE THREAD

**Issue by tech234a** [tbodt/ish#608]
Console output:

XPCOMGlueLoad error for file /usr/lib/firefox/libmozsandbox.so:
Error relocating /usr/lib/firefox/libmozsandbox.so: _ZNSt19_Sp_make_shared_tag5_S_eqERKSt9type_info: symbol not found
Couldn't load XPCOM.

Dmesg output:
421 stub syscall 332
421 stub syscall 291
434 stub syscall 332
434 stub syscall 332
434 stub syscall 291
FIXME socketcall 18

**Comment by ntindle** [comment]
421 stub syscall 332
421 stub syscall 291
ignoring EPOLLET
434 stub syscall 332
434 stub syscall 332
434 stub syscall 291

**Comment by tech234a** [comment]
After I updated iSH I got illegal instruction.

Unique dmesg lines:
357 stub syscall 291
357 stub syscall 332
364 illegal instruction at 0xf401b4a5: f2 0f 10 45 e8 f2 0f 11 
364 stub syscall 375
ignoring EPOLLET

**Comment by tbodt** [comment]
I fixed one thing and then it started trying to use sse2 which is too hard.
