### ISSUE TITLE
Should add a button to clear the terminal

### ISSUE THREAD

**Issue by aschimmichanga** [tbodt/ish#614]

**Comment by Mnpn03** [comment]
Can’t you just type `clear`?

**Comment by aschimmichanga** [comment]
When you scroll up, there are still lines of commands. The whole thing is not cleared

**Comment by uwe-schwarz** [comment]
`clear` works for me, but if it doesn't `reset` should help.

**Comment by tbodt** [comment]
cmd+shift+k on a hardware keyboard clears scrollback. There isn't really room to add more buttons above the keyboard (since they have to fit on an iPhone SE.)

**Comment by VincentCCandela** [comment]
or just type "reset"

**Comment by bderiso** [comment]
one more tip: ctrl+l (Lowercase ‘L’) scrolls the buffer to “clear” the screen while allowing you to scroll back through if needed.
