### ISSUE TITLE
About iperf3

### ISSUE THREAD

**Issue by aitsc** [tbodt/ish#616]
I installed iperf3 using "apk add iperf3", but it did not work.

Error on other linux (iperf3 -c 192.168.150.16): iperf3: the client has unexpectedly closed the connection

Error on iSH (iperf3 -s): iperf3: error - unable to set TCP_CONGESTION: Supplied congestion control algorithm not supported on this host

**Comment by Nikita11790** [comment]
add urself to the hosts file

**Comment by tbodt** [comment]
@Nikita11790 That's not the solution to every weird network error, and will probably do nothing for this
