### ISSUE TITLE
kerberos commands return “Bad file descriptor”

### ISSUE THREAD

**Issue by lyon-fnal** [tbodt/ish#628]
HI - I’m really looking forward to use ish to access computing resources from my iPad. We use kerberos for security. I did 

```
apk add krb5
```

and copied my `krb5.conf` file to `/etc/krb5.conf`.

I get a Kerberos ticket with `kinit`. The communication with our kerberos server seems to work, but it ends with an error...

```bash
ipad-132427:~# kinit <removed>
Password for <removed> 
kinit: Failed to store credentials: Bad file descriptor (filename: /tmp/krb5cc_0) while getting initial credentials
```

There’s an option to `kinit` that saves credentials to any file, and when I do a file in `/root` it fails the same way.

Furthermore, the `klist` command, which tells me what tickets I have (maybe none) also fails with a similar Bad file descriptor error. 

I imagine the kerberos executables were built in some incompatible way. Any ideas? Let me know how I can help!  Thanks, Adam

**Comment by thunderkeys** [comment]
I can replicate, but I wanted to add that the credential cache IS generated properly after authenticating - if it is copied to another (regular, non-iSH) system, it works with klist/can be used to authenticate to other systems.

```
examplesystem:~ exampleuser$ KRB5CCNAME=FILE:/Users/exampleuser/ccache klist
Credentials cache: FILE:/Users/exampleuser/ccache
        Principal: exampleuser@EXAMPLE.COM

  Issued                Expires               Principal
Feb 25 09:10:56 2020  Feb 25 19:10:56 2020  krbtgt/EXAMPLE.COM@EXAMPLE.COM

[ssh somewhere]

examplesystem:~ exampleuser$ KRB5CCNAME=FILE:/Users/exampleuser/ccache klist
Credentials cache: FILE:/Users/exampleuser/ccache
        Principal: exampleuser@EXAMPLE.COM

  Issued                Expires               Principal
Feb 25 09:15:17 2020  Feb 25 19:10:56 2020  host/somesystem.second.example.com@SECOND.EXAMPLE.COM
Feb 25 09:15:17 2020  Feb 25 19:10:56 2020  krbtgt/SECOND.EXAMPLE.COM@EXAMPLE.COM
Feb 25 09:10:56 2020  Feb 25 19:10:56 2020  krbtgt/EXAMPLE.COM@EXAMPLE.COM
```

**Comment by tbodt** [comment]
The main blocker for me fixing this is me having no idea how kerberos works. If I had step-by-step instructions for reproducing this including setting up a kerberos server if needed, that would help.

**Comment by tbodt** [comment]
The main blocker for me fixing this is me having no idea how kerberos works. If I had step-by-step instructions for reproducing this including setting up a kerberos server if needed, that would help.

**Comment by lyon-fnal** [comment]
Thanks @thunderkeys. I will try that!

**Comment by lyon-fnal** [comment]
@tbodt I understand your problem. Unfortunately I can't give you a way to try things yourself with the system I authenticate with.  I don't know of a kerberos test system, and I don't know how to set up one yourself (and it's probably a big pain). If it would be helpful, I would be happy to spend an hour over Skype or Zoom with you to debug and try stuff.  Let me know.  Though @thunderkeys solution may be good enough.

**Comment by tbodt** [comment]
I don't think that's a solution, it doesn't let you use your kerberos credentials on your iPad. Instead you can obtain credentials on your iPad and use them on another computer.

**Comment by thunderkeys** [comment]
@tbodt I've got a test KDC setup and am working on a client system now (to test with SSH for example).

What's the best way to work with you on this - Discord?

**Comment by thunderkeys** [comment]
@lyon-fnal FYI, another issue may arise once/if this is resolved - it appears that SSH and curl (for example) are not compiled with Kerberos/GSSAPI support in the apks.

https://build.alpinelinux.org/buildlogs/build-edge-x86/main/openssh/openssh-8.2_p1-r0.log
                 KerberosV support: no

**Comment by tbodt** [comment]
Discord is good, I should have some time this weekend. If you want to try debugging it yourself, there are instructions in the readme for building and running ish on Linux for testing.

**Comment by thunderkeys** [comment]
Ok, I got a debug environment up running, and I believe these are the relevant syscalls for klist failing:

```
3 call 5   openat(-100, "/tmp/krb5cc_0", 0x88000, 0x0) = 0x3
3 call 221 fcntl(3, F_SETFD, 0x1) = 0x0
3 call 221 fcntl(3, F_SETFD, 0x1) = 0x0
3 call 221 fcntl(3, 38) = 0xffffffea
3 call 221 fcntl(3, F_SETLKW64, 0xffffd3a4) = 0xfffffff7
3 call 6   close(3) = 0x0
3 call 146 write(2, "klist: Bad file descriptor (filename: /tmp/krb5cc_0)", 52)write(2, "", 0) = 0x34
```

**Comment by tbodt** [comment]
I see that first it tries F_OFD_SETLKW which isn't implemented. That's not really the problem as it tries F_SETLK64 when that fails. That fails with an error that's supposed to indicate that you tried to do a read lock but the file isn't open for reading. This isn't true, the file was opened as read-only. The real problem is I messed up the code that checks the open file mode.

https://github.com/tbodt/ish/blob/91b9acf52b8c1738a2633e9426a26269cdce50ba/fs/lock.c#L215

The problem is that O_RDONLY et al aren't flags. O_RDONLY is 0, O_RDWR is 2. You can't check them like you normally check flags, you have to mask against O_ACCMODE which is 3 and then use ==. If you want to take a shot at fixing this go ahead, otherwise I can do it on the weekend.

**Comment by thunderkeys** [comment]
The below diff does make kinit/klist work, and a hand compiled curl with GSSAPI can authenticate against a Kerberos-protected webserver.

Not sure if this patch is 100% correct, though.

```
diff --git a/fs/lock.c b/fs/lock.c
index c497bf4..89743fc 100644
--- a/fs/lock.c
+++ b/fs/lock.c
@@ -212,9 +212,9 @@ out:
 int fcntl_setlk(struct fd *fd, struct flock_ *flock, bool blocking) {
     if (flock->type != F_RDLCK_ && flock->type != F_WRLCK_ && flock->type != F_UNLCK_)
         return _EINVAL;
-    if (flock->type == F_RDLCK_ && !(fd_getflags(fd) & (O_RDONLY_|O_RDWR_)))
+    if (flock->type == F_RDLCK_ && !((fd_getflags(fd) & O_ACCMODE_) == O_RDONLY_) && !((fd_getflags(fd) & O_ACCMODE_) == O_RDWR_))
         return _EBADF;
-    if (flock->type == F_WRLCK_ && !(fd_getflags(fd) & (O_WRONLY_|O_RDWR_)))
+    if (flock->type == F_WRLCK_ && !((fd_getflags(fd) & O_ACCMODE_) == O_WRONLY_) && !((fd_getflags(fd) & O_ACCMODE_) == O_RDWR_))
         return _EBADF;
 
     struct inode_data *inode = fd->inode;
diff --git a/kernel/fs.h b/kernel/fs.h
index ca6b071..32bb2b1 100644
--- a/kernel/fs.h
+++ b/kernel/fs.h
@@ -113,6 +113,7 @@ int mount_remove(struct mount *mount);
 extern struct list mounts;
 
 // open flags
+#define O_ACCMODE_ 3
 #define O_RDONLY_ 0
 #define O_WRONLY_ (1 << 0)
 #define O_RDWR_ (1 << 1)
```

**Comment by tbodt** [comment]
Looks correct to me, though I'd want the `fd_getflags(fd) & O_ACCMODE_` to be moved into a variable to simplify the rest of the code. Why don't you create a pull request?

**Comment by thunderkeys** [comment]
Sure, will work on that tomorrow.

**Comment by lyon-fnal** [comment]
Wow - thanks for working on this! Indeed ssh without kerberos makes this kinda moot, but looks like ssh can be compiled by hand with it turned on (like you did with curl). Quite awhile ago, when I had an android tablet, I did something similar for termux (https://github.com/termux/termux-packages/pull/1205). Termux distributes its own packages, so it was easy to change. Assuming we can hand-build ssh with kerberos, how would it be distributed? Many of my colleagues with iPads would be interested in this fix.   Maybe I'm getting ahead of myself.  I'll try to follow the instructions for making a development environment (@thunderkeys - I assume that's where you build curl - not on the iPad itself) and try openssh. Thanks again for all your work!!

**Comment by lyon-fnal** [comment]
BTW - I did find a rather crazy work-around for the bad file descriptor problem. If you `apk add heimdal` after installing `krb5`, it will add a binary `kcm`, which creates a kerberos cache daemon. (It won't overwrite the binaries from `krb5` - which is important for me because heimdal's `kinit` doesn't work with our server.) One can run `kcm` in the background and then tell `kinit/klist` to use the cache daemon instead of a file. That worked. But not a real solution.

**Comment by thunderkeys** [comment]
@lyon-fnal I've compiled ssh and curl and confirmed they work in an x86 alpinelinux vm, and it could be added to others if desired.  So hopefully once there's an updated iPad build, this would work for you or your teammates.

```
echo 'https://thunderkeys.net/alpine/community' >> /etc/apk/repositories
cd /etc/apk/keys
# get the key, e.g. via wget
wget https://thunderkeys.net/alpine/community/bma-5e56b175.rsa.pub

apk update
apk add --repository bma -u openssh-client
```

**Comment by thunderkeys** [comment]
I tested #649 in the iOS simulator and all worked as expected with the lock fix applied (kinit/klist work) and with my recompiled packages (curl/openssh/postgresql work with Kerberos/GSSAPI).

**Comment by tbodt** [comment]
The PR's in now so I'll close this.

**Comment by lyon-fnal** [comment]
Thanks again for all your work  - I was able to build and run in the simulator and I could log into my computing resources that use Kerberos authentication! WIth the current beta, I can use the Kerberos Cache Daemon trick and @thunderkeys build of ssh and it works on my iPad! Looking forward to the next beta that will make this even easier. 

You should realize that making Kerberos work on iOS is a really big deal! I’m not aware of any other iOS app that can do this - and many of us have been wishing for this feature for a long time. It will make my iPad way more useful.

**Comment by diggerdu** [comment]
> I tested #649 in the iOS simulator and all worked as expected with the lock fix applied (kinit/klist work) and with my recompiled packages (curl/openssh/postgresql work with Kerberos/GSSAPI).

Hi @thunderkeys, I installed the openssh-client package from your repo, but the ssh client still display `Unsupported option "GSSAPIAuthentication"` warninng. But I find that there a openssh-client-krb5 package in https://pkgs.alpinelinux.org/package/edge/. I changed the default apk repo to alpine edge and installed this pack, the warning disappeared.

**Comment by thunderkeys** [comment]
I haven't touched those in nearly two years, so I'm not really surprised they may no work.  I'm glad to see that the upstream packages have Kerberos/GSSAPI enabled now though!
