### ISSUE TITLE
unable to install kubectl

### ISSUE THREAD

**Issue by L3o-pold** [tbodt/ish#632]
Installing the binary and launching it will result in the error message: `./kubectl: line 2: syntax error: unexpected word (expecting ")")`

Using the docker image `i386/alpine:3.10` and installing kubectl binary words as expected.

I'm using:

```
apk add curl
curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
chmod +x ./kubectl
./kubectl -h
```

Actual result:
`./kubectl: line 2: syntax error: unexpected word (expecting ")")`

Expected result:
`kubectl controls the Kubernetes cluster manager.`

**Comment by tbodt** [comment]
This is because you're trying to run a 64 bit binary on a 32 bit emulated system.

Even if you get the 32 bit binary, that still won't work because go programs don't work. #57
