### ISSUE TITLE
How to save files

### ISSUE THREAD

**Issue by paalped** [tbodt/ish#635]
I’m sorry to post questions here as issue, cause I cant seam to find an answer.

I wonder if there is something Im neglecting, I cant seam to figure out how to do commands like: ESC, CTRL SHIFT and so on on my iphone 8? Is this implemented?
Ive tried to set backtick -> escape ok, but when I hit backtick ` theres no escape.
I tried map capslock escape:
And insert ESC into a file hoping for a magical escape, but in vain.

Any pointers would be appreciated!

**Comment by paalped** [comment]
Really copl app btw! Made it run django webframework on localhost, much fun 😊

**Comment by saagarjha** [comment]
They’re the buttons on the top part of the keyboard. Escape looks like ⎋.
