### ISSUE TITLE
App exits on startup when entering a faulty startup command 

### ISSUE THREAD

**Issue by realmayus** [tbodt/ish#637]
See this video: https://streamable.com/t1ecg
I entered ˋ/bin/start -fˋ without specifying a user.

 Crash dump: https://1drv.ms/u/s!Av5aJVOAQFRk4T5mUasSdhfPdbjv

**Comment by tbodt** [comment]
This isn't a crash, what you're seeing is the animation when a multiwindow app on iPad closes the current window.

> I entered ˋ/bin/start -fˋ without specifying a user.
Do you mean `/bin/login -f`?

**Comment by realmayus** [comment]
yes
