### ISSUE TITLE
/sys/class/net: no such file or directory

### ISSUE THREAD

**Issue by hazcod** [tbodt/ish#639]
Hi, love your work on this project!
I was fooling around and installed `airmon-ng`, where an execution resulted in: `ls /sys/class/net: No such file or directory`.

`apk add aircrack-ng && airmon-ng``

**Comment by tbodt** [comment]
iSH doesn't have direct access to the network card.

**Comment by God-mohib** [comment]
Ifconfig gives this output:

┌──(kali㉿localhost)-[~]
└─$ ifconfig
Warning: cannot open /proc/net/dev (Permission denied). Limited output.
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 1000  (UNSPEC)

rmnet_data2: flags=65<UP,RUNNING>  mtu 1500
        inet 10.45.149.2  netmask 255.255.255.252
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 1000  (UNSPEC)

rmnet_data3: flags=65<UP,RUNNING>  mtu 1500
        inet 10.102.46.89  netmask 255.255.255.252
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 1000  (UNSPEC)

wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.0.200  netmask 255.255.255.0  broadcast 192.168.0.255
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 3000  (UNSPEC)



But airmon-ng output shows : 

ls: cannot access '/sys/class/net': No such file or directory

This isn't a duplicate issue
