### ISSUE TITLE
Unable to load Nukkit Server for Java 8

### ISSUE THREAD

**Issue by GBprojekte** [tbodt/ish#640]
Unable to load nukkit-1.0-SNAPSHOT.jar

![52B545FB-5D68-403C-BE76-470453F5ADF7](https://user-images.githubusercontent.com/53085157/74385127-1997ec80-4df3-11ea-942e-9c8f8ad9475f.png)

**Comment by tbodt** [comment]
Please post the output of `dmesg`

**Comment by GBprojekte** [comment]
What is the command for dmesq

**Comment by tbodt** [comment]
`dmesg`

**Comment by GBprojekte** [comment]
-ash: dmesq: not found

**Comment by tbodt** [comment]
`dmesg`, not `dmesq`
