### ISSUE TITLE
Can not find a file.

### ISSUE THREAD

**Issue by javidsch** [tbodt/ish#641]
I see files on app, for example ssh client "Termius", the keys. (_mykey.pem_)
Searching this file... using linux command **"find"**

>find / -name mykey.pem
"no result"

>find / -name *.pem
"no result"

iSH has some limitations?

Thanks in advance.

**Comment by tbodt** [comment]
iSH can't see files in other app sandboxes. Where do you see mykey.pem?

**Comment by javidsch** [comment]
Hmm... I thought it is a terminal (the facto) for iOS/iPadOS.
From Google Drive app I opened the file (mykey.pem), and save as file... there were 3 folders (File app), was chose _Termius_(ssh client) folder

**Comment by tbodt** [comment]
You'll have to move it into iSH's sandbox using the Files app.
