### ISSUE TITLE
can't run ./configure as user

### ISSUE THREAD

**Issue by Lleuad** [tbodt/ish#644]
When I try to compile from source I have no problems as root, but when I try to run the `configure` script as a regular user I get the following:
```
./configure: This script requires a shell more modern than all
./configure: the shells that I found on your system.
./configure: Please tell bug-autoconf@gnu.org about your system,
./configure: including any error possibly output before this
./configure: message. Then install a modern shell, or manually run
./configure: the script under such a shell if you do have one.
```
Tried with [GSL-2.6](https://www.gnu.org/software/gsl/) and [Binutils-2.32](https://www.gnu.org/software/binutils/) on `ash` and `bash`. There is no `config.log`.

I'm on iPadOS 13.3.1, iSH version 1.0 (64)

**Comment by tbodt** [comment]
Turns out I fixed this almost 2 months ago in afd119b. New build coming soon.
