### ISSUE TITLE
Did you look into running device-native aarch64?

### ISSUE THREAD

**Issue by bracketttc** [tbodt/ish#646]
Alpine supports the processors in iOS devices. What made you do island emulation instead of running an appropriate architecture userland?

I think the project is great from a user perspective. Haven’t dived into the code.

**Comment by tbodt** [comment]
This is [in the FAQ](https://github.com/tbodt/ish/wiki/FAQ#q-why-does-ish-not-emulate-arm-or-some-other-architecture)

**Comment by bracketttc** [comment]
My bad. Looking at the GitHub page on iOS means I didn’t see the FAQ because it’s not called out in the README.
