### ISSUE TITLE
Feature: installing server executable

### ISSUE THREAD

**Issue by hazcod** [tbodt/ish#648]
Just throwing out this idea, but since there is the GitHub project [code-server](https://github.com/cdr/code-server): we could run a VS Code web server locally so we could theoretically run Visual Studio Code on iOS and use VS Code on Safari.

How long would the process be kept running in the background?

**Comment by tbodt** [comment]
code-server is written in node, see #90

**Comment by hazcod** [comment]
Good point.

**Comment by saagarjha** [comment]
No fun allowed
