### ISSUE TITLE
Feature Request: Support Screen Split in iPadOS

### ISSUE THREAD

**Issue by rkttu** [tbodt/ish#652]
I’m testing the iSH app for simple Django development environment on my iPad. I found that Django runs successfully on my iPad and iPhone. Especially, I want to run my Django server background, but as far as I know, iOS does not support true background process. Instead, I want to run the iSH as split window mode, so it can run continuously.

Always thanks your effort and I’m a great fan of iSH! Thank you. :-)

**Comment by tbodt** [comment]
As far as I'm aware, split window mode is supported. Is it not working for you?

**Comment by rkttu** [comment]
@tbodt Oh. I’m sorry. I misunderstood how to use the multitasking feature. I’m closing the issue. Thanks. :-D
