### ISSUE TITLE
Command ExternalBuildToolExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by vordenken** [tbodt/ish#655]
Tried building ish in xcode, failed with error "Command ExternalBuildToolExecution failed with a nonzero exit code"

It looks like meson was not found. "line 32: meson: command not found"

How do I fix this?

**Comment by tbodt** [comment]
Probably just need to install meson (`pip3 install meson`)

**Comment by vordenken** [comment]
Error is gone after this, thanks!
