### ISSUE TITLE
/clang:1:1: invalid linker name in argument '-fuse-ld=lld'

### ISSUE THREAD

**Issue by vordenken** [tbodt/ish#656]
This error appears while trying to build. I'm on macOS 10.15.3 with clang version 11.0.0 (clang-1100.0.33.17)

**Comment by tbodt** [comment]
As it says in the readme, you need to install LLD:
> - Clang and LLD (on mac, `brew install llvm`, on linux, `sudo apt install clang lld` or `sudo pacman -S clang lld` or whatever)

**Comment by vordenken** [comment]
My bad, jumped right to the 'Build for iOS' part. 
Thanks dude, keep up the great work!
