### ISSUE TITLE
patreon.com alternative? Crypto..

### ISSUE THREAD

**Issue by GETandSELECT** [tbodt/ish#661]
First of all a **huge thank you for this awesome app**. This is the best Open Source app in history of iPhone.

I wish to donate you money, but I don't have a Patreon account. Great would be If you accept Monero, Bitcoin and other cryptos.

cheers

**Comment by saagarjha** [comment]
I hear that bitcoin:1FLYyKzkZKZVS1RonnVGLEj8VT7bdvuaUW might be what you’re looking for.

**Comment by tbodt** [comment]
^ That address is on my website
