### ISSUE TITLE
rclone ?

### ISSUE THREAD

**Issue by magefesa** [tbodt/ish#666]
There is an official package, installed but does not works:

[rclone](https://pkgs.alpinelinux.org/packages?name=rclone&branch=edge)

Could be great

**Comment by magefesa** [comment]
Sorry, not here...

**Comment by tbodt** [comment]
What does it do instead of working?

**Comment by magefesa** [comment]
Throws an error... Thanks in advance,

Frank

--

**Comment by tbodt** [comment]
What specifically?

**Comment by magefesa** [comment]
Excuseme, I add an image on email. I attach here:
[Picture](https://www.dropbox.com/s/g74a6auduvy86cp/Foto%2025-3-20%2022%2045%2022.jpg?dl=1)

**Comment by tbodt** [comment]
That error is because you downloaded the 64 bit version but iSH is 32 bit.

**Comment by magefesa** [comment]
uops !!! My fault !!! Sorry this waste of time !!!

**Comment by magefesa** [comment]
One more question -....32bits, and arch ? ARM, 386 does nt works.... any help would be appreciated...

**Comment by tbodt** [comment]
You want 386. If that still doesn't work, what happens?

**Comment by magefesa** [comment]
Error is: “This program can only be run on processors with MMX support”

**Comment by tbodt** [comment]
Ah that's #57
