### ISSUE TITLE
ffmpeg support

### ISSUE THREAD

**Issue by calebhicks** [tbodt/ish#71]
Love what's happening here. Tried installing ffmpeg, and it worked! But all commands return Illegal instruction. 

My research leads me to believe it's a processor issue. Not sure what other information would be useful here, but happy to try.

Steps to reproduce:

```
apk add ffmpeg
ffmpeg
```

**Comment by tbodt** [comment]
I've added to the list, though it's somewhat low priority.

**Comment by calebhicks** [comment]
Fair enough! Thanks for all the work you're putting in to make it happen.

**Comment by tbodt** [comment]
ffmpeg now segfaults instead of reporting "illegal instruction".

**Comment by tbodt** [comment]
The mremap fix apparently fixed this as well as python.

**Comment by cliss** [comment]
@tbodt Are you sure this is working? Perhaps it’s just my example, but I just tried and it was no dice.

I was going `mp4` → `mkv`. See the below.

```
Stream mapping:                                                                                                                                                   
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))                                                                                                           
  Stream #0:1 -> #0:1 (aac (native) -> vorbis (libvorbis))                                                                                                        
Press [q] to stop, [?] for help                                                                                                                                   
Illegal instruction     
```

![image-1](https://user-images.githubusercontent.com/282460/49168362-4ef70e00-f305-11e8-8ce8-2ebd2c4f3ce6.jpg)

**Comment by tbodt** [comment]
The fix isn't in the testflight build, did you build from source?

**Comment by cliss** [comment]
Oh oh oh! Apologies; I *ass*umed this was in the most recent testflight build.

![](https://media.giphy.com/media/jUwpNzg9IcyrK/source.gif)
