### ISSUE TITLE
ping does not work

### ISSUE THREAD

**Issue by sgonzalez** [tbodt/ish#76]
Santiagos-iPad:~/stuff# ping google.com                                                                                                    
    PING google.com (216.58.193.142): 56 data bytes                                                                                            
    ping: can't create raw socket: Invalid argument

**Comment by Mnpn03** [comment]
Ping will probably never work as sending ping packets requires root privileges.

**Comment by tbodt** [comment]
Interesting, but then what if a program creates a raw socket and then tries to send a non-ICMP packet?

**Comment by woachk** [comment]
@tbodt on something related, Windows doesn't support raw sockets at all, and has the ICMP transponder implemented in the kernel

**Comment by lunixbochs** [comment]
I imagine a non-ICMP packet will throw an error on send, which is ok.

**Comment by tbodt** [comment]
EPIPE seems appropriate enough.

**Comment by abdelhalim** [comment]
Same error with nmap
