### ISSUE TITLE
confusing motd

### ISSUE THREAD

**Issue by abraxxa** [tbodt/ish#78]
You can setup the system with the command: setup-
alpine                                           
                                                 
You may change this message by editing /etc/motd.
                                                 
Alex-iPhone:~# setup-alpine                      
-ash: setup-alpine: not found

I guess that‘s just a default of Alpine linux but should be changed.

**Comment by tbodt** [comment]
Agreed, it should.

**Comment by tbodt** [comment]
I wrote this replacement motd:
```
Welcome to Alpine!

You can install packages with: apk add <package>

You may change this message by editing /etc/motd.
```
How does that sound?

**Comment by abraxxa** [comment]
Great!
Maybe include a link to the Alpine docs as well.

**Comment by tbodt** [comment]
This is in the latest build.
