### ISSUE TITLE
Irssi does not work

### ISSUE THREAD

**Issue by macBender** [tbodt/ish#81]
Trying to run irssi results in a ‘Illegal Instruction’ error

# apk add irrsi 
...
# irssi
Illegal Instruction
#

There are no IOS IRC apps with xdcc support so I’d love for irssi to work!

**Comment by tbodt** [comment]
Added to the list!

**Comment by tbodt** [comment]
irssi now gives a "bad system call" for eventfd.

**Comment by newbold** [comment]
dmesg output is `3 missing syscall 328`.

**Comment by tbodt** [comment]
irssi now opens but stops responding to input after you type a /connect command.

**Comment by tbodt** [comment]
The fix for #204 somehow fixed this too

**Comment by macBender** [comment]
Tested dcc transfers in Irssi.  Worked as expected for my use case.  Also unzip and unrar worked too on the transfered files.  Well done!

**Comment by Ronsor** [comment]
On the latest version, irssi gives "Illegal instruction" again

**Comment by b1scoito** [comment]
Irssi appears to not work with me. It opens but just freezes as soon as I connect.
