### ISSUE TITLE
`file` does not work

### ISSUE THREAD

**Issue by yifanlu** [tbodt/ish#82]
```
# apk add file
# file test.txt
Bad system call
```

**Comment by jtvjan** [comment]
Same with node.

```shellsession
# apk add nodejs
# node
Bad system call
```

**Comment by tripplet** [comment]
Also

```
# file /etcudhcpd.conf
/etc/udhcpd.conf: ASCII text

# file /bin/echo                                                                           
/bin/echo: symbolic link to /bin/busybox

# file /etc/sysctl.conf                                                                            
Bad system call

# file /bin/busybox
>>App crashes
```

**Comment by tbodt** [comment]
This sounds like it'd be fun to debug. Added to the list.

**Comment by gpmcadam** [comment]
Same for Elixir and iex

**Comment by tbodt** [comment]
The issues with file, node, and elixir are probably separate issues even though the error is the same.

**Comment by gpmcadam** [comment]
Actually looking at iex, the error is:

```
erts_poll_init(): Failed to get max number of files: unknown                                                                                                      
Aborted
```

So may be worth putting an a different issue?

**Comment by tbodt** [comment]
@gpmcadam Yeah, please open a new issue for that.

**Comment by gpmcadam** [comment]
@tbodt Done. See #104

**Comment by zhuowei** [comment]
@tripplet I can't reproduce your first example with the current master branch: maybe it's fixed?

```
# file /etc/sysctl.conf
/etc/sysctl.conf: ASCII text
```

The /etc/busybox [still crashes](https://gist.github.com/zhuowei/ae0791024ae56d9e63e326bcb8d6b508).

Master branch (728b70b391567df140afc7c91d5718e0c3e73f32), iOS 12.1, the default Alpine root fs, DEBUG_strace turned on.

**Comment by tbodt** [comment]
I wonder why read() returns EFAULT when given an address that was just returned from mmap.

**Comment by tbodt** [comment]
file works in the latest commit.

**Comment by tripplet** [comment]
I also can't reproduce the issue with sysctl.conf.
Works fine now, thanks for fixing it.
