### ISSUE TITLE
Include commit hash in /etc/alpine-release?

### ISSUE THREAD

**Issue by kherrera-ebsco** [tbodt/ish#83]
By including the last commit hash in the Git log somewhere in the release information, we can just look it up on GitHub and know what fixes are available or missing.

An example of why this is useful: I’m using v31 and BASH is not working (install fails and bad sys call on running `bash`). There is a closed issue about it being fixed in master. Not knowing if v31 is the current master (bug fix not included, bug fix not working, etc?), I would need to ask here what the last commit was for v31.

**Comment by tbodt** [comment]
Normally I tag the commit for a build with `builds/beta/<id>`, but I forgot for build 31. I've fixed that, and also added the commit hash to the build release notes.
