### ISSUE TITLE
rm -rf /

### ISSUE THREAD

**Issue by CrosseyeJack** [tbodt/ish#86]
It had to be done ;-) Works as expected. But now the application crashes on start up. A error pops up very very briefly and then app just crashes back to SpringBoard.

Deleting and Reinstalling the app restores functionality. 

https://youtu.be/dsvQL_CTmVA

**Comment by jtvjan** [comment]
Could be fixed by implementing #75

**Comment by tbodt** [comment]
For now, the reset button is to reinstall the app. Eventually you'll be able to have multiple sandboxes and so on and so forth, including the option to destroy and recreate them.
