### ISSUE TITLE
Files disappear after killing and restarting

### ISSUE THREAD

**Issue by jckarter** [tbodt/ish#97]
Sorry for the vague description. Immediately after installing iSH I installed a bunch of different apks, including gcc, musl-dev, and ssh. I tried killing iSH by swiping up in the multitasking view out of curiosity, and when I started it up again, all the apks I had installed were still shown as installed, but various files were missing, including the gcc binary.

**Comment by tbodt** [comment]
This tends to happen with the current design of the filesystem. File metadata is stored in a database, and if the app is killed, the metadata might not have been written out to the database even though the file has been created. There are ways I can try and make it more reliable, but a redesign of the filesystem is likely the real solution.

**Comment by saagarjha** [comment]
Interestingly, I've seemingly ended up in the state where I run `ls` and it spits out `ls: test.c: No such file or directory` of its own accord. Of course, this is a file I created earlier, but I can't open it at all through iSH even though the filesystem knows it's there–however, the file provider extension *can* preview and open the file. Is this the same issue you're seeing, @jckarter?

**Comment by jckarter** [comment]
Hm, I hadn't noticed that. In my case, I did notice that the file provider wasn't always updating to reflect new files I'd created (for example, I'd do `cat >foo.txt` and not see foo.txt show up in Files), which seems like a different issue.

**Comment by tbodt** [comment]
LMDB is looking like a good alternative: http://www.lmdb.tech/doc/

**Comment by tbodt** [comment]
iSH is now using SQLite which is anything if not reliable.
